-- Protected Script (Thai)
-- Script ID: 015595b2817bf46db12fb25184d26203
-- Created: 2025-10-27T13:59:29.434Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()


local moduleLink = "https://raw.githubusercontent.com/checkurasshole/PET/refs/heads/main/AnimeRise"
local Module = loadstring(game:HttpGet(moduleLink))()

local Options = Library.Options
local Toggles = Library.Toggles

local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Footer = "Version: 1.0",
    NotifySide = "Right",
    ShowCustomCursor = true,
    Size = UDim2.new(0, 460, 0, 480),
})

local Tabs = {
    Main = Window:AddTab("หลัก", "user"),
    Pets = Window:AddTab("สัตว์เลี้ยง", "package"),
    Misc = Window:AddTab("เบ็ดเตล็ด", "sparkles"),
    ["UI Settings"] = Window:AddTab("À¸à¸±à¹à¸à¸à¹à¸²à¸£à¸¹à¸à¹à¸à¸à¸à¸²à¸£à¹à¸à¸·...", "settings"),
}

local LeftGroupBox = Tabs.Main:AddLeftGroupbox("การทำฟาร์มอัตโนมัติ")
local RightGroupBox = Tabs.Main:AddRightGroupbox("การเลือก NPC")
local MiscGroupBox = Tabs.Misc:AddLeftGroupbox("เบ็ดเตล็ด")
local PetGroupBox = Tabs.Pets:AddLeftGroupbox("การจัดการสัตว์เลี้ยง")
local ShadowGroupBox = Tabs.Pets:AddRightGroupbox("Shadow Essence")

LeftGroupBox:AddToggle("AutoRank", {
    Text = "อันดับขึ้นโดยอัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoRank = Value
    end,
})

LeftGroupBox:AddToggle("AutoAttack", {
    Text = "โจมตีอัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoAttack = Value
    end,
})

LeftGroupBox:AddToggle("GrabDrops", {
    Text = "เก็บไอเท็มที่ตกหล่น",
    Default = false,
    Callback = function(Value)
        getgenv().GrabDrops = Value
    end,
})

LeftGroupBox:AddToggle("AutoBuyZone", {
    Text = "โซนซื้ออัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoBuyZone = Value
    end,
})

LeftGroupBox:AddToggle("AutoAr", {
    Text = "การเกิดใหม่ของ Ascension โดยอัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoAr = Value
    end,
})

LeftGroupBox:AddToggle("AttackNPC", {
    Text = "โจมตีตัวละครที่ไม่ใช่ผู้เล่น",
    Default = false,
    Callback = function(Value)
        getgenv().AttackNPC = Value
    end,
})

LeftGroupBox:AddToggle("AutoAttackNearest", {
    Text = "โจมตีศัตรูที่ใกล้ที่สุดโดยอัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoAttackNearest = Value
    end,
})

Module.availableNPCs = Module.scanAllNPCs()
table.insert(Module.availableNPCs, 1, "None")

Module.NPCDropdown = RightGroupBox:AddDropdown("NPCSelector", {
    Values = Module.availableNPCs,
    Default = 1,
    Multi = false,
    Text = "เลือกอักขระที่ไม่ใช่ผู้เล่น",
    Callback = function(Value)
        Module.selectedNPC = Value
    end,
})

RightGroupBox:AddButton({
    Text = "เข้าสู่การต่อสู้ด้วยการจู่โจม",
    Func = function()
        Module.joinRaid()
    end,
})

RightGroupBox:AddToggle("AutoJoinRaid", {
    Text = "เข้าสู่การต่อสู้จู่โจมโดยอัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoJoinRaid = Value
    end,
})

PetGroupBox:AddToggle("AutoEquipBest", {
    Text = "สวมใส่สัตว์เลี้ยงที่แข็งแรงที่สุดโดยอัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoEquipBest = Value
    end,
})

PetGroupBox:AddSlider("EquipInterval", {
    Text = "เวลารออุปกรณ์ (วินาที)",
    Default = 15,
    Min = 5,
    Max = 600,
    Rounding = 0,
    Compact = false,
    Callback = function(Value)
        getgenv().EquipInterval = Value
    end,
})

PetGroupBox:AddButton({
    Text = "จัดเตรียมสัตว์เลี้ยงที่แข็งแรงที่สุด (ด้วยตนเอง)",
    Func = function()
        Module.equipBestPets()
    end,
})

PetGroupBox:AddToggle("AutoRollEgg", {
    Text = "ฟักไข่โดยอัตโนมัติ",
    Default = false,
    Callback = function(Value)
        getgenv().AutoRollEggs = Value
    end,
})

PetGroupBox:AddDropdown("EggMap", {
    Values = {"Lost Temple", "Desert", "Snow", "Volcano"},
    Default = 1,
    Multi = false,
    Text = "เลือกแผนที่สำหรับการฟักไข่",
    Callback = function(Value)
        getgenv().SelectedEggMap = Value
    end,
})

ShadowGroupBox:AddLabel("Shadow Essence Generator")
ShadowGroupBox:AddInput("ShadowAmount", {
    Default = "9e15",
    Numeric = false,
    Finished = false,
    Text = "จำนวน",
    Placeholder = "Enter amount (example: 9e15)",
})

ShadowGroupBox:AddButton({
    Text = "สร้างเอสเซนส์เงาที่ไม่มีที่สิ้นสุด",
    Func = function()
        local amount = Options.ShadowAmount.Value
        if amount == "" then return end
        Module.giveShadowEssence(amount)
    end,
})

MiscGroupBox:AddToggle("AntiAFK", {
    Text = "Anti Away-From-Keyboard",
    Default = false,
    Callback = function(Value)
        getgenv().AntiAFK = Value
    end,
})

local MenuGroup = Tabs["UI Settings"]:AddLeftGroupbox("เมนู")

MenuGroup:AddToggle("KeybindMenuOpen", {
    Default = Library.KeybindFrame.Visible,
    Text = "แสดงคีย์ลัดบนแป้นคีย์บอร์ด",
    Callback = function(value)
        Library.KeybindFrame.Visible = value
    end,
})

MenuGroup:AddToggle("ShowCustomCursor", {
    Text = "เคอร์เซอร์เมาส์แบบกำหนดเอง",
    Default = true,
    Callback = function(Value)
        Library.ShowCustomCursor = Value
    end,
})

MenuGroup:AddDropdown("NotificationSide", {
    Values = { "Left", "Right" },
    Default = "Right",
    Text = "ตำแหน่งการแจ้งเตือนไอคอน",
    Callback = function(Value)
        Library:SetNotifySide(Value)
    end,
})

MenuGroup:AddDivider()
MenuGroup:AddLabel("Menu Hotkey"):AddKeyPicker("MenuKeybind", { Default = "RightShift", NoUI = true, Text = "ปุ่มลัดเมนู" })

MenuGroup:AddButton("Close Script", function()
    Library:Unload()
end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("AutoFarm")
SaveManager:SetFolder("AutoFarm/game")
SaveManager:BuildConfigSection(Tabs["UI Settings"])
ThemeManager:ApplyToTab(Tabs["UI Settings"])

Module.startLoops()