-- COMBOWICK Loader (Chinese (Simplified))
-- Script ID: 01e83de5f315e8a7afcc49c56e2564c3
-- Updated: 2026-07-10T05:47:11.709Z
-- Auto-generated by Lua Script Vault

if _G.COMBOWICK_ACTIVE then return end

local HttpService = game:GetService("HttpService")
local Players     = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

pcall(function() if not game:IsLoaded() then game.Loaded:Wait() end end)
do
    local t = tick()
    while not LocalPlayer and (tick() - t) < 10 do task.wait(); LocalPlayer = Players.LocalPlayer end
end
if not LocalPlayer then return end
if not game.PlaceId or game.PlaceId == 0 then return end

local MODULE_URL = "https://raw.githubusercontent.com/checkurasshole/combowick-test/main/combowick_module.lua"
local repo       = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"

local M
do
    local ok, m = pcall(function() return loadstring(game:HttpGet(MODULE_URL))() end)
    if ok and type(m) == "table" then M = m end
end
if not M then
    warn("[COMBOWICK] module failed to load from " .. tostring(MODULE_URL))
    return
end

M.queueOnTeleport()

if M.tryVaultWhitelist() then return end
if M.tryHwidKey() then return end

local preCheck = M.withRetry(M.checkSession, M.hwid)
if preCheck ~= nil and preCheck.status ~= "game_not_allowed" then
    if M.tryFreeSession(preCheck) then return end
end
preCheck = preCheck or { status = "error", remaining = 0, disabled = false }

do
    pcall(function() if getgenv and getgenv().Library then getgenv().Library:Unload() end end)
    local targets = {}
    if gethui then local ok, h = pcall(gethui); if ok and h then table.insert(targets, h) end end
    table.insert(targets, game:GetService("CoreGui"))
    for _, target in ipairs(targets) do
        for _, v in ipairs(target:GetChildren()) do
            local n = v.Name
            if n == "Obsidian" or n == "ObsidianLoading" or n == "LinoriaGui" then pcall(v.Destroy, v) end
        end
    end
end

local Library      = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager  = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()
local Options      = Library.Options

local VaultModule       = M.VaultModule
local execPremiumScript = M.execPremiumScript

local function safeSet(lbl, text) pcall(function() lbl:SetText(text) end) end

local Window = Library:CreateWindow({
    Title = "COMBOWICK", Footer = "免费版", NotifySide = "Right",
    ShowCustomCursor = false, AutoShow = true, Size = UDim2.fromOffset(560, 340),
})
local Tabs = {
    Main    = Window:AddTab("主页",        "user"),
    Key     = Window:AddTab("Premium 密钥", "key"),
    Suggest = Window:AddTab("反馈建议", "message-square"),
    UI      = Window:AddTab("界面设置", "settings"),
}

if M.looksTampered() then
    Library:Notify({Title="⚠️ 检测到篡改", Description="检测到你的执行器中存在被修改的函数。", Time=6})
end

local preRemaining = tonumber(preCheck.remaining) or 0
local preStatus      = preCheck.status
local gameDisabled   = preCheck.disabled == true
local gameUnsupported = preStatus == "game_not_allowed"

local InfoGroup = Tabs.Main:AddLeftGroupbox("免费会话", "info")
local lSession  = InfoGroup:AddLabel(
    (not gameDisabled and (preStatus == "allowed" or preStatus == "session_active") and preRemaining > 0)
        and string.format("会话时长：%s", M.formatTime(preRemaining)) or "会话时长：—", true)
local lCooldown = InfoGroup:AddLabel(
    (preStatus == "cooldown" and preRemaining > 0)
        and string.format("冷却时间：%s", M.formatTime(preRemaining)) or "冷却时间：—", true)
if gameUnsupported then
    InfoGroup:AddLabel("🚫 该游戏暂不支持。", true)
elseif gameDisabled then
    InfoGroup:AddLabel("⛔ 该游戏无法使用免费版。", true)
else
    InfoGroup:AddLabel("并非所有游戏都支持免费版。", true)
end
InfoGroup:AddDivider()
InfoGroup:AddLabel("升级 11 小时密钥即可取消冷却。", true)
InfoGroup:AddButton({
    Text = "复制密钥链接", Tooltip = "combowick.com/verify/provider-select",
    Func = function()
        pcall(function() setclipboard(M.KEY_URL) end)
        Library:Notify({Title="COMBOWICK", Description="链接已复制，请粘贴到浏览器中。", Time=4})
    end,
})
local StatusGroup = Tabs.Main:AddRightGroupbox("状态", "shield")
local statusLabel = StatusGroup:AddLabel("检查中…", true)
local timerLabel  = StatusGroup:AddLabel("", true)
local hintLabel   = StatusGroup:AddLabel("", true)

local AnnounceGroup = Tabs.Main:AddRightGroupbox("📢 公告", "megaphone")
local announceLabel = AnnounceGroup:AddLabel("正在加载公告…", true)
task.spawn(function()
    local text
    local ok, body = pcall(function() return game:HttpGet(M.ANNOUNCE_URL) end)
    if ok and type(body) == "string" and #body > 0 then
        local dok, data = pcall(function() return HttpService:JSONDecode(body) end)
        if dok and data ~= nil then
            local a = data
            if type(a) == "table" and a[1] ~= nil then a = a[1] end
            if type(a) == "table" then
                if a.enabled ~= false and a.message then
                    text = (a.title and (tostring(a.title) .. "\n") or "") .. tostring(a.message)
                end
            elseif type(a) == "string" then
                text = a
            end
        elseif not body:match("^%s*<") then
            text = body:sub(1, 400)
        end
    end
    safeSet(announceLabel, (text and #M.trim(text) > 0) and M.trim(text) or "当前暂无公告。")
end)

local savedKey = ""
if VaultModule and VaultModule.loadKey then
    local ok, k = pcall(VaultModule.loadKey)
    if ok and type(k) == "string" then savedKey = k end
end
local keyInputValue = savedKey

local KeyGroup = Tabs.Key:AddLeftGroupbox("输入你的密钥")
KeyGroup:AddInput("KeyInput", {
    Default          = savedKey,
    Numeric          = false,
    Finished         = false,
    ClearTextOnFocus = false,
    Text             = "密钥 🔑",
    Placeholder      = "在此粘贴你的密钥…",
    Callback         = function(v) keyInputValue = v end,
})
local function submitKey(key)
    key = M.cleanKey(key)
    if key == "" then
        Library:Notify({Title="⚠️ 未输入密钥", Description="请输入你的密钥。", Time=3})
        return
    end
    if VaultModule and VaultModule.validateKey then
        local ok = VaultModule.validateKey(key, M.hwid, Library)
        if ok then
            Library:Notify({Title="🔓 加载中", Description="正在加载 Premium 脚本…", Time=2})
            if VaultModule.startSessionMonitoring then pcall(VaultModule.startSessionMonitoring, M.hwid) end
            if getgenv then pcall(function() getgenv().VaultReady = true end) end
            if M.safeToLoad() and execPremiumScript then pcall(execPremiumScript) end
            task.wait(2)
            pcall(function() Library:Unload() end)
        else
            Library:Notify({Title="❌ 密钥无效", Description="该密钥无效，请检查后重试。", Time=4})
        end
    else
        local kr = M.withRetry(M.checkKey, M.encryptedHWID)
        if kr and kr.success == true then
            local url = M.getChronicleScript(game.PlaceId)
            if url and M.runUrl(url) then task.wait(1); pcall(function() Library:Unload() end); return end
        end
        Library:Notify({Title="密钥校验", Description="未找到有效密钥。请在网站上激活密钥，然后重新运行脚本。", Time=6})
    end
end

local function readKeyFromBox()
    local raw
    pcall(function()
        local holder = Options and Options.KeyInput and Options.KeyInput.Holder
        local box = holder and holder:FindFirstChildOfClass("TextBox")
        if box then raw = box.Text end
    end)
    local key = M.cleanKey(raw)
    if key == "" then key = M.cleanKey(Options and Options.KeyInput and Options.KeyInput.Value) end
    if key == "" then key = M.cleanKey(keyInputValue) end
    return key
end

KeyGroup:AddButton({
    Text = "✅ 提交密钥",
    Func = function() submitKey(readKeyFromBox()) end,
})
KeyGroup:AddButton({
    Text = "🔗 获取密钥",
    Func = function()
        pcall(function() setclipboard(M.KEY_URL) end)
        Library:Notify({Title="已复制", Description="密钥链接已复制。", Time=2})
    end,
})

local HWIDGroup = Tabs.Key:AddRightGroupbox("你的 HWID")
HWIDGroup:AddLabel(M.hwid, true)
HWIDGroup:AddButton({
    Text = "📋 复制 HWID",
    Func = function()
        pcall(function() setclipboard(M.hwid) end)
        Library:Notify({Title="已复制", Description="HWID 已复制。", Time=2})
    end,
})
HWIDGroup:AddButton({
    Text = "🔒 复制加密 HWID",
    Func = function()
        pcall(function() setclipboard(M.encryptedHWID) end)
        Library:Notify({Title="已复制", Description="加密 HWID 已复制。", Time=2})
    end,
})

local FEEDBACK_COOLDOWN, lastFeedback = 20, 0
local ERRMAP = {
    empty = "消息为空。", no_links = "不允许包含链接。",
    too_long = "消息过长（最多 500 字符）。", rate_limited = "你已达到 3 条消息上限，请稍后再试。",
    busy = "服务器繁忙，请重试。", banned = "你无权发送反馈。",
    discord_error = "发送失败，请重试。", network = "网络错误。",
    no_request = "你的执行器无法发送请求。", bad_response = "服务器返回了意外的响应。",
    unreachable = "你的执行器无法连接服务器（TLS 错误），请更换执行器。",
}
local FG = Tabs.Suggest:AddLeftGroupbox("建议 / 帮助", "message-square")
FG:AddDropdown("FeedbackType", {Text = "类型", Values = {"Suggestion", "Bug", "Help"}, Default = "Suggestion", Callback = function() end})
FG:AddInput("FeedbackMsg", {Default = "", Numeric = false, Finished = false, ClearTextOnFocus = false, Text = "消息", Placeholder = "输入你的消息（最多 500 字符，不含链接）"})
local fbStatus = FG:AddLabel("", true)
FG:AddButton({
    Text = "📨 Send",
    Func = function()
        local now = tick()
        if now - lastFeedback < FEEDBACK_COOLDOWN then
            safeSet(fbStatus, string.format("请等待 %d 秒后再发送。", math.ceil(FEEDBACK_COOLDOWN - (now - lastFeedback))))
            return
        end
        local ftype = tostring((Options.FeedbackType and Options.FeedbackType.Value) or "Suggestion"):lower()
        local msg   = M.trim((Options.FeedbackMsg and Options.FeedbackMsg.Value) or "")
        if msg == "" then safeSet(fbStatus, "消息为空。"); return end
        if #msg > 500 then safeSet(fbStatus, "消息过长（最多 500 字符）。"); return end
        local low = msg:lower()
        if low:find("http", 1, true) or low:find("discord.gg", 1, true) or low:find("www.", 1, true) or low:find(".gg/", 1, true) then
            safeSet(fbStatus, "不允许包含链接。"); return
        end
        safeSet(fbStatus, "发送中…")
        task.spawn(function()
            local sok, err = M.sendFeedback(ftype, msg, (preCheck and preCheck.session_token) or "")
            if sok then
                lastFeedback = tick()
                safeSet(fbStatus, "✅ 已发送，谢谢！")
                pcall(function() Options.FeedbackMsg:SetValue("") end)
                Library:Notify({Title = "COMBOWICK", Description = "你的反馈已发送，谢谢！", Time = 3})
            else
                safeSet(fbStatus, ERRMAP[err] or ("发送失败：" .. tostring(err)))
            end
        end)
    end,
})
FG:AddLabel("每小时最多 3 条消息，不含链接或提及。", true)

local HelpGroup = Tabs.Suggest:AddRightGroupbox("帮助 / 常见问题", "life-buoy")
HelpGroup:AddButton({
    Text = "💬 加入 Discord",
    Tooltip = M.DISCORD_INVITE,
    Func = function()
        pcall(function() setclipboard(M.DISCORD_INVITE) end)
        Library:Notify({Title = "COMBOWICK", Description = "Discord 链接已复制，请粘贴到浏览器中。", Time = 4})
    end,
})
HelpGroup:AddDivider()
HelpGroup:AddLabel("❓ 我如何获取 Premium？\n在 combowick.com/verify 获取密钥，然后粘贴到 Premium 密钥标签页中，点一下即可。", true)
HelpGroup:AddLabel("⏳ 我为什么处于冷却中？\n免费版在两次会话之间有等待期。11 小时密钥可完全取消冷却。", true)
HelpGroup:AddLabel("🎮 在我的游戏里无法使用。\n并非所有游戏都支持免费版。请在我们的 Discord 中查看支持的游戏列表。", true)
HelpGroup:AddLabel("🔑 我的 HWID 是什么？\n它是你的硬件 ID。如果客服需要，可在 Premium 密钥标签页中复制。", true)

task.spawn(function()
    safeSet(statusLabel, "正在验证…")

    local result = M.withRetry(M.checkSession, M.hwid)

    if result == nil then
        safeSet(statusLabel, "状态：失败")
        Library:Notify({Title="COMBOWICK", Description="会话校验失败。", Time=5})

    elseif result.status == "allowed" or result.status == "session_active" then
        if result.disabled then
            safeSet(statusLabel, "⛔ 游戏已禁用")
            safeSet(hintLabel, "此处无法使用免费版，请获取密钥。")
            Library:Notify({Title="COMBOWICK", Description="该游戏已禁用免费版，请使用密钥。", Time=6})
            return
        end
        local token = result.session_token
        if type(token) ~= "string" or #token < 20 then
            safeSet(statusLabel, "状态：失败")
        else
            safeSet(statusLabel, "状态：已验证")
            Library:Notify({Title="COMBOWICK", Description="你已通过验证。", Time=3})
            _G.COMBOWICK_FREE   = true
            _G.COMBOWICK_ACTIVE = true
            local remaining = tonumber(result.remaining) or 0
            task.spawn(function()
                while remaining > 0 do
                    local fmt = M.formatTime(remaining)
                    safeSet(timerLabel, string.format("剩余时间：%s", fmt))
                    safeSet(lSession, string.format("会话时长：%s", fmt))
                    task.wait(1); remaining = remaining - 1
                end
                safeSet(timerLabel, "会话已过期。")
                safeSet(lSession, "会话时长：已过期")
                _G.COMBOWICK_ACTIVE = false
                pcall(function() Library:Unload() end)
                task.wait(0.5)
                M.reloadExist()
            end)
            local scriptUrl = M.getScriptForGame(token)
            if M.loadFreeScript(scriptUrl, token) then task.wait(2); pcall(function() Library:Unload() end) end
        end

    elseif result.status == "cooldown" then
        local remaining = tonumber(result.remaining) or 0
        safeSet(statusLabel, "冷却中")
        safeSet(hintLabel, "获取 11 小时密钥，或等待冷却结束。")
        Library:Notify({Title="COMBOWICK", Description="你正处于冷却中。获取密钥即可跳过等待。", Time=6})
        task.spawn(function()
            while remaining > 0 do
                local fmt = M.formatTime(remaining)
                safeSet(timerLabel, string.format("冷却时间：%s", fmt))
                safeSet(lCooldown, string.format("冷却时间：%s", fmt))
                task.wait(1); remaining = remaining - 1
            end
            safeSet(timerLabel, "冷却已结束。")
            safeSet(lCooldown, "冷却时间：已结束")
            safeSet(hintLabel, "")
            Library:Notify({Title="COMBOWICK", Description="冷却已结束，正在重新加载…", Time=3})
            pcall(function() Library:Unload() end)
            task.wait(0.5)
            M.reloadExist()
        end)

    elseif result.status == "throttled" then
        local remaining = tonumber(result.remaining) or 0
        safeSet(statusLabel, "请求过多")
        safeSet(hintLabel, "请求过多，请稍候。")
        Library:Notify({Title="COMBOWICK", Description="请求过多，请稍等片刻。", Time=5})
        task.spawn(function()
            while remaining > 0 do
                safeSet(timerLabel, string.format("%s 后重试", M.formatTime(remaining)))
                task.wait(1); remaining = remaining - 1
            end
            safeSet(timerLabel, "正在重新加载…")
            safeSet(hintLabel, "")
            pcall(function() Library:Unload() end)
            task.wait(0.5)
            M.reloadExist()
        end)

    elseif result.status == "disabled" then
        safeSet(statusLabel, "服务已暂停")
        safeSet(hintLabel, "COMBOWICK 暂时离线。")
        Library:Notify({Title="COMBOWICK", Description="服务当前已禁用，请稍后再试。", Time=6})

    elseif result.status == "banned" then
        safeSet(statusLabel, "已封禁")
        Library:Notify({Title="COMBOWICK", Description="你已被封禁。", Time=5})

    elseif result.status == "game_not_allowed" then
        safeSet(statusLabel, "🚫 游戏不支持")
        safeSet(hintLabel, "该游戏暂不支持。如有可用脚本，Premium 密钥仍然有效。")
        Library:Notify({Title="COMBOWICK", Description="该游戏暂不支持。", Time=6})

    else
        safeSet(statusLabel, "错误")
        safeSet(hintLabel, "无法连接服务器，请重新运行脚本。")
        Library:Notify({Title="COMBOWICK", Description=tostring(result.message or "发生未知错误。"), Time=5})
    end
end)

local MenuGroup = Tabs.UI:AddLeftGroupbox("菜单", "wrench")
MenuGroup:AddToggle("ShowCustomCursor", {Text="自定义光标", Default=false, Callback=function(v) Library.ShowCustomCursor = v end})
MenuGroup:AddLabel("菜单快捷键"):AddKeyPicker("MenuKeybind", {Default="RightShift", NoUI=true, Text="菜单快捷键"})
MenuGroup:AddButton({Text="卸载", Func=function() pcall(function() Library:Unload() end) end})
Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({"MenuKeybind"})
ThemeManager:SetFolder("COMBOWICK")
SaveManager:SetFolder("COMBOWICK/game")
SaveManager:BuildConfigSection(Tabs.UI)
ThemeManager:ApplyToTab(Tabs.UI)
SaveManager:LoadAutoloadConfig()
