-- Ant Empire Module
-- Script ID: 092c95fe0ffb95b6c35c3996a6dd0edb
-- Created: 2026-10-09T19:08:21.000Z
-- Source: External API
-- Auto-generated by Lua Script Vault

return function(L)
local CONFIG = {
    DISCORD_INVITE = "",
    LOADER = "",
    VERSION = "combowick-antempire-1.0",
    PLACE_ID = 78490532994307,
}
if not game:IsLoaded() then game.Loaded:Wait() end
if game.PlaceId ~= CONFIG.PLACE_ID then return end
local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Workspace         = game:GetService("Workspace")
local RunService        = game:GetService("RunService")
local HttpService       = game:GetService("HttpService")
local VirtualUser       = game:GetService("VirtualUser")
local TeleportService   = game:GetService("TeleportService")
local UserInputService  = game:GetService("UserInputService")
local lp = Players.LocalPlayer
while not lp do task.wait(); lp = Players.LocalPlayer end
if _G.__CW_ANT_CLEAN then pcall(_G.__CW_ANT_CLEAN) end
local RUNNING = true
local CONNS, CLEANERS = {}, {}
local function track(c) if c then CONNS[#CONNS + 1] = c end return c end
local function onClean(fn) CLEANERS[#CLEANERS + 1] = fn end
_G.__CW_ANT_CLEAN = function()
    RUNNING = false
    for _, fn in ipairs(CLEANERS) do pcall(fn) end
    for _, c in ipairs(CONNS) do pcall(function() c:Disconnect() end) end
    CONNS, CLEANERS = {}, {}
end
local Opt, Toggles
local function on(k) local t = Toggles and Toggles[k]; return t and t.Value end
local function val(k, d) local o = Opt and Opt[k]; if o and o.Value ~= nil then return o.Value end return d end
local function msel(k)
    local v = val(k); if type(v) ~= "table" then return nil end
    local s, any = {}, false
    for key, x in pairs(v) do if x then s[key] = true; any = true end end
    return any and s or nil
end
local function setText(lbl, txt) if lbl then pcall(function() lbl:SetText(txt) end) end end
local notify = function() end
local SUF = { "K", "M", "B", "T", "Qa", "Qi", "Sx", "Sp", "Oc", "No" }
local function fmt(n)
    n = tonumber(n) or 0
    if n < 1000 then return tostring(math.floor(n)) end
    local i = 0
    while n >= 1000 and i < #SUF do n = n / 1000; i = i + 1 end
    return string.format(n < 10 and "%.2f%s" or (n < 100 and "%.1f%s" or "%.0f%s"), n, SUF[i])
end
local MULT = { k = 1e3, m = 1e6, b = 1e9, t = 1e12, qa = 1e15, qi = 1e18, sx = 1e21, sp = 1e24, oc = 1e27, no = 1e30 }
local function parseNum(s)
    s = tostring(s or ""):gsub("[,%s%$]", "")
    local num, suf = s:match("^([%d%.]+)(%a*)$")
    num = tonumber(num)
    if not num then return 0 end
    return num * (MULT[suf:lower()] or 1)
end
local function clock() return os.clock() end
local function now() return Workspace:GetServerTimeNow() end
local EB = ReplicatedStorage:WaitForChild("Packages"):WaitForChild("EventBus"):WaitForChild("RemoteEvent")
local function cmd(name, payload) pcall(function() EB:FireServer("ECS_COMMAND", name, payload or {}) end) end
local function ev(name, payload) pcall(function() EB:FireServer(name, payload) end) end
local WK
local function gcall(fn, ...)
    local co = coroutine.create(fn)
    local ok, a, b = coroutine.resume(co, ...)
    if ok then return a, b end
    return nil
end
local function wk()
    if WK then return WK end
    local m = ReplicatedStorage:FindFirstChild("WuKong")
    if not m then return nil end
    local ok, r = pcall(require, m)
    if ok and r then WK = r end
    return WK
end
local function query(path)
    return gcall(function()
        local w = wk(); if not w then return nil end
        local ok, v = pcall(w.ExecuteQuery, w, path)
        if ok then return v end
        return nil
    end)
end
local function action(path, ...)
    local args = table.pack(...)
    task.spawn(function()
        gcall(function()
            local w = wk(); if not w then return end
            pcall(w.ExecuteAction, w, path, table.unpack(args, 1, args.n))
        end)
    end)
end
local BUSY = {}
local function actionOnce(key, path, ...)
    local b = BUSY[key]
    if b and clock() - b < 10 then return end
    BUSY[key] = clock()
    local args = table.pack(...)
    local co = coroutine.create(function()
        local w = wk()
        if w then pcall(w.ExecuteAction, w, path, table.unpack(args, 1, args.n)) end
        BUSY[key] = nil
    end)
    if not coroutine.resume(co) then BUSY[key] = nil end
end
local function redeemCode(code)
    local p = ReplicatedStorage.Packages:FindFirstChild("CodeService")
    local rf = p and p:FindFirstChild("RemoteFunction")
    if not rf then return false end
    local ok, a, b = pcall(function() return rf:InvokeServer("Redeem", string.lower(code)) end)
    return ok and a == true, b
end
local CFG = {}
gcall(function()
    local g = ReplicatedStorage:FindFirstChild("_genConfigs")
    local function req(n) local m = g and g:FindFirstChild(n); if not m then return nil end; local ok, r = pcall(require, m); return ok and r or nil end
    CFG.unit = req("battle_tbunit") or {}
    CFG.tag = req("battle_tbtag") or {}
    CFG.attr = req("battle_tbattribute") or {}
    CFG.nest = req("battle_tbnestunlock") or {}
    CFG.pool = req("battle_tbpoollevelupgrade") or {}
    CFG.items = req("ui_tbbackpackitem") or {}
    CFG.petEggs = req("event_peteggshop") or {}
    CFG.index = req("ui_tbindexreward") or {}
    CFG.ride = req("battle_tbrideprogressreward") or {}
    local bc = ReplicatedStorage:FindFirstChild("Battle")
    bc = bc and bc:FindFirstChild("Game"); bc = bc and bc:FindFirstChild("Config"); bc = bc and bc:FindFirstChild("DungeonConfig")
    if bc then local ok, r = pcall(require, bc); if ok then CFG.dungeon = r end end
    local pc = ReplicatedStorage:FindFirstChild("Configs"); pc = pc and pc:FindFirstChild("PotionConfig")
    if pc then local ok, r = pcall(require, pc); if ok then CFG.potion = r end end
end)
CFG.unit = CFG.unit or {}; CFG.tag = CFG.tag or {}; CFG.attr = CFG.attr or {}; CFG.nest = CFG.nest or {}
CFG.pool = CFG.pool or {}; CFG.items = CFG.items or {}; CFG.petEggs = CFG.petEggs or {}; CFG.index = CFG.index or {}; CFG.ride = CFG.ride or {}
local RARITY_ORDER = { "Common", "Uncommon", "Rare", "Epic", "Legendary", "Mythic", "Exotic", "Secret", "Divine", "OP", "Celestial" }
local LISTS = { rarities = {}, ants = {}, tags = {}, tagMul = {}, tagById = {}, jellies = {}, potions = {}, gear = {}, gearByName = {}, eggs = {} }
do
    local seen, extra = {}, {}
    for _, r in ipairs(RARITY_ORDER) do seen[r] = false end
    local antRows = {}
    for id, u in pairs(CFG.unit) do
        if type(u) == "table" and u.Rarity and (u._type_ == "AntCfg" or u.Type == "Normal") then
            if seen[u.Rarity] == nil then seen[u.Rarity] = false; extra[#extra + 1] = u.Rarity end
            seen[u.Rarity] = true
            antRows[#antRows + 1] = { name = u.DisplayName or id, rank = table.find(RARITY_ORDER, u.Rarity) or 99, atk = tonumber(u.Attack) or 0 }
        end
    end
    for _, r in ipairs(RARITY_ORDER) do if seen[r] then LISTS.rarities[#LISTS.rarities + 1] = r end end
    for _, r in ipairs(extra) do LISTS.rarities[#LISTS.rarities + 1] = r end
    if #LISTS.rarities == 0 then LISTS.rarities = table.clone(RARITY_ORDER) end
    table.sort(antRows, function(a, b) if a.rank ~= b.rank then return a.rank > b.rank end return a.atk > b.atk end)
    local dup = {}
    for _, a in ipairs(antRows) do if not dup[a.name] then dup[a.name] = true; LISTS.ants[#LISTS.ants + 1] = a.name end end
    for i = 0, 30 do
        local t = CFG.tag[i]
        if type(t) == "table" and t.DisplayName then
            LISTS.tagById[i] = t.DisplayName
            LISTS.tagMul[t.DisplayName] = tonumber(t.Mul) or 1
            if i > 0 then LISTS.tags[#LISTS.tags + 1] = t.DisplayName end
        end
    end
    if #LISTS.tags == 0 then LISTS.tags = { "Leaf", "Bubblegum", "Candy", "Rainbow", "Petal", "Starlight" } end
    local rows = {}
    for id, it in pairs(CFG.items) do
        if type(it) == "table" and it.DisplayName and (tonumber(it.CoinPrice) or 0) > 0 then
            rows[#rows + 1] = { id = id, name = it.DisplayName, price = tonumber(it.CoinPrice), tag = it.Tag, sort = tonumber(it.sort) or tonumber(it.Index) or 99, dur = tonumber(it.Duration) or 0 }
        end
    end
    table.sort(rows, function(a, b) return a.sort < b.sort end)
    for _, r in ipairs(rows) do
        LISTS.gear[#LISTS.gear + 1] = r.name
        LISTS.gearByName[r.name] = r
        if r.tag == "Jelly" then LISTS.jellies[#LISTS.jellies + 1] = r.name end
        if r.tag == "Potion" and not r.name:find("Removal") then
            local mut = r.name:match("^(%a+) Mutation")
            r.mut = mut
            LISTS.potions[#LISTS.potions + 1] = r.name
        end
    end
    local er = {}
    for id, e in pairs(CFG.petEggs) do if type(e) == "table" then er[#er + 1] = { id = e.PetEggid or id, price = tonumber(e.Price) or 0 } end end
    table.sort(er, function(a, b) return a.price < b.price end)
    LISTS.eggRows = er
    for _, e in ipairs(er) do LISTS.eggs[#LISTS.eggs + 1] = e.id end
end
local ATTRS = {
    { key = "单抽数量", name = L["Rolls Per Pull"] },
    { key = "幸运值", name = L["Egg Luck"] },
    { key = "蚂蚁攻击力", name = L["Food Value"] },
    { key = "蚂蚁移速", name = "Ant Speed" },
    { key = "巢穴层数", name = L["Colony Expansion"] },
    { key = "蚁后等级", name = L["Queen Level"] },
}
local ATTR_BY_NAME = {}
for _, a in ipairs(ATTRS) do ATTR_BY_NAME[a.name] = a end
local STAFF = { [3703873374] = true, [4447945316] = true, [4442552551] = true, [8092713214] = true, [10719382632] = true, [2794649209] = true, [4619859828] = true }
local D = { gold = 0, food = 0, pet = 0, act = 0, star = 0, room = 1, slots = 1 }
local S = {
    stats = { rolled = 0, bought = 0, spent = 0, sold = 0, earned = 0, kills = 0, petTok = 0, coins = 0, gear = 0, started = clock() },
    price = nil, priceAt = 0, bm = nil, gearStock = {}, gearAt = 0,
    dg = nil, dgAt = 0, roll = { sentAt = 0, gotAt = 0, wait = false },
    msg = "", tpBusy = false, slotMax = false, attrMax = {},
}
local function refreshData()
    D.room = tonumber(lp:GetAttribute("RoomIndex")) or D.room
    D.slots = tonumber(lp:GetAttribute("MaxAntSlots")) or D.slots
    local g = tonumber(query("/货币/金币?属性数量")); if g and clock() > (S.spendLock or 0) then D.gold = g end
    local f = tonumber(query("/货币/食物?属性数量")); if f then D.food = f end
    local p = tonumber(query("/货币/宠物代币?属性数量")); if p then D.pet = p end
    local a = tonumber(query("/货币/活动代币?属性数量")); if a then D.act = a end
end
local function reserve() return parseNum(val("g_reserve", "0")) end
local function spendable() return D.gold - reserve() end
local function spendFree() return spendable() - (S.shopNeed or 0) end
local function spend(n) D.gold = D.gold - (tonumber(n) or 0); S.spendLock = clock() + 1.5 end
local function foodKeep() return parseNum(val("s_keep", "0")) end
local function hrp() local c = lp.Character; return c and c:FindFirstChild("HumanoidRootPart") end
local function myRoom() local r = Workspace:FindFirstChild("Rooms"); return r and r:FindFirstChild(tostring(D.room)) end
local function tp(pos)
    local r = hrp(); if not r then return false end
    r.CFrame = CFrame.new(pos + Vector3.new(0, 3, 0))
    r.AssemblyLinearVelocity = Vector3.zero
    return true
end
local function partPos(x)
    if not x then return nil end
    if x:IsA("Attachment") then return x.WorldPosition end
    if x:IsA("BasePart") then return x.Position end
    if x:IsA("Model") then local ok, cf = pcall(x.GetPivot, x); return ok and cf.Position or nil end
    return nil
end
local function firePrompt(p, hold)
    if not p then return end
    if hold then
        if fireproximityprompt then pcall(fireproximityprompt, p) end
        task.wait(0.3)
        pcall(function() p:InputHoldBegin() end)
        task.wait((tonumber(p.HoldDuration) or 1) + 0.15)
        pcall(function() p:InputHoldEnd() end)
        return
    end
    pcall(function() p.HoldDuration = 0 end)
    if fireproximityprompt then pcall(fireproximityprompt, p) end
end
local function myAnts()
    local list = {}
    local f = Workspace:FindFirstChild("Client_Assets"); f = f and f:FindFirstChild("Unit")
    if not f then return list end
    local seen = {}
    for _, m in ipairs(f:GetChildren()) do
        if tonumber(m:GetAttribute("RoomIndex")) == D.room and m:GetAttribute("AntIndex") then list[#list + 1] = m end
    end
    table.sort(list, function(a, b) return (tonumber(a:GetAttribute("Attack")) or 0) > (tonumber(b:GetAttribute("Attack")) or 0) end)
    local out = {}
    for _, m in ipairs(list) do
        local i = m:GetAttribute("AntIndex")
        if not seen[i] then seen[i] = true; out[#out + 1] = m end
    end
    return out
end
local function activity() return Workspace:GetAttribute("CurrentActivityId"), tonumber(Workspace:GetAttribute("CurrentActivityCountdownSeconds")) or 0 end
local LIVE = { ready = true, fighting = true, intermission = true, dropping = true }
local function inDungeon()
    local d = S.dg
    return (d and d.sessionId and LIVE[d.status] and (clock() - S.dgAt) < 120) and true or false
end
local function withTp(fn)
    if S.tpBusy or inDungeon() then return false end
    local r = hrp(); if not r then return false end
    S.tpBusy = true
    local home = r.CFrame
    local ok = pcall(fn)
    local r2 = hrp()
    if r2 and on("p_return") ~= false then r2.CFrame = home; r2.AssemblyLinearVelocity = Vector3.zero end
    S.tpBusy = false
    return ok
end
local HANDLERS = {}
track(EB.OnClientEvent:Connect(function(name, data)
    local h = HANDLERS[name]
    if h then pcall(h, data) end
end))
local function onEvent(name, fn) HANDLERS[name] = fn end
local function reasonText(r)
    local map = { NotEnoughGold = "Not enough cash", NotEnoughFood = "Not enough food", MaxLevel = "Max level", MaxReached = "Maxed out", QueenLevelRequired = "Needs higher queen", LuckLevelRequired = "Needs more luck", RobuxPurchasePending = "Close the purchase window",
        AddBackpackFailed = "Backpack full", Expired = "Roll expired", Busy = "Busy", NoFood = "No food yet", CostFailed = "Purchase failed" }
    return map[r] or tostring(r or "")
end
local function gameMsg(t) S.msg = t end
local function wantResult(r)
    if type(r) ~= "table" then return false end
    if r.ResultType == "Item" or (tonumber(r.Cost) or 0) <= 0 then return on("f_items") ~= false end
    local name = r.UnitId and CFG.unit[r.UnitId] and CFG.unit[r.UnitId].DisplayName
    local tag = LISTS.tagById[tonumber(r.TagId) or 0] or r.Tag
    if r.Source == "Vine" and on("e_vine") and on("e_vinebuy") then return true end
    local rar, names, muts = msel("f_rar"), msel("f_names"), msel("f_mut")
    if rar and r.Rarity and rar[r.Rarity] then return true end
    if names and name and names[name] then return true end
    if muts and tag and tag ~= "None" and muts[tag] then return true end
    if on("f_new") and r.FirstObtain then return true end
    return false
end
onEvent("RollAntResult", function(data)
    S.roll.gotAt = clock(); S.roll.wait = false
    local res = type(data) == "table" and data.Results or {}
    S.stats.rolled = S.stats.rolled + #res
    local vine = type(data) == "table" and data.Source == "Vine" and on("e_vine") and on("e_vinebuy")
    if not (on("f_buy") or vine) then return end
    local budget = spendable()
    for _, r in ipairs(res) do
        if r.ClaimId and wantResult(r) then
            local cost = tonumber(r.Cost) or 0
            if cost <= 0 or cost <= budget then
                budget = budget - cost
                spend(cost)
                cmd("ClaimRolledAnt", { ClaimId = r.ClaimId })
                S.roll.claimAt = clock()
            end
        end
    end
end)
onEvent("ClaimRolledAntResult", function(d)
    if type(d) ~= "table" then return end
    if d.Success then
        S.stats.bought = S.stats.bought + 1
        S.stats.spent = S.stats.spent + (tonumber(d.Cost) or 0)
    elseif d.Reason then gameMsg(reasonText(d.Reason)) end
end)
onEvent("SellFoodPriceUpdate", function(d) if type(d) == "table" and d.GoldPerFood then S.price = d; S.priceAt = clock() end end)
onEvent("SellResuit", function(d)
    if type(d) ~= "table" then return end
    local r = d.Result or {}
    if d.Success then
        S.stats.sold = S.stats.sold + (tonumber(r.FoodAmount) or 0)
        S.stats.earned = S.stats.earned + (tonumber(r.GoldAmount) or 0)
    elseif r.Reason and r.Reason ~= "NotEnoughFood" and r.Reason ~= "InvalidAmount" then gameMsg(reasonText(r.Reason)) end
end)
onEvent("BlackMarketState", function(d) if type(d) == "table" then S.bm = d end end)
local function pricePct()
    local p = S.price; if not p then return nil end
    local g, mn, mx = tonumber(p.GoldPerFood), tonumber(p.MinGoldPerFood), tonumber(p.MaxGoldPerFood)
    if not (g and mn and mx) then return nil end
    if mx <= mn then return 100 end
    return math.clamp((g - mn) / (mx - mn) * 100, 0, 100)
end
local function bmOpen()
    local b = S.bm
    if not (b and b.Active) then return false end
    local t = now()
    return t >= (tonumber(b.SellOpensAt) or 0) and t < (tonumber(b.EndsAt) or 0) - 2
end
local function bmSellPart()
    local a = ReplicatedStorage:FindFirstChild("Assets"); a = a and a:FindFirstChild("Event"); a = a and a:FindFirstChild("BlackMarket")
    local s = a and a:FindFirstChild("Sell")
    return s and s:IsA("BasePart") and s or nil
end
S.attrBlock = {}
onEvent("UpgradePlayerAttributeResult", function(d)
    if type(d) ~= "table" or d.Success then return end
    local r = type(d.Result) == "table" and d.Result or d
    local key = r.AttributeName
    if key and (r.Reason == "MaxReached" or r.Reason == "MaxLevel") then S.attrMax[key] = true end
    if key and (r.Reason == "QueenLevelRequired" or r.Reason == "LuckLevelRequired" or r.Reason == "NotEnoughGold") then S.attrBlock[key] = clock() + 20 end
    if r.Reason then gameMsg(reasonText(r.Reason)) end
end)
onEvent("AddAntSlotResult", function(d)
    if type(d) ~= "table" then return end
    local r = type(d.Result) == "table" and d.Result or d
    if r.PromptRobuxPurchase then gameMsg(reasonText("RobuxPurchasePending")) end
    if not d.Success and (r.Reason == "MaxReached" or r.Reason == "AlreadyUnlocked") then S.slotMax = tonumber(lp:GetAttribute("NestLayer")) or 0 end
end)
local LQP = gcall(function() local h = ReplicatedStorage:FindFirstChild("Helper"); h = h and h:FindFirstChild("LuckQueenProgression"); if not h then return nil end; local ok, r = pcall(require, h); return ok and r or nil end)
local function attrLv(k) return math.max(math.floor(tonumber(query("/属性/" .. k .. "?属性数量")) or 1), 1) end
local function attrBlocked(k)
    if (S.attrBlock[k] or 0) > clock() then return true end
    if not LQP or (k ~= "幸运值" and k ~= "蚁后等级") then return false end
    local st = gcall(function() local ok, r = pcall(LQP.GetState, attrLv("幸运值"), attrLv("蚁后等级")); return ok and r or nil end)
    if type(st) ~= "table" or st.IsQueenUpgradeRequired == nil then return false end
    if k == "幸运值" then return st.IsQueenUpgradeRequired == true end
    return st.IsQueenUpgradeRequired ~= true
end
local function attrLevelPrice(key)
    local c = CFG.attr[key]; if type(c) ~= "table" or type(c.Info) ~= "table" then return nil end
    local lvl = attrLv(key)
    local cur, nxt
    for _, v in ipairs(c.Info) do
        local L = math.floor(tonumber(v.Level) or 0)
        if L == lvl then cur = v elseif L == lvl + 1 then nxt = v end
    end
    if not nxt then return lvl, nil end
    return lvl, tonumber(cur and cur.Price) or 0
end
local DG = { started = {}, placed = {}, picked = {}, pend = {}, lastEnter = 0, lastKills = 0, sid = nil }
onEvent("DungeonState", function(d)
    if type(d) ~= "table" then return end
    if d.sessionId ~= DG.sid then
        DG.sid = d.sessionId; DG.lastKills = 0
        DG.started, DG.placed, DG.picked, DG.pend = {}, {}, {}, {}
    end
    if DG.pend and d.sessionId then
        local live = {}
        for _, c in ipairs(type(d.timeCoins) == "table" and d.timeCoins or {}) do live[tostring(d.sessionId) .. ":" .. tostring(c.id)] = true end
        for key in pairs(DG.pend) do if not live[key] then DG.pend[key] = nil; S.stats.coins = S.stats.coins + 1 end end
    end
    local k = tonumber(d.kills) or 0
    if k > DG.lastKills then S.stats.kills = S.stats.kills + (k - DG.lastKills); DG.lastKills = k end
    S.dg = d; S.dgAt = clock()
end)
local function dgBase(d)
    local c = CFG.dungeon or {}
    local base = c.BossPosition or Vector3.new(439.663, -373.137, 1911.807)
    local land = (c.TimeCoin and c.TimeCoin.LandingHeight) or -370
    if d and d.dungeonType and d.dungeonType ~= "Pet" and c.StarEvent and c.StarEvent.PositionOffset then
        base = base + c.StarEvent.PositionOffset
        land = land + c.StarEvent.PositionOffset.Y
    end
    return base, land
end
local function freshEntrance()
    local f = Workspace:FindFirstChild("DungeonEntrances"); if not f then return nil end
    local t, best = now(), nil
    for _, m in ipairs(f:GetChildren()) do
        if not m:GetAttribute("DungeonUsed_" .. lp.UserId) and (tonumber(m:GetAttribute("ExpiresAt")) or math.huge) > t + 5 then
            local pr = m:FindFirstChild("promt", true)
            local pp = pr and (pr:IsA("ProximityPrompt") and pr or pr:FindFirstChildWhichIsA("ProximityPrompt", true))
            if pp then best = { model = m, prompt = pp, pos = partPos(pp.Parent) or partPos(m) }; break end
        end
    end
    return best
end
local function hopServer()
    local loader = (CONFIG.LOADER ~= "" and CONFIG.LOADER) or 'if isfile and isfile("ant_empire_hub.lua") then loadstring(readfile("ant_empire_hub.lua"))() end'
    local q = queue_on_teleport or (syn and syn.queue_on_teleport)
    if q then pcall(q, loader) end
    local ok, body = pcall(function() return game:HttpGet("https://games.roblox.com/v1/games/" .. game.PlaceId .. "/servers/Public?sortOrder=Desc&limit=100") end)
    if ok then
        local dok, data = pcall(function() return HttpService:JSONDecode(body) end)
        if dok and data and data.data then
            local list = {}
            for _, s in ipairs(data.data) do
                if s.id ~= game.JobId and (s.playing or 0) < (s.maxPlayers or 0) then list[#list + 1] = s.id end
            end
            if #list > 0 then
                pcall(function() TeleportService:TeleportToPlaceInstance(game.PlaceId, list[math.random(1, #list)], lp) end)
                return
            end
        end
    end
    pcall(function() TeleportService:Teleport(game.PlaceId, lp) end)
end
do
    local hm = hookmetamethod
    local gnm = getnamecallmethod
    if hm and gnm then
        local old
        local ok = pcall(function()
            old = hm(game, "__namecall", (newcclosure or function(f) return f end)(function(self, ...)
                if RUNNING then
                    local m = gnm()
                    if m == "Kick" and self == lp and on("g_antikick") and not (checkcaller and checkcaller()) then return nil end
                    if m == "FireServer" and self == EB and on("g_antiidle") then
                        local a = ...
                        if a == "AfkReconnectRequest" then return nil end
                    end
                end
                return old(self, ...)
            end))
        end)
        if not ok then old = nil end
    end
end
local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
if _G.__antLib then pcall(function() _G.__antLib:Unload() end) end
local function fetch(u) for _ = 1, 6 do local ok, s = pcall(function() return game:HttpGet(u) end); if ok and type(s) == "string" and #s > 100 then return s end; task.wait(2) end; return game:HttpGet(u) end
local Library = loadstring(fetch(repo .. "Library.lua"))()
local SaveManager = loadstring(fetch(repo .. "addons/SaveManager.lua"))()
local ThemeManager = loadstring(fetch(repo .. "addons/ThemeManager.lua"))()
_G.__antLib = Library
getgenv().Library = Library
Library.ShowCustomCursor = false
onClean(function() pcall(function() Library:Unload() end) end)
local Window = Library:CreateWindow({ Title = "COMBO_WICK", Footer = "Build An Ant Empire · v1.0", NotifySide = "Right", ShowCustomCursor = false, AutoShow = true, Size = UDim2.fromOffset(600, 460) })
Opt, Toggles = Library.Options, Library.Toggles
notify = function(text) pcall(function() Library:Notify({ Title = "COMBO_WICK", Description = text, Time = 3 }) end) end
local function section(name, fn)
    local ok, err = xpcall(fn, debug.traceback)
    if not ok then notify(name .. L[" tab failed to load"]); pcall(setclipboard, tostring(err)) end
end
local UI = {}
section(L["Feedback"], function()
    local Tab = Window:AddTab(L["Feedback"], "message-square")
    local FEEDBACK_URL = "https://v0-secure-discord-proxy.vercel.app/api/v2sender"
    local _request = request or (syn and syn.request) or http_request
    local okId, cid = pcall(function() return game:GetService("RbxAnalyticsService"):GetClientId() end)
    local HWID = (okId and type(cid) == "string" and cid ~= "") and cid or tostring(lp.UserId)
    local ERR = {
        empty = "The message is empty.", no_links = "Links are not allowed.", too_long = "Too long (500 max).",
        rate_limited = "You reached the limit. Try again later.", network = "Network error.",
        no_request = "Your executor cannot send requests.", bad_response = "Unexpected server response.",
        unreachable = "Your executor cannot reach the server.",
    }
    local function send(ftype, msg)
        if not _request then return false, "no_request" end
        local ok, res = pcall(function()
            return _request({ Url = FEEDBACK_URL, Method = "POST", Headers = { ["Content-Type"] = "application/json" },
                Body = HttpService:JSONEncode({ type = ftype, message = msg, hwid = HWID, placeId = tostring(game.PlaceId), username = lp.Name, version = CONFIG.VERSION }) })
        end)
        if not ok or type(res) ~= "table" then return false, (type(res) == "string") and "unreachable" or "network" end
        local code = res.StatusCode or res.status_code or res.Status or res.status
        if type(code) == "number" and code ~= 200 and code ~= 201 and code ~= 204 then return false, "http_" .. code end
        local dok, data = pcall(function() return HttpService:JSONDecode(res.Body or res.body or "") end)
        if not dok or type(data) ~= "table" then return false, "bad_response" end
        if data.success == true then return true end
        return false, tostring(data.error or "unknown")
    end
    local FG = Tab:AddLeftGroupbox(L["Suggestions / Help"], "message-square")
    FG:AddDropdown("FeedbackType", { Text = L["Type"], Values = { "Suggestion", "Bug", "Help" }, Default = "Suggestion" })
    FG:AddInput("FeedbackMsg", { Default = "", Numeric = false, Finished = false, ClearTextOnFocus = false, Text = L["Message"], Placeholder = L["500 chars max, no links"] })
    local status = FG:AddLabel("", true)
    local last = 0
    FG:AddButton({ Text = L["Send"], Func = function()
        if tick() - last < 20 then setText(status, string.format(L["Wait %ds"], math.ceil(20 - (tick() - last)))); return end
        local msg = tostring(val("FeedbackMsg", "")):gsub("^%s*(.-)%s*$", "%1")
        if msg == "" then setText(status, ERR.empty); return end
        if #msg > 500 then setText(status, ERR.too_long); return end
        local low = msg:lower()
        if low:find("http", 1, true) or low:find("discord.gg", 1, true) or low:find("www.", 1, true) or low:find(".gg/", 1, true) then setText(status, ERR.no_links); return end
        setText(status, L["Sending..."])
        task.spawn(function()
            local ok, err = send(tostring(val("FeedbackType", "Suggestion")):lower(), msg)
            if ok then last = tick(); setText(status, L["Sent. Thank you!"]); pcall(function() Opt.FeedbackMsg:SetValue("") end)
            else setText(status, ERR[err] or (L["Failed: "] .. tostring(err))) end
        end)
    end })
    FG:AddLabel(L["Max 3 messages per hour."], true)
    local HG = Tab:AddRightGroupbox(L["Quick Start"], "life-buoy")
    HG:AddLabel(L["Farm: Auto Roll, Auto Buy, Fast Harvest, Auto Sell."], true)
    HG:AddLabel(L["Upgrades: pick what to level, set Keep Cash."], true)
    HG:AddLabel(L["Dungeon: Auto Dungeon + Auto Hatch for pets."], true)
    HG:AddLabel(L["Settings: Hide Effects for less lag."], true)
    if CONFIG.DISCORD_INVITE ~= "" then
        HG:AddButton({ Text = L["Copy Discord Invite"], Func = function() pcall(setclipboard, CONFIG.DISCORD_INVITE); notify(L["Discord link copied"]) end })
    end
end)
section(L["Farm"], function()
    local Tab = Window:AddTab(L["Farm"], "egg")
    local RB = Tab:AddLeftGroupbox(L["Roll & Buy"], "egg")
    RB:AddToggle("f_roll", { Text = L["Auto Roll"], Default = false, Tooltip = L["Rolls from anywhere at max speed"] })
    RB:AddToggle("f_buy", { Text = L["Auto Buy"], Default = false, Tooltip = L["Buys rolls that match your filters"] })
    local bd = RB:AddDependencyBox()
    bd:AddDropdown("f_rar", { Text = L["Rarities"], Values = LISTS.rarities, Default = {}, Multi = true, AllowNull = true })
    bd:AddDropdown("f_names", { Text = L["Specific Ants"], Values = LISTS.ants, Default = {}, Multi = true, AllowNull = true, Searchable = true })
    bd:AddDropdown("f_mut", { Text = L["Mutations"], Values = LISTS.tags, Default = {}, Multi = true, AllowNull = true })
    bd:AddToggle("f_new", { Text = L["New For Index"], Default = true, Tooltip = L["Buys ants you never owned"] })
    bd:AddToggle("f_items", { Text = L["Claim Free Items"], Default = true })
    bd:SetupDependencies({ { Toggles.f_buy, true } })
    UI.roll = RB:AddLabel(L["Idle"], true)
    local CB = Tab:AddLeftGroupbox(L["Colony"], "paw-print")
    CB:AddToggle("f_harvest", { Text = L["Fast Harvest"], Default = false, Tooltip = L["Collects food from every ant as fast as allowed"] })
    CB:AddToggle("f_equip", { Text = L["Auto Equip Best"], Default = false })
    CB:AddToggle("f_slot", { Text = L["Auto Unlock Ant Slots"], Default = false, Tooltip = L["Only buys with cash"] })
    CB:AddToggle("f_upant", { Text = L["Auto Level Up Ants"], Default = false })
    local SB = Tab:AddRightGroupbox(L["Smart Sell"], "dollar-sign")
    SB:AddToggle("s_sell", { Text = L["Auto Sell"], Default = false, Tooltip = L["Sells from anywhere when the price is good"] })
    local sd = SB:AddDependencyBox()
    sd:AddSlider("s_pct", { Text = L["Min Price"], Default = 85, Min = 0, Max = 100, Rounding = 0, Suffix = L["% of max"] })
    sd:AddToggle("s_bm", { Text = L["Prefer Black Market"], Default = true, Tooltip = L["Sells at the Black Market when it shows up"] })
    sd:SetupDependencies({ { Toggles.s_sell, true } })
    SB:AddInput("s_keep", { Text = L["Keep Food"], Default = "0", Numeric = false, Finished = true, Placeholder = L["e.g. 0, 5K"] })
    UI.price = SB:AddLabel(L["Price: waiting"], true)
    SB:AddButton({ Text = L["Sell All Now"], Func = function()
        refreshData()
        local n = math.floor(D.food - foodKeep())
        if n > 0 then cmd("SellPlayerFood", { FoodAmount = n, Source = "SellShopModel" }); notify(L["Sold "] .. fmt(n) .. L[" food"]) else notify(L["No food to sell"]) end
    end })
    local MB = Tab:AddRightGroupbox(L["Money"], "coins")
    MB:AddInput("g_reserve", { Text = L["Keep Cash"], Default = "0", Numeric = false, Finished = true, Placeholder = L["e.g. 0, 1M, 2.5B"] })
    MB:AddLabel(L["Buying never goes below this."], true)
    UI.money = MB:AddLabel(L["Cash: -"], true)
end)
section(L["Upgrades"], function()
    local Tab = Window:AddTab(L["Upgrades"], "arrow-up")
    local names = {}
    for _, a in ipairs(ATTRS) do names[#names + 1] = a.name end
    local AB = Tab:AddLeftGroupbox(L["Auto Upgrade"], "arrow-up")
    AB:AddToggle("u_auto", { Text = L["Auto Upgrade"], Default = false })
    local ud = AB:AddDependencyBox()
    ud:AddDropdown("u_list", { Text = L["Upgrades"], Values = names, Default = { L["Rolls Per Pull"], L["Egg Luck"], L["Queen Level"], L["Food Value"], L["Colony Expansion"] }, Multi = true, AllowNull = true })
    ud:AddToggle("u_cheap", { Text = L["Cheapest First"], Default = true })
    ud:SetupDependencies({ { Toggles.u_auto, true } })
    UI.up = AB:AddLabel(L["Idle"], true)
    local QB = Tab:AddRightGroupbox(L["Queen"], "trending-up")
    QB:AddToggle("u_queen", { Text = L["Use Highest Queen"], Default = false, Tooltip = L["Rolls from your best queen"] })
    local KB = Tab:AddRightGroupbox(L["Compost"], "refresh-cw")
    KB:AddToggle("u_lever", { Text = L["Auto Pull Lever"], Default = false })
    KB:AddToggle("u_compup", { Text = L["Auto Upgrade Machine"], Default = false })
end)
section("Dungeon", function()
    local Tab = Window:AddTab("Dungeon", "swords")
    local DB = Tab:AddLeftGroupbox(L["Auto Dungeon"], "swords")
    DB:AddToggle("d_auto", { Text = L["Auto Dungeon"], Default = false, Tooltip = L["Finds, enters and starts dungeons"] })
    DB:AddToggle("d_click", { Text = L["Max Attack Speed"], Default = true, Tooltip = L["Keeps the 4x boost up"] })
    DB:AddToggle("d_coins", { Text = L["Collect Time Coins"], Default = true, Tooltip = L["+15s per coin"] })
    DB:AddToggle("d_hop", { Text = L["Hop When None Left"], Default = false })
    local hd = DB:AddDependencyBox()
    hd:AddSlider("d_hopwait", { Text = L["Wait Before Hop"], Default = 60, Min = 10, Max = 600, Rounding = 0, Suffix = "s" })
    hd:SetupDependencies({ { Toggles.d_hop, true } })
    UI.dg = DB:AddLabel(L["Idle"], true)
    local PB = Tab:AddRightGroupbox(L["Pets"], "paw-print")
    PB:AddToggle("d_buyegg", { Text = L["Auto Buy Pet Egg"], Default = false })
    local ed = PB:AddDependencyBox()
    ed:AddDropdown("d_egg", { Text = L["Egg"], Values = LISTS.eggs, Default = LISTS.eggs[1] })
    ed:SetupDependencies({ { Toggles.d_buyegg, true } })
    PB:AddToggle("d_hatch", { Text = L["Auto Hatch Eggs"], Default = false, Tooltip = L["Places and hatches your pet eggs"] })
    PB:AddToggle("d_stroke", { Text = L["Auto Pet Your Pets"], Default = false })
    UI.pet = PB:AddLabel(L["Pet Coins: -"], true)
end)
section(L["Events"], function()
    local Tab = Window:AddTab(L["Events"], "zap")
    local EB2 = Tab:AddLeftGroupbox(L["Live Events"], "zap")
    UI.ev = EB2:AddLabel(L["Event: -"], true)
    EB2:AddToggle("e_straw", { Text = L["Collect Strawberry Coins"], Default = false })
    EB2:AddToggle("e_spin", { Text = L["Auto Spin Strawberry Wheel"], Default = false })
    EB2:AddToggle("e_snail", { Text = L["Auto Travelling Snail"], Default = false })
    EB2:AddToggle("e_vine", { Text = L["Auto Vine Rolls"], Default = false, Tooltip = L["Rolls for Leaf ants during Vine"] })
    local vd = EB2:AddDependencyBox()
    vd:AddToggle("e_vinebuy", { Text = L["Buy Every Vine Roll"], Default = true })
    vd:SetupDependencies({ { Toggles.e_vine, true } })
    local NB = Tab:AddRightGroupbox(L["Trips"], "map-pin")
    NB:AddToggle("p_return", { Text = L["Return After Trips"], Default = true, Tooltip = L["Goes back to where you were"] })
end)
section(L["Shop"], function()
    local Tab = Window:AddTab(L["Shop"], "dollar-sign")
    local GB = Tab:AddLeftGroupbox(L["Gear Shop"], "dollar-sign")
    GB:AddToggle("g_buy", { Text = L["Auto Buy Gear"], Default = false, Tooltip = L["Buys selected items every restock"] })
    local gd = GB:AddDependencyBox()
    gd:AddDropdown("g_items", { Text = L["Items"], Values = LISTS.gear, Default = {}, Multi = true, AllowNull = true })
    gd:SetupDependencies({ { Toggles.g_buy, true } })
    UI.gear = GB:AddLabel(L["Restock: -"], true)
    local UB = Tab:AddRightGroupbox(L["Use Items"], "zap")
    UB:AddToggle("g_jelly", { Text = L["Auto Feed Speed Jelly"], Default = false })
    local jd = UB:AddDependencyBox()
    jd:AddDropdown("g_jellyid", { Text = "Jelly", Values = LISTS.jellies, Default = LISTS.jellies[#LISTS.jellies] })
    jd:SetupDependencies({ { Toggles.g_jelly, true } })
    UB:AddToggle("g_mut", { Text = L["Auto Apply Mutations"], Default = false, Tooltip = L["Only upgrades, never downgrades"] })
    local md = UB:AddDependencyBox()
    md:AddDropdown("g_mutids", { Text = L["Potions"], Values = LISTS.potions, Default = {}, Multi = true, AllowNull = true })
    md:SetupDependencies({ { Toggles.g_mut, true } })
end)
section(L["Rewards"], function()
    local Tab = Window:AddTab(L["Rewards"], "gift")
    local RB = Tab:AddLeftGroupbox(L["Auto Claim"], "gift")
    RB:AddToggle("r_all", { Text = L["Auto Claim Rewards"], Default = false, Tooltip = L["Online, daily, 7-day, index, ride, group"] })
    UI.rew = RB:AddLabel(L["Idle"], true)
    local CB = Tab:AddRightGroupbox(L["Codes"], "ticket")
    CB:AddInput("r_codes", { Text = L["Codes"], Default = "Wnus13, 9hcb2s", Numeric = false, Finished = true, Placeholder = L["comma separated"] })
    CB:AddButton({ Text = L["Redeem Codes"], Func = function()
        task.spawn(function()
            local n = 0
            for c in tostring(val("r_codes", "")):gmatch("[^,%s]+") do
                local ok = redeemCode(c)
                if ok then n = n + 1 end
                task.wait(10.5)
            end
            notify(n > 0 and (L["Redeemed "] .. n .. L[" code(s)"]) or L["No new codes"])
        end)
    end })
end)
section(L["Player"], function()
    local Tab = Window:AddTab(L["Player"], "user")
    local MB = Tab:AddLeftGroupbox(L["Movement"], "wind")
    MB:AddToggle("p_speed", { Text = L["Walk Speed"], Default = false })
    local sd = MB:AddDependencyBox()
    sd:AddSlider("p_speedv", { Text = L["Speed"], Default = 40, Min = 16, Max = 150, Rounding = 0 })
    sd:SetupDependencies({ { Toggles.p_speed, true } })
    MB:AddToggle("p_jump", { Text = L["Infinite Jump"], Default = false })
    MB:AddToggle("p_noclip", { Text = L["Noclip"], Default = false })
    MB:AddToggle("p_fly", { Text = L["Fly"], Default = false })
    local fd = MB:AddDependencyBox()
    fd:AddSlider("p_flyv", { Text = L["Fly Speed"], Default = 60, Min = 10, Max = 200, Rounding = 0 })
    fd:SetupDependencies({ { Toggles.p_fly, true } })
    MB:AddToggle("p_prompt", { Text = L["Instant Prompts"], Default = false })
    local TB = Tab:AddRightGroupbox(L["Teleport"], "map-pin")
    local function go(getter, label)
        return function()
            local p = getter()
            if p then tp(p) else notify(label .. L[" not found"]) end
        end
    end
    TB:AddButton({ Text = L["My Colony"], Func = go(function() local r = myRoom(); return r and partPos(r:FindFirstChild("BaseGround") or r:FindFirstChild("FoodSpawnPart")) end, L["Colony"]) })
    TB:AddButton({ Text = L["Sell Spot"], Func = go(function() local r = myRoom(); local f = r and r:FindFirstChild("PlayerFood"); return f and partPos(f:FindFirstChild("SellPrompt")) end, L["Sell spot"]) })
    TB:AddButton({ Text = L["Gear Shop"], Func = go(function() return partPos(Workspace:FindFirstChild("GearShop")) end, L["Gear Shop"]) })
    TB:AddButton({ Text = L["Pet Shop"], Func = go(function() return partPos(Workspace:FindFirstChild("PetShop")) end, L["Pet Shop"]) })
    TB:AddButton({ Text = L["Strawberry King"], Func = go(function() return partPos(Workspace:FindFirstChild("StrawberryKingPart")) end, L["Strawberry King"]) })
    TB:AddButton({ Text = L["Dungeon Portal"], Func = go(function() local e = freshEntrance(); return e and e.pos end, L["Open portal"]) })
end)
section(L["Settings"], function()
    local Tab = Window:AddTab(L["Settings"], "settings")
    local GB = Tab:AddLeftGroupbox(L["Safety"], "shield")
    GB:AddToggle("g_antiidle", { Text = L["Anti-Idle"], Default = true, Tooltip = L["Stay in this server while AFK"] })
    GB:AddToggle("g_antikick", { Text = L["Anti-Kick"], Default = true })
    GB:AddToggle("g_staff", { Text = L["Staff Alert"], Default = true })
    local std = GB:AddDependencyBox()
    std:AddDropdown("g_staffdo", { Text = L["When Staff Joins"], Values = { "Notify", "Hop Server", "Leave" }, Default = "Notify" })
    std:SetupDependencies({ { Toggles.g_staff, true } })
    local SB = Tab:AddLeftGroupbox(L["Server"], "server")
    SB:AddButton({ Text = L["Server Hop"], Func = function() hopServer() end })
    SB:AddButton({ Text = L["Rejoin"], Func = function() pcall(function() TeleportService:TeleportToPlaceInstance(game.PlaceId, game.JobId, lp) end) end })
    local PB = Tab:AddLeftGroupbox(L["Performance"], "gauge")
    PB:AddToggle("g_fx", { Text = L["Hide Effects"], Default = false, Tooltip = L["Removes particles, beams and glow"] })
    PB:AddToggle("g_popups", { Text = L["Hide Reward Popups"], Default = false })
    PB:AddToggle("g_others", { Text = L["Hide Other Players' Ants"], Default = false, Tooltip = L["Less lag in full servers"] })
    PB:AddToggle("g_lowgfx", { Text = L["Low Graphics"], Default = false })
    PB:AddToggle("g_3d", { Text = L["Disable 3D Rendering"], Default = false })
    local WB = Tab:AddRightGroupbox(L["AFK Summary"], "bell")
    UI.sum = WB:AddLabel("-", true)
    WB:AddInput("g_hook", { Text = L["Discord Webhook"], Default = "", Numeric = false, Finished = true, Placeholder = "https://discord.com/api/webhooks/..." })
    WB:AddSlider("g_hookmin", { Text = L["Send Every"], Default = 30, Min = 5, Max = 180, Rounding = 0, Suffix = L[" min"] })
    local Menu = Tab:AddRightGroupbox(L["Menu"], "menu")
    Menu:AddLabel(L["Menu Key"]):AddKeyPicker("MenuKeybind", { Default = "RightShift", NoUI = true, Text = L["Menu Key"] })
    Library.ToggleKeybind = Opt.MenuKeybind
    Menu:AddButton({ Text = L["Unload"], Func = function() pcall(_G.__CW_ANT_CLEAN) end })
    SaveManager:SetLibrary(Library)
    ThemeManager:SetLibrary(Library)
    SaveManager:IgnoreThemeSettings()
    SaveManager:SetIgnoreIndexes({ "MenuKeybind", "FeedbackType", "FeedbackMsg" })
    ThemeManager:SetFolder("COMBO_WICK_AntEmpire")
    SaveManager:SetFolder("COMBO_WICK_AntEmpire")
    ThemeManager:ApplyToTab(Tab)
    SaveManager:BuildConfigSection(Tab)
    pcall(function() SaveManager:LoadAutoloadConfig() end)
end)
local function loop(interval, fn)
    task.spawn(function()
        while RUNNING do
            local ok, err = pcall(fn)
            if not ok then S.lastErr = tostring(err) end
            task.wait(type(interval) == "function" and interval() or interval)
        end
    end)
end
loop(0.5, refreshData)
local function vineLive() local id, cd = activity(); return on("e_vine") and id == "Vine" and cd > 0 end
loop(0.1, function()
    if not on("f_roll") or inDungeon() or vineLive() then return end
    local t = clock()
    local r = S.roll
    if r.claimAt and t - r.claimAt < 0.6 then return end
    if r.wait and t - r.sentAt < 3.5 then return end
    if t - r.gotAt < 3.05 or t - r.sentAt < 3.05 then return end
    r.wait = true; r.sentAt = t
    cmd("RollAnt", { Source = "ProximityPrompt" })
end)
loop(3.1, function()
    if not on("f_harvest") then return end
    local idx = {}
    for _, m in ipairs(myAnts()) do idx[#idx + 1] = tonumber(m:GetAttribute("AntIndex")) end
    if #idx == 0 then for i = 1, math.max(D.slots, 1) do idx[i] = i end end
    table.sort(idx)
    cmd("ClaimAntReward", { AntIndices = idx })
end)
loop(2, function()
    if not on("f_harvest") then return end
    local claims = {}
    for _, m in ipairs(myAnts()) do
        local slot = tonumber(m:GetAttribute("AntIndex"))
        local food = math.floor(tonumber(m:GetAttribute("Food")) or 0)
        if slot and food > 0 then claims[#claims + 1] = { SlotIndex = slot, Amount = food } end
    end
    if #claims > 0 then cmd("ClaimWorkerAntFood", { SubmissionId = HttpService:GenerateGUID(false), Claims = claims }) end
end)
loop(15, function()
    if on("f_equip") then actionOnce("equip", "/背包系统/背包装备最佳单位?购买", "__null__", "__null__", { HttpService:JSONEncode({}) }) end
end)
local function antLevelCost(m)
    local price = tonumber(m:GetAttribute("Price")) or 0
    local lvl = math.max(tonumber(m:GetAttribute("Level")) or 1, 1)
    return math.floor(price * 0.05 * 1.35 ^ (lvl - 1))
end
loop(2, function()
    if on("f_slot") then
        local layer = tonumber(lp:GetAttribute("NestLayer")) or 0
        if not (S.slotMax and S.slotMax == layer) then
            S.slotMax = false
            local row = CFG.nest[D.slots]
            local price = row and tonumber(row.Price)
            if price and spendFree() >= price then
                spend(price)
                cmd("AddAntSlot", { Source = "ProximityPrompt", RoomIndex = D.room, SlotIndex = D.slots + 1 })
                task.wait(1)
            end
        end
    end
    if on("f_upant") then
        local ants = myAnts()
        table.sort(ants, function(a, b) return antLevelCost(a) < antLevelCost(b) end)
        for _, m in ipairs(ants) do
            if not on("f_upant") then break end
            local cost = antLevelCost(m)
            if cost <= 0 or spendFree() < cost then break end
            spend(cost)
            cmd("UpgradeEquippedAnt", { Source = "RoomAntInfoGui", AntIndex = tonumber(m:GetAttribute("AntIndex")) })
            task.wait(0.3)
        end
    end
end)
loop(1, function()
    if not on("s_sell") then return end
    if clock() - S.priceAt > 4 then cmd("RequestSellFoodPrice", { Source = "SellShopModel", UserId = lp.UserId }) end
    if clock() - (S.bmAskAt or 0) > 30 then S.bmAskAt = clock(); ev("BlackMarketSnapshotRequest", {}) end
    local n = math.floor(D.food - foodKeep())
    if n <= 0 then return end
    if on("s_bm") and bmOpen() then
        local part = bmSellPart()
        if part and clock() - (S.bmSoldAt or 0) > 5 then
            S.bmSoldAt = clock()
            withTp(function()
                tp(part.Position)
                task.wait(0.35)
                cmd("SellPlayerFood", { FoodAmount = n, Source = "BlackMarket" })
                task.wait(0.6)
            end)
        end
        return
    end
    local pct = pricePct()
    if pct and pct + 0.001 >= val("s_pct", 85) and clock() - (S.soldAt or 0) > 2 then
        S.soldAt = clock()
        cmd("SellPlayerFood", { FoodAmount = n, Source = "SellShopModel" })
    end
end)
loop(1.5, function()
    if on("u_auto") then
        local sel = msel("u_list")
        if sel then
            local list, blocked = {}, 0
            for _, a in ipairs(ATTRS) do
                if sel[a.name] and not S.attrMax[a.key] then
                    if attrBlocked(a.key) then blocked = blocked + 1
                    else
                        local lvl, price = attrLevelPrice(a.key)
                        if price then list[#list + 1] = { a = a, price = price, lvl = lvl } elseif lvl then S.attrMax[a.key] = true end
                    end
                end
            end
            if on("u_cheap") then table.sort(list, function(x, y) return x.price < y.price end) end
            local first = list[1]
            if first then
                if spendFree() >= first.price then
                    spend(first.price)
                    cmd("UpgradePlayerAttribute", { AttributeName = first.a.key })
                    setText(UI.up, first.a.name .. L[" → Lv "] .. (first.lvl + 1))
                else
                    setText(UI.up, L["Next: "] .. first.a.name .. " · " .. fmt(first.price))
                end
            elseif blocked > 0 then
                setText(UI.up, L["Waiting on Luck/Queen"])
            else
                setText(UI.up, L["All selected maxed"])
            end
        end
    end
    if on("u_queen") then
        local q = tonumber(query("/属性/蚁后等级?属性数量"))
        if q and q ~= S.queenSet then S.queenSet = q; cmd("SetCurrentAntQueenLevel", { Level = math.floor(q) }) end
    end
end)
local COMPOST = (function()
    local c = gcall(function() local g = ReplicatedStorage:FindFirstChild("_genConfigs"); local m = g and g:FindFirstChild("battle_tbcompostpool"); if not m then return nil end; local ok, r = pcall(require, m); return ok and r or nil end)
    return type(c) == "table" and type(c.CompostInfo) == "table" and c.CompostInfo.Info or {}
end)()
local function compostRow()
    local lvl = math.max(math.floor(tonumber(query("/属性/堆肥机等级?属性数量")) or 1), 1)
    for _, r in ipairs(COMPOST) do if tonumber(r.Level) == lvl then return r end end
    return nil
end
loop(5, function()
    if on("u_lever") or on("u_compup") then
        local row = compostRow()
        if row then
            if on("u_lever") and clock() - (S.leverAt or 0) > 10 then
                local have = tonumber(query("/货币/堆肥币?属性数量")) or 0
                if have >= (tonumber(row.NeedValue) or math.huge) then S.leverAt = clock(); cmd("CompostPullLever", {}) end
            end
            local up = tonumber(row.UpgradePrice)
            if on("u_compup") and up and up > 0 and spendFree() >= up then spend(up); cmd("CompostUpgrade", {}) end
        end
    end
end)
local CBOOST = gcall(function()
    local b = ReplicatedStorage:FindFirstChild("Battle"); b = b and b:FindFirstChild("Game"); b = b and b:FindFirstChild("Dungeon")
    local m = b and b:FindFirstChild("ClickBoost"); if not m then return nil end
    local ok, r = pcall(require, m); return ok and r or nil
end)
local function boostMult(d)
    if not (CBOOST and CBOOST.Project) then return tonumber(d.attackSpeedMultiplier) or 1 end
    local t = now()
    local _, m = gcall(function()
        local ok, a, b = pcall(CBOOST.Project, d.clickScore or 0, d.attackSpeedMultiplier or 1, math.max(t - (tonumber(d.clickUpdatedAt) or t), 0), (CFG.dungeon or {}).ClickBoost)
        if ok then return a, b end
        return nil, nil
    end)
    return tonumber(m) or tonumber(d.attackSpeedMultiplier) or 1
end
loop(0.1, function()
    local d = S.dg
    if d and d.sessionId and LIVE[d.status] and clock() - S.dgAt > 5 and clock() - (DG.syncAt or 0) > 5 then
        DG.syncAt = clock()
        cmd("DungeonCommand", { Action = "Sync" })
    end
    if inDungeon() and d then
        local st = d.status
        local sid = d.sessionId
        if on("d_auto") and st == "ready" and sid and clock() >= (DG.started[sid] or 0) then
            DG.started[sid] = clock() + 1
            cmd("DungeonCommand", { Action = "Start", SessionId = sid })
        end
        local fighting = st == "fighting" or st == "intermission" or st == "dropping"
        local mult = boostMult(d)
        if fighting and on("d_click") and sid and mult < 4 then
            for _ = 1, 4 do cmd("DungeonCommand", { Action = "Click", SessionId = sid }) end
        end
        if fighting and on("d_coins") and sid and type(d.timeCoins) == "table" then
            local base, land = dgBase(d)
            for _, c in ipairs(d.timeCoins) do
                local id = tonumber(c.id)
                local key = tostring(sid) .. ":" .. tostring(id)
                if id and clock() >= (DG.picked[key] or 0) then
                    local pos = c.position or DG.placed[key]
                    if not pos then
                        local r = hrp()
                        local dir = r and (r.Position - base) * Vector3.new(1, 0, 1)
                        if not dir or dir.Magnitude < 1 then dir = Vector3.new(1, 0, 0) end
                        local p2 = base + dir.Unit * 42
                        pos = Vector3.new(p2.X, land, p2.Z)
                        DG.placed[key] = pos
                        DG.picked[key] = clock() + 0.5
                        cmd("DungeonCommand", { Action = "PlaceTimeCoin", SessionId = sid, CoinId = id, Position = pos })
                    elseif now() >= (tonumber(c.landsAt) or 0) + 0.1 then
                        DG.picked[key] = clock() + 1.5
                        DG.pend[key] = true
                        tp(pos)
                        task.wait(0.15)
                        cmd("DungeonCommand", { Action = "PickupTimeCoin", SessionId = sid, CoinId = id })
                    end
                end
            end
        end
        local left = math.max(0, math.floor((tonumber(d.phaseEndsAt) or now()) - now()))
        setText(UI.dg, string.format(L["Lv %s · %sx · %ds"], tostring(d.level or "-"), tostring(mult), left))
        return
    end
    if not on("d_auto") or S.tpBusy then
        setText(UI.dg, string.format(L["Kills %d · Coins %d"], S.stats.kills, S.stats.coins))
        return
    end
    if clock() - DG.lastEnter < 20 then return end
    local e = freshEntrance()
    if e and e.pos then
        DG.lastEnter = clock()
        DG.noneSince = nil
        setText(UI.dg, L["Entering dungeon"])
        S.tpBusy = true
        tp(e.pos)
        task.wait(0.4)
        firePrompt(e.prompt, true)
        local t0 = clock()
        while RUNNING and clock() - t0 < 8 and not inDungeon() do
            local r = hrp()
            if r and (r.Position - e.pos).Magnitude > 8 then tp(e.pos) end
            task.wait(0.2)
        end
        S.tpBusy = false
        return
    end
    DG.noneSince = DG.noneSince or clock()
    local waitHop = val("d_hopwait", 60)
    if on("d_hop") then
        local left = math.max(0, math.floor(waitHop - (clock() - DG.noneSince)))
        setText(UI.dg, L["No portal · hop in "] .. left .. "s")
        if left <= 0 then DG.noneSince = clock() + 30; hopServer() end
    else
        setText(UI.dg, L["Waiting for a portal"])
    end
end)
loop(3, function()
    if on("d_buyegg") then
        local id = val("d_egg")
        for _, e in ipairs(LISTS.eggRows or {}) do
            if e.id == id and D.pet >= e.price and e.price > 0 then
                actionOnce("egg", "/功能商人/购买宠物蛋?购买", "__null__", "__null__", { id, 1 })
                break
            end
        end
    end
    setText(UI.pet, L["Pet Coins: "] .. fmt(D.pet))
end)
loop(30, function()
    if not on("d_stroke") then return end
    local f = Workspace:FindFirstChild("EquippedPets"); if not f then return end
    for _, m in ipairs(f:GetChildren()) do
        local uid, key = m.Name:match("^Pet_(%d+)_(.+)$")
        if tonumber(uid) == lp.UserId and key then
            cmd("StrokePet", { PetKey = key })
            task.wait(0.3)
        end
    end
end)
loop(0.6, function()
    local id, cd = activity()
    local nid = Workspace:GetAttribute("NextActivityId")
    local ncd = tonumber(Workspace:GetAttribute("NextActivityCountdownSeconds")) or 0
    setText(UI.ev, (id and cd > 0) and string.format(L["Now: %s · %ds"], tostring(id), cd) or string.format(L["Next: %s · %ds"], tostring(nid or "-"), ncd))
    if on("e_snail") and id == "TravelSnail" and cd > 0 then actionOnce("snail", "/功能商人/蜗牛活动抽奖?购买") end
end)
loop(1, function()
    if on("e_spin") and D.act >= 10 and activity() == "StrawberryKing" then actionOnce("spin", "/功能商人/草莓国王活动转盘抽奖?购买", "__null__", "__null__", { "StrawberryKingEvent", 1 }) end
    if on("e_straw") and not S.tpBusy and not inDungeon() then
        local f = Workspace:FindFirstChild("_StrawberryKingActivityCoins")
        if f then
            local prompts = {}
            for _, p in ipairs(f:GetDescendants()) do
                if p:IsA("ProximityPrompt") and p.Enabled then prompts[#prompts + 1] = p end
            end
            if #prompts > 0 then
                withTp(function()
                    for _, p in ipairs(prompts) do
                        if not on("e_straw") then break end
                        pcall(function()
                            local m = p.Parent
                            while m and m.Parent and m.Parent ~= f do m = m.Parent end
                            if not (m and m.Parent and p.Parent) then return end
                            local a = m:GetPivot().Position
                            task.wait(0.15)
                            if not m.Parent then return end
                            local b = m:GetPivot().Position
                            if (a - b).Magnitude > 0.5 then return end
                            tp(b); task.wait(0.3)
                            if p.Parent and p.Enabled then firePrompt(p) end
                            task.wait(0.3)
                        end)
                    end
                end)
            end
        end
    end
end)
loop(1, function()
    if not on("e_vine") then return end
    local id, cd = activity()
    if id ~= "Vine" or cd <= 0 or S.tpBusy or inDungeon() then return end
    local vine = Workspace:FindFirstChild("Vine")
    if not vine then for _, c in ipairs(Workspace:GetChildren()) do if c.Name:find("Vine") then vine = c; break end end end
    local pp = vine and vine:FindFirstChildWhichIsA("ProximityPrompt", true)
    local pos = pp and partPos(pp.Parent)
    if not pos then return end
    local r = hrp()
    if r and (r.Position - pos).Magnitude > 10 then tp(pos) end
    task.wait(0.2)
    firePrompt(pp)
end)
onEvent("GearShopSnapshot", function(d)
    if type(d) == "table" and type(d.StockByItem) == "table" then
        S.gearStock = d.StockByItem; S.gearAt = clock(); S.gearNext = tonumber(d.NextRefreshAt)
    end
end)
onEvent("GearShopResult", function(d)
    if type(d) ~= "table" then return end
    local snap = type(d.Snapshot) == "table" and d.Snapshot or d
    if type(snap.StockByItem) == "table" then S.gearStock = snap.StockByItem end
    if d.Success then S.stats.gear = S.stats.gear + 1 elseif d.Reason then gameMsg(reasonText(d.Reason)) end
end)
loop(1, function()
    local nr = S.gearNext or ((math.floor(os.time() / 300) + 1) * 300)
    local left = math.max(0, math.floor(nr - now()))
    setText(UI.gear, string.format(L["Restock in %d:%02d · Bought %d"], math.floor(left / 60), left % 60, S.stats.gear))
    S.shopNeed = 0
    if not on("g_buy") then return end
    if clock() - S.gearAt > 20 or left <= 0 then S.gearAt = clock(); ev("GearShopRequest", { Action = "Snapshot" }) end
    local sel = msel("g_items"); if not sel then return end
    local budget = spendable()
    local need
    for name in pairs(sel) do
        local it = LISTS.gearByName[name]
        if it and (tonumber(S.gearStock[it.id]) or 0) > 0 and it.price <= math.max(budget, 0) * 3 and (not need or it.price < need) then need = it.price end
    end
    S.shopNeed = need or 0
    for name in pairs(sel) do
        local it = LISTS.gearByName[name]
        local stock = it and tonumber(S.gearStock[it.id]) or 0
        if it and stock > 0 and budget >= it.price then
            budget = budget - it.price
            spend(it.price)
            S.gearStock[it.id] = stock - 1
            ev("GearShopRequest", { Action = "Purchase", ItemId = it.id })
            task.wait(0.2)
        end
    end
end)
local JELLY = {}
local MUTTRY = {}
S.items = nil
local function takeStacks(d)
    local data = type(d) == "table" and d.Data
    if type(data) == "table" and type(data.ItemStacks) == "table" then S.items = data.ItemStacks end
    if type(data) == "table" and type(data.PetEggStacks) == "table" then S.eggStacks = data.PetEggStacks end
end
onEvent("AutoUsePotionResult", takeStacks)
onEvent("BackpackEquippedSlotsChanged", takeStacks)
local EGG = { placed = nil, askAt = 0, block = 0, hatchTry = {} }
onEvent("PlacedPetEggStateSync", function(d) if type(d) == "table" and type(d.Eggs) == "table" then EGG.placed = d.Eggs end end)
onEvent("PetEggPlaced", function() EGG.askAt = 0 end)
EGG.newPets = {}
onEvent("PetEggHatched", function(d)
    EGG.askAt = 0; S.stats.hatched = (S.stats.hatched or 0) + 1
    if type(d) == "table" and d.PetKey then EGG.newPets[#EGG.newPets + 1] = d.PetKey end
end)
local function myPetCount()
    local f = Workspace:FindFirstChild("EquippedPets"); if not f then return 0 end
    local n = 0
    for _, m in ipairs(f:GetChildren()) do if tonumber(m.Name:match("^Pet_(%d+)_")) == lp.UserId then n = n + 1 end end
    return n
end
onEvent("PetEggPlacementFailed", function(d) EGG.block = clock() + 30; if type(d) == "table" and d.Reason then gameMsg("Egg: " .. tostring(d.Reason)) end end)
local function eggHome()
    local r = myRoom()
    local pm = r and r:FindFirstChild("PetMoveRanage")
    if not pm then return nil end
    local params = RaycastParams.new()
    params.FilterType = Enum.RaycastFilterType.Exclude
    local ex = { pm }
    for _, n in ipairs({ "Client_Assets", "EquippedPets", "PlacedPetEggs" }) do local f = Workspace:FindFirstChild(n); if f then ex[#ex + 1] = f end end
    if lp.Character then ex[#ex + 1] = lp.Character end
    params.FilterDescendantsInstances = ex
    local off = Vector3.new((math.random() - 0.5) * pm.Size.X * 0.6, 0, (math.random() - 0.5) * pm.Size.Z * 0.6)
    local p = pm.CFrame:PointToWorldSpace(off)
    local hit = Workspace:Raycast(p + Vector3.new(0, 25, 0), Vector3.new(0, -80, 0), params)
    if hit and hit.Normal.Y >= 0.55 then return hit end
    return nil
end
loop(3, function()
    if not on("d_hatch") or S.tpBusy or inDungeon() or lp:GetAttribute("DungeonSessionId") ~= nil then return end
    if clock() - EGG.askAt > 20 then EGG.askAt = clock(); ev("RequestPlacedPetEggState", {}) end
    if not EGG.placed then return end
    for hid in pairs(EGG.hatchTry) do if not EGG.placed[hid] then EGG.hatchTry[hid] = nil end end
    if #EGG.newPets > 0 then
        local max = tonumber(query("/属性/宠物最大装备数量?属性数量")) or 1
        if myPetCount() < max then
            local key = table.remove(EGG.newPets, 1)
            local hit = eggHome()
            if hit then
                withTp(function()
                    tp(hit.Position + Vector3.new(3, 0, 3)); task.wait(0.4)
                    ev("SetBackpackHeldEntry", { Kind = "Pet", EntryKey = "Pet:" .. key, PetKey = key })
                    task.wait(0.6)
                    cmd("PlacePet", { PetKey = key, Position = hit.Position, Normal = hit.Normal })
                    task.wait(1)
                    ev("SetBackpackHeldEntry", {})
                end)
            end
            return
        else
            EGG.newPets = {}
        end
    end
    local t = now()
    local f = Workspace:FindFirstChild("PlacedPetEggs")
    for hid, e in pairs(EGG.placed) do
        if type(e) == "table" and (tonumber(e.HatchAt) or math.huge) <= t and clock() >= (EGG.hatchTry[hid] or 0) then
            EGG.hatchTry[hid] = clock() + 10
            local model
            for _, m in ipairs(f and f:GetChildren() or {}) do if m:GetAttribute("HatchId") == hid then model = m end end
            withTp(function()
                local pos = model and partPos(model)
                if pos then tp(pos + Vector3.new(4, 0, 0)); task.wait(0.4) end
                ev("SetBackpackHeldEntry", {})
                task.wait(0.5)
                ev("HatchPlacedPetEgg", { HatchId = hid })
                task.wait(1)
            end)
            return
        end
    end
    if clock() < EGG.block then return end
    if not S.eggStacks or clock() - (EGG.bpAt or 0) > 30 then
        EGG.bpAt = clock()
        local stacks = gcall(function()
            local u = ReplicatedStorage:FindFirstChild("UI"); u = u and u:FindFirstChild("Backpack"); u = u and u:FindFirstChild("Model"); u = u and u:FindFirstChild("BackpackModel")
            if not u then return nil end
            local ok, bm = pcall(require, u)
            local data = ok and type(bm) == "table" and bm.BackPackData
            return type(data) == "table" and data.PetEggStacks or nil
        end)
        if type(stacks) == "table" then S.eggStacks = table.clone(stacks) end
    end
    local id
    for eid, n in pairs(S.eggStacks or {}) do if (tonumber(n) or 0) > 0 then id = eid; break end end
    if not id then return end
    local hit = eggHome()
    if not hit then return end
    withTp(function()
        tp(hit.Position + Vector3.new(3, 0, 3)); task.wait(0.5)
        ev("SetBackpackHeldEntry", { Kind = "PetEgg", EntryKey = "PetEgg:" .. id, PetEggId = id })
        task.wait(0.6)
        ev("PlaceSelectedPetEgg", { PetEggId = id, Position = hit.Position, Normal = hit.Normal })
        task.wait(1.2)
        ev("SetBackpackHeldEntry", {})
        task.wait(0.3)
    end)
    if S.eggStacks then S.eggStacks[id] = math.max((tonumber(S.eggStacks[id]) or 1) - 1, 0) end
    EGG.askAt = 0
end)
local function owned(id)
    if not S.items then return nil end
    return tonumber(S.items[id]) or 0
end
loop(5, function()
    if on("g_jelly") then
        local it = LISTS.gearByName[val("g_jellyid") or ""]
        local dur = it and (it.dur > 0 and it.dur or 300) or 300
        if it then
            for _, m in ipairs(myAnts()) do
                local have = owned(it.id)
                if have and have <= 0 then break end
                local slot = tonumber(m:GetAttribute("AntIndex"))
                if slot and clock() >= (JELLY[slot] or 0) then
                    JELLY[slot] = clock() + dur + 2
                    if S.items then S.items[it.id] = (have or 1) - 1 end
                    ev("UseAutoToolPotion", { RequestId = HttpService:GenerateGUID(false), SlotIndex = slot, PotionId = it.id })
                    task.wait(0.3)
                end
            end
        end
    end
    if on("g_mut") then
        local sel = msel("g_mutids"); if not sel then return end
        local best = {}
        for name in pairs(sel) do local it = LISTS.gearByName[name]; if it and it.mut then best[#best + 1] = { it = it, mul = LISTS.tagMul[it.mut] or 1 } end end
        table.sort(best, function(a, b) return a.mul > b.mul end)
        for _, m in ipairs(myAnts()) do
            local slot = tonumber(m:GetAttribute("AntIndex"))
            local curMul = LISTS.tagMul[LISTS.tagById[tonumber(m:GetAttribute("TagId")) or 0] or "None"] or 1
            for _, b in ipairs(best) do
                local key = tostring(slot) .. b.it.id
                local have = owned(b.it.id)
                if b.mul > curMul + 0.001 and (have == nil or have > 0) and clock() >= (MUTTRY[key] or 0) then
                    MUTTRY[key] = clock() + 30
                    if S.items then S.items[b.it.id] = (have or 1) - 1 end
                    ev("SetBackpackHeldEntry", { Kind = "Item", EntryKey = "Item:" .. b.it.id, ItemId = b.it.id })
                    task.wait(0.4)
                    ev("UsePotionOnRoomSlot", { RoomIndex = D.room, SlotIndex = slot, ItemId = b.it.id })
                    task.wait(0.6)
                    ev("SetBackpackHeldEntry", {})
                    break
                end
            end
        end
    end
end)
local FX = { on = false, saved = setmetatable({}, { __mode = "k" }), conns = {} }
local FX_CLASS = { ParticleEmitter = true, Beam = true, Trail = true, Fire = true, Smoke = true, Sparkles = true }
FX.watched = setmetatable({}, { __mode = "k" })
local function fxOff(d)
    if not FX_CLASS[d.ClassName] then return end
    if d.Enabled and FX.saved[d] == nil then
        FX.saved[d] = true
        pcall(function() d.Enabled = false end)
    end
    if not FX.watched[d] then
        FX.watched[d] = d:GetPropertyChangedSignal("Enabled"):Connect(function()
            if FX.on and d.Enabled then FX.saved[d] = true; d.Enabled = false end
        end)
    end
end
local function setFx(want)
    if want == FX.on then return end
    FX.on = want
    if want then
        task.spawn(function()
            local n = 0
            for _, d in ipairs(Workspace:GetDescendants()) do
                if not FX.on then return end
                fxOff(d)
                n = n + 1; if n % 600 == 0 then task.wait() end
            end
        end)
        FX.conns[#FX.conns + 1] = Workspace.DescendantAdded:Connect(function(d)
            if FX.on and FX_CLASS[d.ClassName] then task.defer(fxOff, d) end
        end)
        for _, e in ipairs(game:GetService("Lighting"):GetChildren()) do
            if (e:IsA("BloomEffect") or e:IsA("SunRaysEffect") or e:IsA("BlurEffect") or e:IsA("DepthOfFieldEffect")) and e.Enabled then FX.saved[e] = true; e.Enabled = false end
        end
    else
        for _, c in ipairs(FX.conns) do pcall(function() c:Disconnect() end) end
        FX.conns = {}
        for _, c in pairs(FX.watched) do if typeof(c) == "RBXScriptConnection" then pcall(function() c:Disconnect() end) end end
        FX.watched = setmetatable({}, { __mode = "k" })
        for d in pairs(FX.saved) do pcall(function() if d.Parent then d.Enabled = true end end) end
        FX.saved = setmetatable({}, { __mode = "k" })
    end
end
onClean(function() setFx(false) end)
local GSET = { applied = {}, orig = {} }
local GSET_LIST = { { t = "g_others", key = "ShowOtherAnts", want = false }, { t = "g_lowgfx", key = "LowPerformance", want = true } }
local function gameSetting(key, value)
    return gcall(function()
        local h = ReplicatedStorage:FindFirstChild("Helper"); h = h and h:FindFirstChild("PlayerSettingHelper")
        if not h then return nil end
        local ok, m = pcall(require, h)
        if not (ok and m) then return nil end
        local cur = m.GetLocalSettings and m.GetLocalSettings()
        local before = type(cur) == "table" and cur[key]
        if value ~= nil and m.SetLocalSetting then pcall(m.SetLocalSetting, key, value) end
        return before
    end)
end
loop(1, function()
    for _, g in ipairs(GSET_LIST) do
        local want = on(g.t) == true
        if want and not GSET.applied[g.t] then
            local before = gameSetting(g.key, g.want)
            if GSET.orig[g.key] == nil then GSET.orig[g.key] = before end
            GSET.applied[g.t] = true
        elseif not want and GSET.applied[g.t] then
            local o = GSET.orig[g.key]
            if o == nil then o = not g.want end
            gameSetting(g.key, o)
            GSET.applied[g.t] = nil
        end
    end
end)
onClean(function()
    for _, g in ipairs(GSET_LIST) do
        if GSET.applied[g.t] then local o = GSET.orig[g.key]; if o == nil then o = not g.want end; gameSetting(g.key, o) end
    end
end)
local POPUPS = { "AwardReward", "DungeonEggRewardGui" }
local popSaved = {}
loop(0.5, function()
    setFx(on("g_fx") == true)
    local pg = lp:FindFirstChild("PlayerGui"); if not pg then return end
    local hud = pg:FindFirstChild("HUDContainer")
    local ef = hud and hud:FindFirstChild("EffectFrame")
    if ef and ef:IsA("GuiObject") then
        if on("g_fx") then
            if ef.Visible then FX.hud = ef; ef.Visible = false end
        elseif FX.hud then
            pcall(function() FX.hud.Visible = true end); FX.hud = nil
        end
    end
    if on("g_popups") then
        for _, n in ipairs(POPUPS) do
            local g = pg:FindFirstChild(n)
            if g and g:IsA("ScreenGui") and g.Enabled then popSaved[g] = true; g.Enabled = false end
        end
    elseif next(popSaved) then
        for g in pairs(popSaved) do pcall(function() g.Enabled = true end) end
        popSaved = {}
    end
end)
onClean(function()
    for g in pairs(popSaved) do pcall(function() g.Enabled = true end) end
    if FX.hud then pcall(function() FX.hud.Visible = true end) end
end)
local CLAIMED = {}
loop(5, function()
    if not on("r_all") then return end
    if clock() - (CLAIMED.online or -1e9) < 60 then return end
    CLAIMED.online = clock()
    local n = 0
    action("/功能商人/在线奖励领取?购买", "__null__", "__null__", "__null__")
    if clock() - (CLAIMED.daily or -1e9) > 300 then
        CLAIMED.daily = clock()
        action("/功能商人/七日奖励领取?购买", "__null__", "__null__", "__null__")
        action("/活动/群组奖励/群组每日奖励?购买")
        local okA, ad = pcall(function() return HttpService:JSONDecode(lp:GetAttribute("ActivityData") or "{}") end)
        if okA and type(ad) == "table" then
            local login, got = tonumber(ad.LoginMask) or 0, tonumber(ad.RewardMask) or 0
            for day = 1, 14 do
                local bit = 2 ^ (day - 1)
                if math.floor(login / bit) % 2 == 1 and math.floor(got / bit) % 2 == 0 then
                    action("/功能商人/活动签到?购买", "__null__", "__null__", { DayId = day })
                    n = n + 1
                end
            end
        end
        local PROG = { AntCollectReward = "蚂蚁图鉴奖励进度", MutationCollectReward = "突变图鉴奖励进度" }
        for cid, prop in pairs(PROG) do
            local row = CFG.index[cid]
            local done = math.max(math.floor(tonumber(query("/属性/" .. prop .. "?属性数量")) or 0), 0)
            local tier = type(row) == "table" and type(row.Content) == "table" and row.Content[done + 1]
            if tier then
                action("/图鉴系统/领取图鉴奖励?购买", "__null__", "__null__", { HttpService:JSONEncode({ ConfigId = row.Id or cid, Level = tier.Level }) })
                task.wait(0.2)
            end
        end
        if clock() - (CLAIMED.ride or -1e9) > 600 then CLAIMED.ride = clock(); for i = 1, #CFG.ride do action("/功能商人/骑乘单位进度奖励领取?购买", "__null__", "__null__", { i }); task.wait(0.1) end end
    end
    setText(UI.rew, L["Last check "] .. os.date("%H:%M"))
end)
loop(1, function()
    local s = S.stats
    setText(UI.roll, string.format(L["Rolled %d · Bought %d"], s.rolled, s.bought))
    local pct = pricePct()
    local p = S.price
    if bmOpen() then setText(UI.price, L["Black Market open"])
    elseif p and pct then setText(UI.price, string.format(L["Price %.2f · %d%%"], tonumber(p.GoldPerFood) or 0, math.floor(pct)))
    else setText(UI.price, L["Price: waiting"]) end
    setText(UI.money, string.format(L["Cash %s · Food %s"], fmt(D.gold), fmt(D.food)))
    local mins = math.floor((clock() - s.started) / 60)
    local line = string.format("%dm · Sold %s · +%s cash\nBought %d ants · %d kills", mins, fmt(s.sold), fmt(s.earned), s.bought, s.kills)
    if S.msg ~= "" then line = line .. "\n" .. S.msg end
    setText(UI.sum, line)
end)
loop(30, function()
    local url = tostring(val("g_hook", ""))
    if not url:find("^https://discord") then return end
    if clock() - (S.hookAt or 0) < val("g_hookmin", 30) * 60 then return end
    S.hookAt = clock()
    local req = request or (syn and syn.request) or http_request
    if not req then return end
    local s = S.stats
    local msg = string.format("**%s** · %dm\nCash %s · Food %s\nSold %s food for %s\nBought %d ants (%s) · Rolled %d\nDungeon kills %d · Time coins %d · Gear %d",
        lp.Name, math.floor((clock() - s.started) / 60), fmt(D.gold), fmt(D.food), fmt(s.sold), fmt(s.earned), s.bought, fmt(s.spent), s.rolled, s.kills, s.coins, s.gear)
    pcall(req, { Url = url, Method = "POST", Headers = { ["Content-Type"] = "application/json" }, Body = HttpService:JSONEncode({ content = msg }) })
end)
local FLY = { bv = nil, bg = nil }
local function stopFly()
    if FLY.bv then pcall(function() FLY.bv:Destroy() end) end
    if FLY.bg then pcall(function() FLY.bg:Destroy() end) end
    FLY.bv, FLY.bg = nil, nil
end
onClean(stopFly)
track(RunService.Heartbeat:Connect(function()
    if not RUNNING then return end
    local c = lp.Character
    local hum = c and c:FindFirstChildOfClass("Humanoid")
    local r = hrp()
    if hum and on("p_speed") then hum.WalkSpeed = val("p_speedv", 40) end
    if on("p_fly") and r and hum then
        if not FLY.bv or FLY.bv.Parent ~= r then
            stopFly()
            FLY.bv = Instance.new("BodyVelocity"); FLY.bv.MaxForce = Vector3.new(1e9, 1e9, 1e9); FLY.bv.Velocity = Vector3.zero; FLY.bv.Parent = r
            FLY.bg = Instance.new("BodyGyro"); FLY.bg.MaxTorque = Vector3.new(1e9, 1e9, 1e9); FLY.bg.P = 9e4; FLY.bg.Parent = r
        end
        local cam = Workspace.CurrentCamera
        local dir = hum.MoveDirection
        local up = (UserInputService:IsKeyDown(Enum.KeyCode.Space) and 1 or 0) - (UserInputService:IsKeyDown(Enum.KeyCode.LeftControl) and 1 or 0)
        local look = cam.CFrame.LookVector
        local v = dir * val("p_flyv", 60)
        if dir.Magnitude > 0 then v = v + Vector3.new(0, look.Y * dir.Magnitude * val("p_flyv", 60), 0) end
        FLY.bv.Velocity = v + Vector3.new(0, up * val("p_flyv", 60), 0)
        FLY.bg.CFrame = cam.CFrame
    elseif FLY.bv then stopFly() end
end))
track(RunService.Stepped:Connect(function()
    if not (RUNNING and (on("p_noclip") or on("p_fly"))) then return end
    local c = lp.Character
    if c then for _, p in ipairs(c:GetDescendants()) do if p:IsA("BasePart") and p.CanCollide then p.CanCollide = false end end end
end))
track(UserInputService.JumpRequest:Connect(function()
    if not on("p_jump") then return end
    local c = lp.Character
    local hum = c and c:FindFirstChildOfClass("Humanoid")
    if hum then hum:ChangeState(Enum.HumanoidStateType.Jumping) end
end))
track(game:GetService("ProximityPromptService").PromptButtonHoldBegan:Connect(function(p)
    if on("p_prompt") and fireproximityprompt then pcall(fireproximityprompt, p) end
end))
track(lp.Idled:Connect(function()
    if on("g_antiidle") then pcall(function() VirtualUser:CaptureController(); VirtualUser:ClickButton2(Vector2.new()) end) end
end))
local function staffCheck(p)
    if not (on("g_staff") and p and STAFF[p.UserId]) then return end
    local what = val("g_staffdo", "Notify")
    notify(L["Staff joined: "] .. p.Name)
    if what == "Hop Server" then hopServer() elseif what == "Leave" then lp:Kick("Staff joined") end
end
track(Players.PlayerAdded:Connect(staffCheck))
task.delay(3, function() for _, p in ipairs(Players:GetPlayers()) do staffCheck(p) end end)
local r3d = true
loop(1, function()
    local want = not on("g_3d")
    if want ~= r3d then r3d = want; pcall(function() RunService:Set3dRenderingEnabled(want) end) end
end)
onClean(function() pcall(function() RunService:Set3dRenderingEnabled(true) end) end)
notify(L["Loaded"])

end
