-- Russian Translation
-- Script ID: 0de1d27457c7b1852e6f5f7dc6be8202
-- Updated: 2026-04-27T21:06:51.497Z
-- Auto-generated by Lua Script Vault

local MODULE_URL = "https://raw.githubusercontent.com/YOUR_USERNAME/YOUR_REPO/main/Module.lua"
local M = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/main/+1health"))()

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()
local Options = Library.Options
local Toggles = Library.Toggles

local Window = Library:CreateWindow({
	Title = "COMBO_WICK",
	ShowCustomCursor = false,
	Size = UDim2.new(0, 450, 0, 500),
	Position = UDim2.new(0.5, -225, 0.5, -250),
	AutoShow = true,
	NotifySide = "Right",
})

local Tabs = {
	Main = Window:AddTab("Главное ", "user"),
	Shop = Window:AddTab("Магазин ", "shopping-cart"),
	UI   = Window:AddTab("Настройки интерфейса ", "settings"),
}

local LeftGroup  = Tabs.Main:AddLeftGroupbox("Передвижение ")
local RightGroup = Tabs.Main:AddRightGroupbox("Усиления ")
local TeleGroup  = Tabs.Main:AddLeftGroupbox("Телепорт ")
local ShopGroup  = Tabs.Shop:AddLeftGroupbox("Бесплатные покупки ")
local MenuGroup  = Tabs.UI:AddLeftGroupbox("Меню ")

LeftGroup:AddSlider("WalkSpeedSlider", {
	Text     = "Скорость ходьбы",
	Default  = 16,
	Min      = 16,
	Max      = 250,
	Rounding = 0,
	Suffix   = " sp",
})
Options.WalkSpeedSlider:OnChanged(function()
	M.setWalkSpeed(Options.WalkSpeedSlider.Value)
end)

LeftGroup:AddSlider("JumpPowerSlider", {
	Text     = "Сила прыжка",
	Default  = 50,
	Min      = 50,
	Max      = 500,
	Rounding = 0,
	Suffix   = " jp",
})
Options.JumpPowerSlider:OnChanged(function()
	M.setJumpPower(Options.JumpPowerSlider.Value)
end)

M.buildTeleportToggles(TeleGroup, Toggles)

RightGroup:AddToggle("InfHealthToggle", { Text = "Режим бога",  Default = false })
RightGroup:AddToggle("AutoClickToggle", { Text = "Автофарм", Default = false })
RightGroup:AddToggle("RebirthToggle",   { Text = "Rebirth",   Default = false })
RightGroup:AddToggle("InfSpinsToggle",  { Text = "Фарм вращением", Default = false })

M.startMovementLoop()
M.startBoostLoop(Toggles)

M.buildShop(ShopGroup)

MenuGroup:AddToggle("ShowCustomCursorToggle", { Text = "Пользовательский курсор", Default = false })
Toggles.ShowCustomCursorToggle:OnChanged(function()
	Library.ShowCustomCursor = Toggles.ShowCustomCursorToggle.Value
end)

MenuGroup:AddDropdown("NotifSideDropdown", {
	Values  = { "Left", "Right" },
	Default = "Right",
	Text    = "Сторона уведомлений",
})
Options.NotifSideDropdown:OnChanged(function()
	Library:SetNotifySide(Options.NotifSideDropdown.Value)
end)

MenuGroup:AddDropdown("DPIDropdown", {
	Values  = { "50%", "75%", "100%", "125%", "150%", "175%", "200%" },
	Default = "100%",
	Text    = "Масштаб DPI",
})
Options.DPIDropdown:OnChanged(function()
	local v = Options.DPIDropdown.Value:gsub("%%", "")
	Library:SetDPIScale(tonumber(v))
end)

MenuGroup:AddDivider()
MenuGroup:AddLabel("Hotkey"):AddKeyPicker("MenuKeybind", { Default = "RightShift", NoUI = true, Text = "Клавиша меню" })
MenuGroup:AddButton({ Text = "Close", Func = function() M.stop() Library:Unload() end })

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("COMBO_WICK")
SaveManager:SetFolder("COMBO_WICK/saves")
SaveManager:BuildConfigSection(Tabs.UI)
ThemeManager:ApplyToTab(Tabs.UI)
SaveManager:LoadAutoloadConfig()