-- Protected Script (Portuguese)
-- Script ID: 0f337d635adba588ceedeee0ec6a002e
-- Created: 2025-12-22T16:26:11.708Z
-- Source: External API
-- Auto-generated by Lua Script Vault

-- Main Script
-- Este carrega o módulo e cria a UI

if getgenv().ComboWickLoaded then
    getgenv().ComboWickLoaded:Unload()
end

-- Load Obsidian Library
local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()

-- Load ComboWick Module
local moduleUrl = "https://raw.githubusercontent.com/checkurasshole/Trt/refs/heads/main/rt"
local ComboWick = loadstring(game:HttpGet(moduleUrl))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ShowCustomCursor = false

getgenv().ComboWickLoaded = Library

-- Create Window
local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Footer = "By COMBO_WICK",
    ShowCustomCursor = false,
    Position = UDim2.new(0.5, -200, 0.5, -150),
    Size = UDim2.new(0, 400, 0, 300),
})

-- Create Tabs
local Tabs = {
    Main = Window:AddTab("Principal", "shopping-cart"),
}

-- Main Purchases Box
local MainBox = Tabs.Main:AddLeftGroupbox("Compras", "package")

task.spawn(function()
    local items = ComboWick.fetchAllItems()
    
    if #items > 0 then
        -- Process and rename items
        local processedItems = {}
        local specialItem = nil
        local coinPack = nil
        local keyPack = nil
        local otherItems = {}
        
        for _, item in pairs(items) do
            local itemData = {
                Name = item.Name,
                ProductId = item.ProductId,
            }
            
            if item.Name:match("OP DOMINUS PET") then
                itemData.Name = "Melhor animal de estimação do jogo"
                specialItem = itemData
            elseif item.Name:match("Coin Pack 5") or item.Name:match("coin pack 5") then
                itemData.Name = "Moedas infinitas"
                coinPack = itemData
            elseif item.Name:match("Keys Pack 5") or item.Name:match("keys pack 5") then
                itemData.Name = "Chaves infinitas"
                keyPack = itemData
            else
                table.insert(otherItems, itemData)
            end
        end
        
        -- Add items in priority order
        if specialItem then
            table.insert(processedItems, specialItem)
        end
        if coinPack then
            table.insert(processedItems, coinPack)
        end
        if keyPack then
            table.insert(processedItems, keyPack)
        end
        for _, item in ipairs(otherItems) do
            table.insert(processedItems, item)
        end
        
        -- Add "Get Everything" button
        MainBox:AddButton({
            Text = "Obtenha tudo!",
            Func = function()
                ComboWick.purchaseAll(items, 0.3)
            end
        })
        
        MainBox:AddDivider()
        
        -- Add toggle for each item
        for _, item in ipairs(processedItems) do
            MainBox:AddToggle("Toggle_" .. item.ProductId, {
                Text = item.Name,
                Default = false,
                Callback = function(value)
                    if value then
                        ComboWick.startAutoPurchase(item.ProductId, 0.1)
                    else
                        ComboWick.stopAutoPurchase(item.ProductId)
                    end
                end,
            })
        end
    end
end)

-- Manual Purchase Box
local ManualBox = Tabs.Main:AddRightGroupbox("Compra manual", "edit")

local manualItemId = 0
local manualToggleActive = false

ManualBox:AddInput("ManualID", {
    Default = "",
    Numeric = true,
    Finished = true,
    Text = "ID do item",
    Placeholder = "Insira o ID do item",
    Callback = function(Value)
        local id = tonumber(Value)
        if id then
            manualItemId = id
        end
    end,
})

ManualBox:AddToggle("ManualPurchase", {
    Text = "Comprar item manualmente",
    Default = false,
    Callback = function(value)
        manualToggleActive = value
        if value then
            if manualItemId > 0 then
                ComboWick.startAutoPurchase(manualItemId, 0.1)
            else
                manualToggleActive = false
                Toggles.ManualPurchase:SetValue(false)
            end
        else
            if manualItemId > 0 then
                ComboWick.stopAutoPurchase(manualItemId)
            end
        end
    end,
})