-- Protected Script (Filipino)
-- Script ID: 11dcbef1552c11ef0ac66f72bfc4f80c
-- Created: 2025-12-22T18:57:57.443Z
-- Source: External API
-- Auto-generated by Lua Script Vault

if getgenv().ComboWickLoaded then
    getgenv().ComboWickLoaded:Unload()
end

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()

local Module = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/Trt/refs/heads/main/inf%20money"))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ShowCustomCursor = false

getgenv().ComboWickLoaded = Library

local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Footer = "By COMBO_WICK",
    ShowCustomCursor = false,
    Position = UDim2.new(0.5, -200, 0.5, -150),
    Size = UDim2.new(0, 400, 0, 300),
})

local Tabs = {
    Main = Window:AddTab("Pangunahin", "shopping-cart"),
    Other = Window:AddTab("Iba pa", "zap"),
}

local MainBox = Tabs.Main:AddLeftGroupbox("Estadistika", "package")

MainBox:AddButton({
    Text = "Pinakamataas na Estadistika",
    Func = function()
        Module.trainStat("9999e15")
        task.wait(0.1)
        Module.winGainStat("9999e15")
    end
})

MainBox:AddDivider()

local customTrainValue = "1"

MainBox:AddInput("CustomTrain", {
    Default = "",
    Numeric = false,
    Finished = true,
    Text = "Lakas",
    Placeholder = "",
    Callback = function(Value)
        customTrainValue = Value
    end,
})

MainBox:AddButton({
    Text = "Sanayin ang Lakas",
    Func = function()
        Module.trainStat(customTrainValue)
    end
})

MainBox:AddDivider()

local customWinGainValue = "1"

MainBox:AddInput("CustomWinGain", {
    Default = "",
    Numeric = false,
    Finished = true,
    Text = "Salapi",
    Placeholder = "",
    Callback = function(Value)
        customWinGainValue = Value
    end,
})

MainBox:AddButton({
    Text = "WinGain Salapi",
    Func = function()
        Module.winGainStat(customWinGainValue)
    end
})

local RightBox = Tabs.Main:AddRightGroupbox("Iba pa", "zap")

RightBox:AddButton({
    Text = "Marahuyo",
    Func = function()
        Module.enchanted(195500000000, 0.15)
    end
})

RightBox:AddButton({
    Text = "Pagdaragdag ng Kalusugan / Muling Pagsilang",
    Func = function()
        Module.healthAdd(25)
    end
})

local OtherBox = Tabs.Other:AddLeftGroupbox("Mga Mundo at Bagay", "globe")

OtherBox:AddButton({
    Text = "I-lock ang Lahat ng Mundo",
    Func = function()
        Module.unlockWorld("W3")
        task.wait(0.1)
        Module.unlockWorld("W2")
        task.wait(0.1)
        Module.unlockWorld("W1")
    end
})

OtherBox:AddDivider()

OtherBox:AddButton({
    Text = "Bumili ng Pinakamahusay na Palakol",
    Func = function()
        Module.buyPower("Water", 39100000000)
    end
})

local PetBox = Tabs.Other:AddRightGroupbox("Mga Alagang Hayop", "star")

local petData = 900

PetBox:AddInput("PetData", {
    Default = "900",
    Numeric = true,
    Finished = true,
    Text = "Halaga ng Data ng Alagang Hayop",
    Placeholder = "",
    Callback = function(Value)
        petData = tonumber(Value) or 900
    end,
})

PetBox:AddButton({
    Text = "Kumuha ng Pinakamahusay na Alagang Hayop",
    Func = function()
        Module.hatchPet("Exotic", "Celestia", petData)
    end
})