-- Protected Script (Filipino)
-- Script ID: 171e7b3481c648565fe2e1e8dfc5e0b7
-- Created: 2025-10-20T23:12:54.620Z
-- Source: External API
-- Auto-generated by Lua Script Vault


local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

-- Load Core Module from GitHub (replace with your raw GitHub link)
local Module = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/refs/heads/main/Jurrasicscript"))()

-- Initialize connections
Module.initConnections()

-- Create Window
local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Icon = 7734068321,
    NotifySide = "Right",
    ShowCustomCursor = true,
    Size = UDim2.new(0, 500, 0, 400),
})

-- Create Tabs
local Tabs = {
    Main = Window:AddTab("Main", "zap"),
    Amber = Window:AddTab("Amber", "gem"),
    Utility = Window:AddTab("Mga Setting", "wrench"),
}

-- Main Tab - Walkspeed
local MainWalkspeed = Tabs.Main:AddLeftGroupbox("Walkspeed", "activity")
MainWalkspeed:AddToggle("WalkspeedToggle", {
    Text = "Paganahin ang Bilis ng Paglalakad",
    Default = false,
    Callback = function(Value)
        Module.toggleWalkspeed(Value)
    end,
})
MainWalkspeed:AddSlider("WalkspeedSlider", {
    Text = "Halaga ng Bilis ng Paglalakad",
    Default = 16,
    Min = 1,
    Max = 150,
    Rounding = 1,
    Callback = function(Value)
        Module.updateWalkspeed(Value)
    end,
})

-- Main Tab - Animal Farm
local MainNPC = Tabs.Main:AddLeftGroupbox("Sakahan ng hayop", "crosshair")
MainNPC:AddToggle("ESPToggle", {
    Text = "Pangalan ng ESP",
    Default = false,
    Callback = function(Value)
        Module.toggleESP(Value)
    end,
})
MainNPC:AddToggle("HighlightToggle", {
    Text = "ESP Marker",
    Default = false,
    Callback = function(Value)
        Module.toggleHighlight(Value)
    end,
})
MainNPC:AddToggle("NPCTeleportToggle", {
    Text = "Teleport Sa Mga Kambing",
    Default = false,
    Callback = function(Value)
        Module.toggleNPCTeleport(Value)
    end,
})
MainNPC:AddSlider("NPCDistance", {
    Text = "Distansya sa Likod",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.npcBehindDistance = Value
        if Module.State.npcTeleportEnabled and Module.State.currentNPCTarget then
            Module.anchorToNPC(Module.State.currentNPCTarget)
        end
    end,
})
MainNPC:AddButton({
    Text = "Susunod na NPC",
    Func = function()
        if Module.State.npcTeleportEnabled then
            local newTarget = Module.switchToNextNPC()
            if newTarget then
                Module.State.currentNPCTarget = newTarget
                Module.anchorToNPC(Module.State.currentNPCTarget)
            end
        end
    end,
})

-- Main Tab - Boss Farm
local MainBoss = Tabs.Main:AddLeftGroupbox("Boss Farm", "skull")
MainBoss:AddToggle("BossTeleportToggle", {
    Text = "Teleport sa D - Rex Boss",
    Default = false,
    Callback = function(Value)
        Module.toggleBossTeleport(Value)
    end,
})
MainBoss:AddSlider("BossDistance", {
    Text = "Distansya sa Likod",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.bossBehindDistance = Value
        if Module.State.bossTeleportEnabled and Module.State.currentBossTarget then
            Module.anchorToBoss(Module.State.currentBossTarget)
        end
    end,
})
MainBoss:AddButton({
    Text = "Susunod na Boss",
    Func = function()
        if Module.State.bossTeleportEnabled then
            local newTarget = Module.switchToNextBoss()
            if newTarget then
                Module.State.currentBossTarget = newTarget
                Module.anchorToBoss(Module.State.currentBossTarget)
            end
        end
    end,
})

-- Main Tab - Combat
local MainCombat = Tabs.Main:AddRightGroupbox("Alis ng lason", "sword")
MainCombat:AddToggle("AutoAttackToggle", {
    Text = "Awtomatikong Pag - atake",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoAttack(Value)
    end,
})
MainCombat:AddToggle("AutoHeavyToggle", {
    Text = "Combat Mode",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoHeavy(Value)
    end,
})
MainCombat:AddButton({
    Text = "Instant Despawn",
    Func = function()
        Module.executeInstantDespawn()
    end,
})

-- Main Tab - Player Farm
local MainPlayer = Tabs.Main:AddRightGroupbox("Sakahan ng Manlalaro", "users")
MainPlayer:AddToggle("MobileToggle", {
    Text = "Teleport Sa Mga Manlalaro",
    Default = false,
    Callback = function(Value)
        Module.State.teleporting = Value
        if Module.State.teleporting then
            Module.State.playerIndex = 0
            Module.State.currentTarget = Module.getNextTarget()
            if Module.State.currentTarget then
                Module.anchorToPlayer(Module.State.currentTarget)
            end
        else
            Module.State.currentTarget = nil
        end
    end,
})
MainPlayer:AddToggle("TargetMovingToggle", {
    Text = "Target na Paglipat",
    Default = true,
    Callback = function(Value)
        Module.State.targetMovingPlayers = Value
        if not Module.State.targetMovingPlayers and not Module.State.targetStillPlayers then
            Module.State.targetStillPlayers = true
        end
    end,
})
MainPlayer:AddToggle("TargetStillToggle", {
    Text = "Target na Pagtayo",
    Default = true,
    Callback = function(Value)
        Module.State.targetStillPlayers = Value
        if not Module.State.targetMovingPlayers and not Module.State.targetStillPlayers then
            Module.State.targetMovingPlayers = true
        end
    end,
})
MainPlayer:AddSlider("Sa LikodDistansya", {
    Text = "Distansya sa Likod",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.behindDistance = Value
        if Module.State.teleporting and Module.State.currentTarget then
            Module.anchorToPlayer(Module.State.currentTarget)
        end
    end,
})
MainPlayer:AddButton({
    Text = "Susunod na Target",
    Func = function()
        if Module.State.teleporting then
            local validPlayers = Module.getValidPlayers()
            if #validPlayers > 0 then
                Module.State.currentTarget = Module.getNextTarget()
                if Module.State.currentTarget then
                    Module.anchorToPlayer(Module.State.currentTarget)
                end
            end
        end
    end,
})

-- Amber Tab - V1
local AmberV1 = Tabs.Amber:AddLeftGroupbox("Amber V1", "gem")
AmberV1:AddToggle("AmberV1Toggle", {
    Text = "Amber Koleksiyon",
    Default = false,
    Callback = function(Value)
        Module.toggleAmberCollectionSwim(Value)
    end,
})

-- Amber Tab - V2
local AmberV2 = Tabs.Amber:AddRightGroupbox("Amber V2", "zap")
AmberV2:AddToggle("AmberV2Toggle", {
    Text = "Kolektahin Dinosaur barya v2",
    Default = false,
    Callback = function(Value)
        Module.toggleAmberCollection(Value)
    end,
})
AmberV2:AddToggle("AutoSpawnToggle", {
    Text = "Awtomatikong I - revive",
    Default = false,
    Callback = function(Value)
        Module.State.AUTO_SPAWN_ENABLED = Value
        if Value then
            Module.State.lastVisibleGuis = {}
        end
    end,
})
AmberV2:AddDropdown("DinoSelection", {
    Values = Module.allDinosaurs,
    Default = "Gallimimus",
    Text = "Pumili ng Dinosaur",
    Callback = function(Value)
        Module.State.selectedDino = Value
        Module.State.SPAWN_ARGS = { [1] = Value }
    end,
})
AmberV2:AddButton({
    Text = "Pinili ang Manu - manong Spawn",
    Func = function()
        Module.executeSpawn()
    end,
})
AmberV2:AddSlider("AmberTimeout", {
    Text = "(Mga) Timeout",
    Default = 15,
    Min = 5,
    Max = 60,
    Rounding = 1,
    Callback = function(Value)
        Module.State.amberAttemptTimeout = Value
    end,
})

-- Amber Tab - V3 (Premium)
local AmberV3 = Tabs.Amber:AddLeftGroupbox("Mas mahusay na mas mabilis na bersyon ng amber", "zap")
local linkText = "Buy Premium Best DinoCoin Script here:\nhttps://discord.gg/9FWBQnVXCy"
AmberV3:AddLabel(linkText)
AmberV3:AddButton("Copy Link", function()
    if setclipboard then
        setclipboard("https://discord.gg/9FWBQnVXCy")
    elseif toclipboard then
        toclipboard("https://discord.gg/9FWBQnVXCy")
    else
        warn("Clipboard not supported in this executor")
    end
end)

-- Utility Tab - Anti-Void
local UtilityAntiVoid = Tabs.Utility:AddLeftGroupbox("Anti - Void", "shield")
UtilityAntiVoid:AddToggle("AntiVoidToggle", {
    Text = "Kontrahin ang Void",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableAntiVoid()
        else
            Module.disableAntiVoid()
        end
    end,
})

-- Utility Tab - Other
local UtilityOther = Tabs.Utility:AddLeftGroupbox("Iba pa", "zap")
UtilityOther:AddToggle("NoclipToggle", {
    Text = "Noclip",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableNoclip()
        else
            Module.disableNoclip()
        end
    end,
})
UtilityOther:AddToggle("AntiAFKToggle", {
    Text = "Anti - AFK",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableAntiAfk()
        else
            Module.disableAntiAfk()
        end
    end,
})
UtilityOther:AddToggle("StaffWatchToggle", {
    Text = "Maghanap ng isang ban martilyo (staff watch)",
    Default = false,
    Callback = function(Value)
        Module.toggleStaffWatch(Value)
    end,
})

-- Utility Tab - Combat
local Combat = Tabs.Utility:AddRightGroupbox("Alis ng lason", "sword")
Combat:AddToggle("AutoAttackToggle", {
    Text = "Awtomatikong Pag - atake",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoAttack(Value)
    end,
})
Combat:AddToggle("AutoHeavyToggle", {
    Text = "Combat Mode",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoHeavy(Value)
    end,
})
Combat:AddButton({
    Text = "Mabilis na Pagpapakamatay (despawn)",
    Func = function()
        Module.executeInstantDespawn()
    end,
})

-- Utility Tab - UI Settings
local UISettings = Tabs.Utility:AddRightGroupbox("Mga Setting ng UI", "settings")
UISettings:AddToggle("KeybindMenuOpen", {
    Default = Library.KeybindFrame.Visible,
    Text = "Buksan ang Keybind Menu",
    Callback = function(value)
        Library.KeybindFrame.Visible = value
    end,
})
UISettings:AddToggle("ShowCustomCursor", {
    Text = "Iniangkop na Cursor",
    Default = true,
    Callback = function(Value)
        Library.ShowCustomCursor = Value
    end,
})
UISettings:AddDropdown("NotificationSide", {
    Values = { "Left", "Right" },
    Default = "Right",
    Text = "Panig ng Notipikasyon",
    Callback = function(Value)
        Library:SetNotifySide(Value)
    end,
})
UISettings:AddButton("Unload", function()
    Library:Unload()
end)

-- Setup Theme and Save Manager
ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("ComboChronicle")
SaveManager:SetFolder("ComboChronicle")
SaveManager:BuildConfigSection(Tabs.Utility)
ThemeManager:ApplyToTab(Tabs.Utility)

-- Cleanup on close
game:BindToClose(Module.cleanup)
SaveManager:LoadAutoloadConfig()