-- Protected Script (French)
-- Script ID: 421b6dda7665cc534b21ffb25d16037f
-- Created: 2025-10-28T01:37:49.450Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local moduleUrl = "https://raw.githubusercontent.com/checkurasshole/PET/refs/heads/main/skatee"
local Module = loadstring(game:HttpGet(moduleUrl))()

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")

local TimerSystem = {
    playTime = 20 * 60,
    cooldownTime = 10 * 60,
    dataFile = "COMBO_WICK_Timer.txt",
    hwid = game:GetService("RbxAnalyticsService"):GetClientId(),
    currentSession = {
        startTime = 0,
        remainingTime = 0,
        inCooldown = false,
        cooldownStart = 0
    }
}

function TimerSystem:loadData()
    local success, data = pcall(function()
        return readfile(self.dataFile)
    end)
    
    if success and data then
        local decoded = HttpService:JSONDecode(data)
        if decoded[self.hwid] then
            return decoded[self.hwid]
        end
    end
    
    return nil
end

function TimerSystem:saveData()
    local allData = {}
    
    local success, existingData = pcall(function()
        return readfile(self.dataFile)
    end)
    
    if success and existingData then
        allData = HttpService:JSONDecode(existingData)
    end
    
    allData[self.hwid] = {
        remainingTime = self.currentSession.remainingTime,
        inCooldown = self.currentSession.inCooldown,
        cooldownStart = self.currentSession.cooldownStart,
        lastSave = os.time()
    }
    
    writefile(self.dataFile, HttpService:JSONEncode(allData))
end

function TimerSystem:initialize()
    local savedData = self:loadData()
    local currentTime = os.time()
    
    if savedData then
        if savedData.inCooldown then
            local cooldownElapsed = currentTime - savedData.cooldownStart
            if cooldownElapsed >= self.cooldownTime then
                self.currentSession.remainingTime = self.playTime
                self.currentSession.inCooldown = false
                self.currentSession.cooldownStart = 0
            else
                self.currentSession.inCooldown = true
                self.currentSession.cooldownStart = savedData.cooldownStart
                self:showCooldownGUI(self.cooldownTime - cooldownElapsed)
                return false
            end
        else
            self.currentSession.remainingTime = savedData.remainingTime or self.playTime
        end
    else
        self.currentSession.remainingTime = self.playTime
    end
    
    self.currentSession.startTime = currentTime
    return true
end

function TimerSystem:formatTime(seconds)
    local mins = math.floor(seconds / 60)
    local secs = seconds % 60
    return string.format("%02d:%02d", mins, secs)
end

function TimerSystem:showCooldownGUI(remainingCooldown)
    if Library then
        Library:Unload()
    end
    
    local ScreenGui = Instance.new("ScreenGui")
    ScreenGui.Name = "RefroidissementGUI"
    ScreenGui.ResetOnSpawn = false
    ScreenGui.Parent = game:GetService("CoreGui")
    
    local Frame = Instance.new("Frame")
    Frame.Size = UDim2.new(0, 400, 0, 220)
    Frame.Position = UDim2.new(0.5, -200, 0.5, -110)
    Frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    Frame.BorderSizePixel = 0
    Frame.Parent = ScreenGui
    
    local UICorner = Instance.new("UICorner")
    UICorner.CornerRadius = UDim.new(0, 10)
    UICorner.Parent = Frame
    
    local Message = Instance.new("TextLabel")
    Message.Size = UDim2.new(1, -40, 0, 60)
    Message.Position = UDim2.new(0, 20, 0, 20)
    Message.BackgroundTransparency = 1
    Message.Text = "To continue using this script\njoin the discord/youtube:"
    Message.TextColor3 = Color3.fromRGB(200, 200, 200)
    Message.TextSize = 16
    Message.Font = Enum.Font.Gotham
    Message.TextWrapped = true
    Message.TextYAlignment = Enum.TextYAlignment.Top
    Message.Parent = Frame
    
    local DiscordButton = Instance.new("TextButton")
    DiscordButton.Size = UDim2.new(1, -40, 0, 30)
    DiscordButton.Position = UDim2.new(0, 20, 0, 90)
    DiscordButton.BackgroundColor3 = Color3.fromRGB(88, 101, 242)
    DiscordButton.Text = "discord.gg/wyBDqVfn7V"
    DiscordButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    DiscordButton.TextSize = 14
    DiscordButton.Font = Enum.Font.GothamBold
    DiscordButton.Parent = Frame
    
    local DiscordCorner = Instance.new("UICorner")
    DiscordCorner.CornerRadius = UDim.new(0, 6)
    DiscordCorner.Parent = DiscordButton
    
    DiscordButton.MouseButton1Click:Connect(function()
        setclipboard("https://discord.gg/wyBDqVfn7V")
    end)
    
    local YoutubeButton = Instance.new("TextButton")
    YoutubeButton.Size = UDim2.new(1, -40, 0, 30)
    YoutubeButton.Position = UDim2.new(0, 20, 0, 130)
    YoutubeButton.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
    YoutubeButton.Text = "youtube.com/@COMBO_WICK"
    YoutubeButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    YoutubeButton.TextSize = 14
    YoutubeButton.Font = Enum.Font.GothamBold
    YoutubeButton.Parent = Frame
    
    local YoutubeCorner = Instance.new("UICorner")
    YoutubeCorner.CornerRadius = UDim.new(0, 6)
    YoutubeCorner.Parent = YoutubeButton
    
    YoutubeButton.MouseButton1Click:Connect(function()
        setclipboard("https://www.youtube.com/@COMBO_WICK/videos")
    end)
    
    local TimerLabel = Instance.new("TextLabel")
    TimerLabel.Size = UDim2.new(1, 0, 0, 30)
    TimerLabel.Position = UDim2.new(0, 0, 0, 170)
    TimerLabel.BackgroundTransparency = 1
    TimerLabel.Text = "Time left: " .. self:formatTime(remainingCooldown)
    TimerLabel.TextColor3 = Color3.fromRGB(255, 100, 100)
    TimerLabel.TextSize = 18
    TimerLabel.Font = Enum.Font.GothamBold
    TimerLabel.Parent = Frame
    
    task.spawn(function()
        local timeLeft = remainingCooldown
        while timeLeft > 0 do
            task.wait(1)
            timeLeft = timeLeft - 1
            TimerLabel.Text = "Time left: " .. self:formatTime(timeLeft)
        end
        
        ScreenGui:Destroy()
        
        self.currentSession.remainingTime = self.playTime
        self.currentSession.inCooldown = false
        self.currentSession.cooldownStart = 0
        self:saveData()
        
        loadstring(game:HttpGet(moduleUrl))()
    end)
end

function TimerSystem:startTimer()
    task.spawn(function()
        while self.currentSession.remainingTime > 0 do
            task.wait(1)
            self.currentSession.remainingTime = self.currentSession.remainingTime - 1
            
            if self.currentSession.remainingTime % 30 == 0 then
                self:saveData()
            end
        end
        
        self.currentSession.inCooldown = true
        self.currentSession.cooldownStart = os.time()
        self:saveData()
        
        self:showCooldownGUI(self.cooldownTime)
    end)
end

if not TimerSystem:initialize() then
    return
end

TimerSystem:startTimer()

local Options = Library.Options
local Toggles = Library.Toggles

local Window = Library:CreateWindow({
    Title = "C'est pas vrai.",
    Footer = "Version 1.0.0",
    NotifySide = "Right",
    ShowCustomCursor = false,
    Size = UDim2.new(0, 500, 0, 400),
})

local Tabs = {
    Main = Window:AddTab("Principales", "home"),
    Combat = Window:AddTab("Lutte", "sword"),
    Player = Window:AddTab("Joueur", "user"),
    Settings = Window:AddTab("Paramètres", "settings"),
}

Module.setupCombatKeybind()
Module.setupMovementLoop()

local EquipmentGroup = Tabs.Main:AddLeftGroupbox("Matériel", "sword")

EquipmentGroup:AddToggle("AutoEquipBest", {
    Text = "Équiper automatiquement les meilleurs articles",
    Default = false,
})

EquipmentGroup:AddSlider("EquipIntervalle", {
    Text = "Temps entre les équipements",
    Default = 60,
    Min = 10,
    Max = 300,
    Rounding = 0,
    Suffix = " seconds",
})

EquipmentGroup:AddButton({
    Text = "Equipez les meilleurs articles maintenant",
    Func = function()
        Module.equipBestItems()
        Library:Notify({
            Title = "Matériel",
            Description = "Best items equipped successfully",
            Time = 3,
        })
    end,
})

task.spawn(function()
    while task.wait(Options.EquipInterval.Value or 60) do
        if Library.Unloaded then break end
        if Toggles.AutoEquipBest.Value then
            Module.equipBestItems()
        end
    end
end)

EquipmentGroup:AddDivider()

local PetGroup = Tabs.Main:AddLeftGroupbox("Animaux de compagnie", "dog")

PetGroup:AddButton({
    Text = "Équiper les meilleurs animaux de compagnie",
    Func = function()
        local maxPets = Module.equipBestPets()
        Library:Notify({
            Title = "Animaux de compagnie",
            Description = "Best " .. maxPets .. " pets equipped",
            Time = 3,
        })
    end,
})

PetGroup:AddButton({
    Text = "Supprimer tous les animaux de compagnie",
    Func = function()
        Module.removeAllPets()
        Library:Notify({
            Title = "Animaux de compagnie",
            Description = "All pets removed",
            Time = 3,
        })
    end,
})

PetGroup:AddDivider()

local EggGroup = Tabs.Main:AddLeftGroupbox("Œufs", "egg")

EggGroup:AddDropdown("EggSelection", {
    Values = {"Egg1", "Egg2", "Egg3", "Egg4"},
    Default = 1,
    Multi = false,
    Text = "Sélectionner le type d'oeuf",
})

EggGroup:AddToggle("AutoBuyEgg", {
    Text = "Achat automatique d'oeufs",
    Default = false,
})

EggGroup:AddSlider("EggBuyIntervalle", {
    Text = "Temps entre les achats",
    Default = 1,
    Min = 0.1,
    Max = 10,
    Rounding = 1,
    Suffix = " seconds",
})

task.spawn(function()
    while task.wait(Options.EggBuyInterval.Value or 1) do
        if Library.Unloaded then break end
        if Toggles.AutoBuyEgg.Value then
            local selectedEgg = Options.EggSelection.Value
            if selectedEgg then
                Module.buyEgg(selectedEgg)
            end
        end
    end
end)

local StatsGroup = Tabs.Main:AddRightGroupbox("Statistiques", "trending-up")

StatsGroup:AddToggle("AutoAllocateDamage", {
    Text = "Ajouter automatiquement des statistiques sur les dommages",
    Default = false,
})

StatsGroup:AddSlider("Points de dommage", {
    Text = "Montant des dommages",
    Default = 0,
    Min = 0,
    Max = 100,
    Rounding = 0,
})

StatsGroup:AddToggle("Auto AllocateHealth", {
    Text = "Auto Ajouter des statistiques de santé",
    Default = false,
})

StatsGroup:AddSlider("Points de santé", {
    Text = "Quantité pour la santé",
    Default = 0,
    Min = 0,
    Max = 100,
    Rounding = 0,
})

StatsGroup:AddToggle("AutoAllocateDefense", {
    Text = "Ajout automatique de statistiques de défense",
    Default = false,
})

StatsGroup:AddSlider("Points de défense", {
    Text = "Montant de la défense",
    Default = 0,
    Min = 0,
    Max = 100,
    Rounding = 0,
})

task.spawn(function()
    while task.wait(1) do
        if Library.Unloaded then break end
        
        if Toggles.AutoAllocateDamage.Value then
            Module.addStatPoints("Damage", Options.DamagePoints.Value)
            task.wait(0.1)
        end
        
        if Toggles.AutoAllocateHealth.Value then
            Module.addStatPoints("Health", Options.HealthPoints.Value)
            task.wait(0.1)
        end
        
        if Toggles.AutoAllocateDefense.Value then
            Module.addStatPoints("Defense", Options.DefensePoints.Value)
            task.wait(0.1)
        end
    end
end)

StatsGroup:AddButton({
    Text = "Réinitialiser tous les Statistiques",
    Func = function()
        Module.resetStats()
        Library:Notify({
            Title = "Statistiques",
            Description = "All stats have been reset",
            Time = 3,
        })
    end,
})

StatsGroup:AddDivider()

local RebirthGroup = Tabs.Main:AddRightGroupbox("Renaissance", "refresh-cw")

RebirthGroup:AddToggle("Autorenaissance", {
    Text = "Renaissance automatique",
    Default = false,
})

RebirthGroup:AddSlider("RenaissanceIntervalle", {
    Text = "Temps entre les renaissances",
    Default = 10,
    Min = 1,
    Max = 300,
    Rounding = 0,
    Suffix = " seconds",
})

RebirthGroup:AddButton({
    Text = "Renaissance maintenant",
    Func = function()
        Module.doRebirth()
        Library:Notify({
            Title = "Renaissance",
            Description = "Rebirth completed",
            Time = 3,
        })
    end,
})

task.spawn(function()
    while task.wait(Options.RebirthInterval.Value or 10) do
        if Library.Unloaded then break end
        if Toggles.AutoRebirth.Value then
            Module.doRebirth()
        end
    end
end)

local QuestGroup = Tabs.Main:AddRightGroupbox("Quests", "scroll")

QuestGroup:AddButton({
    Text = "Réclamation Toutes les quêtes terminées",
    Func = function()
        local questsClaimed = Module.claimAllQuests()
        Library:Notify({
            Title = "Quests",
            Description = questsClaimed > 0 and ("Claimed " .. questsClaimed .. " quests") or "No quests available to claim",
            Time = 3,
        })
    end,
})

QuestGroup:AddToggle("AutoClaimQuests", {
    Text = "Quests d'auto-requête",
    Default = false,
})

QuestGroup:AddSlider("AutoClaimInterval", {
    Text = "Temps écoulé entre les réclamations",
    Default = 60,
    Min = 10,
    Max = 300,
    Rounding = 0,
    Suffix = " seconds",
})

task.spawn(function()
    while task.wait(Options.AutoClaimInterval.Value or 60) do
        if Library.Unloaded then break end
        
        if Toggles.AutoClaimQuests.Value then
            local questsClaimed = Module.claimAllQuests()
            
            if questsClaimed > 0 then
                Library:Notify({
                    Title = "Système Auto Quest",
                    Description = "Claimed " .. questsClaimed .. " quests",
                    Time = 3,
                })
            end
        end
    end
end)

local AttackGroup = Tabs.Combat:AddLeftGroupbox("Attaque automatique")

AttackGroup:AddToggle("AutoAttack", {
    Text = "Activer l'attaque automatique",
    Default = false,
    Callback = function(Value)
        Module.Data.autoAttackEnabled = Value
        if Value then
            Module.startAutoAttack()
        end
    end,
})

AttackGroup:AddSlider("AttaqueSpeed", {
    Text = "Vitesse d'attaque",
    Default = 0.1,
    Min = 0.01,
    Max = 1,
    Rounding = 2,
    Compact = false,
    Suffix = " seconds",
    Callback = function(Value)
        Module.Data.attackSpeed = Value
    end,
})

AttackGroup:AddSlider("Rang d'attaque", {
    Text = "Portée d'attaque",
    Default = 50,
    Min = 20,
    Max = 200,
    Rounding = 0,
    Compact = false,
    Callback = function(Value)
        Module.Data.attackRange = Value
    end,
})

local VisualGroup = Tabs.Combat:AddRightGroupbox("Affichage visuel")

VisualGroup:AddToggle("GammeCircle", {
    Text = "Afficher le cercle de portée d'attaque",
    Default = false,
    Callback = function(Value)
        Module.Data.rangeCircleEnabled = Value
        if Value then
            Module.createRangeCircle()
        else
            Module.removeRangeCircle()
        end
    end,
})

VisualGroup:AddDivider()

local AntiDetectionGroup = Tabs.Combat:AddRightGroupbox("Système antidétection")

Module.Data.statusLabel = AntiDetectionGroup:AddLabel("Status: Inactive")

AntiDetectionGroup:AddButton("Toggle Combat Mode", function()
    Module.toggleCombat()
end)

AntiDetectionGroup:AddLabel("Important: Press 5 times\nMake sure status shows Inactive")

AntiDetectionGroup:AddButton("Kill Character", function()
    Module.killCharacter()
end)

local MovementGroup = Tabs.Player:AddLeftGroupbox("Contrôles des mouvements")

MovementGroup:AddToggle("Vitesse de marche", {
    Text = "Activer la vitesse de marche",
    Default = false,
    Callback = function(Value)
        Module.Data.walkSpeedEnabled = Value
        if not Value then
            local char = game.Players.LocalPlayer.Character
            if char and char:FindFirstChild("Humanoid") then
                char.Humanoid.WalkSpeed = 16
            end
        end
    end,
})

MovementGroup:AddSlider("WalkSpeedValue", {
    Text = "Valeur de vitesse de marche",
    Default = 16,
    Min = 16,
    Max = 200,
    Rounding = 0,
    Compact = false,
    Callback = function(Value)
        Module.Data.walkSpeedValue = Value
    end,
})

MovementGroup:AddToggle("Puissance de saut", {
    Text = "Activer la puissance de saut",
    Default = false,
    Callback = function(Value)
        Module.Data.jumpPowerEnabled = Value
        if not Value then
            local char = game.Players.LocalPlayer.Character
            if char and char:FindFirstChild("Humanoid") then
                char.Humanoid.JumpPower = 50
            end
        end
    end,
})

MovementGroup:AddSlider("Valeur de JumpPower", {
    Text = "Valeur de la puissance de saut",
    Default = 50,
    Min = 50,
    Max = 300,
    Rounding = 0,
    Compact = false,
    Callback = function(Value)
        Module.Data.jumpPowerValue = Value
    end,
})

MovementGroup:AddDivider()

MovementGroup:AddToggle("Voler", {
    Text = "Activer le mode de vol",
    Default = false,
    Callback = function(Value)
        Module.Data.flyEnabled = Value
        if Value then
            Module.startFly()
        else
            Module.stopFly()
        end
    end,
})

MovementGroup:AddSlider("FlySpeed", {
    Text = "Valeur de la vitesse de vol",
    Default = 50,
    Min = 10,
    Max = 200,
    Rounding = 0,
    Compact = false,
    Callback = function(Value)
        Module.Data.flySpeed = Value
    end,
})

MovementGroup:AddLabel("Controls: W A S D to move around")
MovementGroup:AddLabel("Space to go up, Shift to go down")

MovementGroup:AddDivider()

MovementGroup:AddToggle("Noclip", {
    Text = "Activer le mode Noclip",
    Default = false,
    Callback = function(Value)
        Module.Data.noclipEnabled = Value
        if Value then
            Module.startNoclip()
        else
            Module.stopNoclip()
        end
    end,
})

local MenuGroup = Tabs.Settings:AddLeftGroupbox("Contrôles de menus")

MenuGroup:AddLabel("Menu Open Key"):AddKeyPicker("MenuKeybind", {
    Default = "RightShift",
    NoUI = true,
    Text = "Keybind du menu"
})

MenuGroup:AddButton("Close Script", function()
    TimerSystem:saveData()
    Library:Unload()
end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()

ThemeManager:SetFolder("COMBO_WICK")
SaveManager:SetFolder("COMBO_WICK/Config")

SaveManager:BuildConfigSection(Tabs.Settings)
ThemeManager:ApplyToTab(Tabs.Settings)

Library:Notify({
    Title = "C'est pas vrai.",
    Description = "Script loaded successfully",
    Time = 5,
})

Library:OnUnload(function()
    TimerSystem:saveData()
    Module.cleanup()
end)

Module.toggleDetection(true)