-- Spanish Translation
-- Script ID: 481bf724005ae1d7c6a9fd1d23fe8539
-- Updated: 2026-05-20T18:30:31.024Z
-- Auto-generated by Lua Script Vault

-- Main Script
local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ForceCheckbox = false
Library.ShowToggleFrameInKeybinds = true

local Window = Library:CreateWindow({
	Title = "COMBOWICK",
	Footer = "v2.0",
	Icon = "star",
	NotifySide = "Right",
	ShowCustomCursor = false,
	Size = UDim2.fromOffset(300, 500),
})

local Tabs = {
	Main = Window:AddTab("Main", "sword"),
	["Ajustes de la UI"] = Window:AddTab("Ajustes de la UI", "settings"),
}

local CombatGroup  = Tabs.Main:AddLeftGroupbox("Combate ", "zap")
local ESPGroup     = Tabs.Main:AddLeftGroupbox("ESP", "eye")
local GearGroup    = Tabs.Main:AddLeftGroupbox("Engranajes", "box")
local InvisGroup   = Tabs.Main:AddLeftGroupbox("Inmortal ", "eye")
local UpgradeGroup = Tabs.Main:AddRightGroupbox("Mejoras ", "zap")
local WaveGroup    = Tabs.Main:AddRightGroupbox("Ola", "waves")
local MiscGroup    = Tabs.Main:AddRightGroupbox("Varios ", "map-pin")
local InfoGroup    = Tabs.Main:AddRightGroupbox("Info ", "info")

local Mod = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/main/SurviveZombieArenaModule"))()(Library, Toggles, Options)

local countLabel    = InfoGroup:AddLabel("Zombis: 0")
local estCredLabel  = InfoGroup:AddLabel("Créditos estimados: 0")
local sessCredLabel = InfoGroup:AddLabel("Sesión: 0")

task.spawn(function()
	while true do
		task.wait(0.5)
		countLabel:SetText("Zombies: " .. Mod.getZombieCount())
		estCredLabel:SetText("Est. Credits: " .. tostring(Mod.getEstCredits()))
		sessCredLabel:SetText("Session: " .. tostring(Mod.sessionTotal))
		Mod.updateESP()
	end
end)

CombatGroup:AddToggle("AutoKill", {
	Text    = "Disparo automático",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.InstaKill.Value then Toggles.InstaKill:SetValue(false) end
			Mod.startAutoKill()
		else
			Mod.stopAutoKill()
		end
	end,
})
CombatGroup:AddSlider("AutoKillDelay", {
	Text = "Retardo del disparo automático (segundos)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddToggle("InstaKill", {
	Text    = "Matar al instante",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.AutoKill.Value then Toggles.AutoKill:SetValue(false) end
			Mod.startInstaKill()
		else
			Mod.stopInstaKill()
		end
	end,
})
CombatGroup:AddSlider("InstaKillDamage", {
	Text = "Damage", Default = 999999999, Min = 1000, Max = 999999999, Rounding = 0,
})
CombatGroup:AddSlider("InstaKillDelay", {
	Text = "Retardo (segundos)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddButton({
	Text = "Matar a todos", DoubleClick = false,
	Func = function() Mod.killAll() end,
})

ESPGroup:AddToggle("ZombieESP", {
	Text    = "Resaltar zombis",
	Default = false,
	Callback = function(Value) if not Value then Mod.clearESP() end end,
})
ESPGroup:AddDropdown("ESPColor", {
	Values = { "Red", "Orange", "Yellow", "Purple" }, Default = "Red", Text = "Color",
	Callback = function(Value) Mod.applyESPColor(Mod.ESP_COLORS[Value] or Mod.ESP_COLORS.Red) end,
})

local GEARS = {
	"Landmine", "AutoTurret", "Barricade", "Bunker", "Drone",
	"FlamethrowerTurret", "HealingStation", "LaserTurret", "MendingTower",
	"Molotov", "ShockwaveMine", "Shuriken", "Spikes", "SteelBarricade", "VanguardTurret",
}
GearGroup:AddDropdown("GearBuySelect", {
	Values = GEARS, Default = { "Landmine" }, Text = "Seleccionar engranajes", Multi = true,
})
GearGroup:AddToggle("AutoBuyGear", {
	Text    = "Compra automática",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startAutoBuy() else Mod.stopAutoBuy() end
	end,
})
GearGroup:AddSlider("GearBuyDelay", {
	Text = "Retrasar compra(s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

InvisGroup:AddToggle("InvisEnabled", {
	Text    = "Inmortal ",
	Default = false,
	Callback = function(Value)
		if Value then
			Mod.setInvisTransparency(Options.InvisTransparency.Value / 100) -- apply current slider value immediately
			Mod.enableInvisibility()
		else
			Mod.disableInvisibility()
		end
	end,
})

InvisGroup:AddSlider("InvisTransparency", {
	Text = "Transparencia ", Default = 0, Min = 0, Max = 100, Rounding = 0,
	Callback = function(value)
		Mod.setInvisTransparency(value / 100)
	end,
})
InvisGroup:AddLabel("Tecla de Inmortal"):AddKeyPicker("Keybind_Invis", {
	Default  = "Z",
	Mode     = "Press",
	Text     = "Activar/desactivar invisibilidad",
	NoUI     = false,
	Callback = function()
		Toggles.InvisEnabled:SetValue(not Toggles.InvisEnabled.Value)
	end,
})

UpgradeGroup:AddToggle("AutoWeaponUpgrade", {
	Text    = "Mejora automática de arma",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startWeaponUpgrade() else Mod.stopWeaponUpgrade() end
	end,
})
UpgradeGroup:AddSlider("WeaponUpgradeDelay", {
	Text = "Retardo (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})
UpgradeGroup:AddToggle("AutoHealthUpgrade", {
	Text    = "Mejora automática de salud",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startHealthUpgrade() else Mod.stopHealthUpgrade() end
	end,
})
UpgradeGroup:AddSlider("HealthUpgradeDelay", {
	Text = "Retardo (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

WaveGroup:AddToggle("AutoSkipWave", {
	Text    = "Voto de salto automático",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startSkip() else Mod.stopSkip() end
	end,
})
WaveGroup:AddButton({
	Text = "Saltar las oleadas al instante", DoubleClick = false,
	Func = function()
		Mod.instantSkip()
		if not Toggles.EnableFly.Value then Toggles.EnableFly:SetValue(true) end
	end,
})
WaveGroup:AddToggle("AutoDoubleCredits", {
	Text    = "Créditos dobles automáticos",
	Default = false,
})

MiscGroup:AddToggle("AntiAFK", {
	Text    = "Antiausencia (AFK)",
	Default = false,
	Callback = function(Value) if Value then Mod.enableAntiAFK() end end,
})
MiscGroup:AddToggle("Noclip", {
	Text    = "Noclip",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startNoclip() else Mod.stopNoclip() end
	end,
})
MiscGroup:AddSlider("WalkSpeed", {
	Text = "Velocidad al caminar", Default = 16, Min = 16, Max = 150, Rounding = 0,
	Callback = function(Value) Mod.setWalkSpeed(Value) end,
})
MiscGroup:AddToggle("EnableFly", {
	Text    = "Fly",
	Default = false,
	Callback = function(Value) if Value then Mod.startFly() else Mod.stopFly() end end,
})
MiscGroup:AddSlider("FlyHeight", {
	Text = "Altura de vuelo", Default = 0, Min = 0, Max = 150, Rounding = 0,
})

local MenuGroup = Tabs["Ajustes de la UI"]:AddLeftGroupbox("Menu", "wrench")
MenuGroup:AddToggle("KeybindMenuOpen", {
	Default = Library.KeybindFrame.Visible, Text = "Menú de teclas",
	Callback = function(value) Library.KeybindFrame.Visible = value end,
})
MenuGroup:AddDropdown("NotificationSide", {
	Values = { "Left", "Right" }, Default = "Right", Text = "Lado de las notificaciones",
	Callback = function(Value) Library:SetNotifySide(Value) end,
})
MenuGroup:AddDropdown("DPIDropdown", {
	Values = { "50%", "75%", "100%", "125%", "150%", "175%", "200%" }, Default = "100%", Text = "Escala DPI",
	Callback = function(Value)
		Value = Value:gsub("%%", "")
		Library:SetDPIScale(tonumber(Value))
	end,
})
MenuGroup:AddSlider("UICornerSlider", {
	Text = "Radio de las esquinas", Default = Library.CornerRadius, Min = 0, Max = 20, Rounding = 0,
	Callback = function(value) Window:SetCornerRadius(value) end,
})
MenuGroup:AddLabel("Tecla del menú"):AddKeyPicker("MenuKeybind", {
	Default = "RightShift", NoUI = true, Text = "Tecla del menú",
})
MenuGroup:AddButton("Unload", function() Library:Unload() end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("COMBOWICK")
SaveManager:SetFolder("COMBOWICK/zombie-game")
SaveManager:BuildConfigSection(Tabs["Ajustes de la UI"])
ThemeManager:ApplyToTab(Tabs["Ajustes de la UI"])
SaveManager:LoadAutoloadConfig()
Library:SetDPIScale(100)

if _G.COMBOWICK_KEY then
	_G.COMBOWICK_FREE = false
	_G.COMBOWICK_ACTIVE = nil
	_G.COMBOWICK_KEY = false
end

if _G.COMBOWICK_FREE then
	_G.COMBOWICK_ACTIVE = true
	task.spawn(function()
		repeat task.wait(1) until _G.COMBOWICK_ACTIVE == false
		Mod.disableAllFeatures()
		Mod.showExpiredPopup(function() Library:Unload() end)
	end)
end