-- Thai Translation
-- Script ID: 4a646ede8a3a63edb23a253d2eff6cd1
-- Created: 2026-01-13T17:33:50.141Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local LocalPlayer = Players.LocalPlayer

local AutoRebirth = false
local AutoClaimRewards = false
local AutoBuyEgg = false
local SelectedEgg = "BasicEgg"
local WinAmount = 100

local EggNames = {
    ["Basic Egg"] = "BasicEgg",
    ["Fairy Egg"] = "FairyEgg",
    ["Dragon Egg"] = "DragonEgg",
    ["Computer Egg (15M)"] = "ComputerEgg",
    ["Galaxy Egg (80M)"] = "GalaxyEgg",
    ["Evil Egg (250M)"] = "EvilEgg",
    ["Pirate Egg (3B)"] = "PirateEgg",
    ["Jungle Egg (20B)"] = "JungleEgg",
    ["Underworld Egg (60B)"] = "UnderworldEgg"
}

local Window = Library:CreateWindow({
    Title = "combo_wick",
    Footer = "คุณสมบัติทั้งหมด",
    ShowCustomCursor = false,
    Size = UDim2.new(0, 400, 0, 450),
})

local MainTab = Window:AddTab("หลัก", "home")

local WinsGroup = MainTab:AddLeftGroupbox("รางวัล")
local EggGroup = MainTab:AddRightGroupbox("ซื้อ")
local SettingsGroup = MainTab:AddLeftGroupbox("ตัวเลือก")

WinsGroup:AddSlider("WinAmount", {Text = "จำนวนรวม", Default = 100, Min = 1, Max = 1000, Rounding = 0, Callback = function(v) WinAmount = v end})

WinsGroup:AddButton({Text = "รางวัลไม่จำกัด", Func = function()
    task.spawn(function()
        local Remote = ReplicatedStorage:WaitForChild("RemoteEvents"):WaitForChild("ProgressionControllerEvents"):WaitForChild("RewardWins")
        local args = {}
        for i = 1, WinAmount do
            task.spawn(function()
                pcall(function()
                    Remote:FireServer(unpack(args))
                end)
            end)
        end

    end)
end})

WinsGroup:AddDivider()

WinsGroup:AddToggle("AutoRebirth", {Text = "เกิดใหม่โดยอัตโนมัติ", Default = false, Callback = function(v)
    AutoRebirth = v
    if AutoRebirth then
        task.spawn(function()
            while AutoRebirth do
                pcall(function()
                    local args = {}
                    ReplicatedStorage:WaitForChild("RemoteEvents"):WaitForChild("RebirthEvents"):WaitForChild("PurchaseRebirth"):InvokeServer(unpack(args))
                end)
                task.wait(1)
            end
        end)
    end
end})

WinsGroup:AddButton({Text = "เกิดใหม่หนึ่งครั้ง", Func = function()
    pcall(function()
        local args = {}
        ReplicatedStorage:WaitForChild("RemoteEvents"):WaitForChild("RebirthEvents"):WaitForChild("PurchaseRebirth"):InvokeServer(unpack(args))

    end)
end})

WinsGroup:AddDivider()

WinsGroup:AddToggle("AutoClaim", {Text = "รับรางวัลอัตโนมัติ", Default = false, Callback = function(v)
    AutoClaimRewards = v
    if AutoClaimRewards then
        task.spawn(function()
            while AutoClaimRewards do
                for i = 1, 12 do
                    if not AutoClaimRewards then break end
                    pcall(function()
                        local args = {[1] = i}
                        ReplicatedStorage:WaitForChild("RemoteEvents"):WaitForChild("FreeGiftEvents"):WaitForChild("ClaimReward"):InvokeServer(unpack(args))
                    end)
                    task.wait(0.1)
                end
                task.wait(60)
            end
        end)
    end
end})

EggGroup:AddDropdown("EggSelect", {
    Text = "เลือกไข่",
    Default = 1,
    Values = {
        "Basic Egg",
        "Fairy Egg",
        "Dragon Egg",
        "Computer Egg (15M)",
        "Galaxy Egg (80M)",
        "Evil Egg (250M)",
        "Pirate Egg (3B)",
        "Jungle Egg (20B)",
        "Underworld Egg (60B)"
    },
    Callback = function(v)
        SelectedEgg = EggNames[v]
    end
})

EggGroup:AddToggle("AutoBuyEgg", {Text = "ซื้ออัตโนมัติ", Default = false, Callback = function(v)
    AutoBuyEgg = v
    if AutoBuyEgg then
        task.spawn(function()
            while AutoBuyEgg do
                pcall(function()
                    local args = {
                        [1] = SelectedEgg,
                        [2] = false,
                        [3] = false,
                        [4] = {}
                    }
                    ReplicatedStorage:WaitForChild("RemoteEvents"):WaitForChild("PetShopHandlerEvents"):WaitForChild("AttemptPurchase"):InvokeServer(unpack(args))
                end)
                task.wait(0.5)
            end
        end)
    end
end})

EggGroup:AddButton({Text = "ซื้อครั้งเดียว", Func = function()
    pcall(function()
        local args = {
            [1] = SelectedEgg,
            [2] = false,
            [3] = false,
            [4] = {}
        }
        ReplicatedStorage:WaitForChild("RemoteEvents"):WaitForChild("PetShopHandlerEvents"):WaitForChild("AttemptPurchase"):InvokeServer(unpack(args))

    end)
end})

SettingsGroup:AddButton({Text = "ปลดโหลดสคริปต์", Func = function()
    AutoRebirth = false
    AutoClaimRewards = false
    AutoBuyEgg = false
    Library:Unload()
end})