-- Thai Translation
-- Script ID: 4fdc8c78b36a90ce897d54943769e8bb
-- Updated: 2025-12-18T18:10:18.087Z
-- Auto-generated by Lua Script Vault

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local PlayerModule = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/hOL/refs/heads/main/moduleeeeeeee"))()
local GameModule = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/Trt/refs/heads/main/www"))() -- Replace with your GameModule URL

local Options = Library.Options
local Toggles = Library.Toggles

Library.ShowCustomCursor = false

local Window = Library:CreateWindow({
	Title = "COMBO_WICK",
	Footer = "v1.1",
	Icon = star,
	NotifySide = "Right",
	ShowCustomCursor = false,
	Size = UDim2.new(0, 500, 0, 450),
	Position = UDim2.new(0.5, -250, 0.5, -225),
})

local Tabs = {
	Main = Window:AddTab("หลัก", "gem"),
	Combat = Window:AddTab("สู้", "sword"),
	Player = Window:AddTab("ผู้เล่น", "user"),
	["UI Settings"] = Window:AddTab("การตั้งค่า UI", "settings"),
}

-- MINING TAB
local MiningGroupBox = Tabs.Main:AddLeftGroupbox("ทำเหมือง", "pickaxe")

MiningGroupBox:AddDropdown("OreType", {
	Values = { 
		"Pebble", "Rock", "Boulder",
		"Basalt Rock", "Basalt Core", "Basalt Vein", "Volcanic Rock"
	},
	Default = 1,
	Text = "เลือกประเภทแร่",
	Callback = function(Value)
		GameModule.SelectedOreType = Value
		GameModule.clearSkippedOres()
	end,
})

MiningGroupBox:AddDivider()

MiningGroupBox:AddToggle("ทำฟาร์มอัตโนมัติ", {
	Text = "เปิดใช้งานการขุดอัตโนมัติ",
	Default = false,
	Callback = function(value)
		if value then
			GameModule.clearSkippedOres()
			GameModule.startAutoMining()
		else
			GameModule.stopAutoMining()
		end
	end,
})

local SettingsGroupBox = Tabs.Main:AddRightGroupbox("การตั้งค่า", "settings")

SettingsGroupBox:AddSlider("MiningSpeed", {
	Text = "ความเร็ว",
	Default = 50,
	Min = 1,
	Max = 50,
	Rounding = 0,
	Callback = function(Value)
		GameModule.MiningSpeed = Value
	end,
})

SettingsGroupBox:AddSlider("OreTeleportOffset", {
	Text = "ความสูงเหนือแร่",
	Default = 5,
	Min = 5,
	Max = 50,
	Rounding = 1,
	Callback = function(Value)
		GameModule.OreTeleportOffset = Value
	end,
})

SettingsGroupBox:AddDivider()

SettingsGroupBox:AddToggle("EnableAntiStuck", {
	Text = "รีเซ็ตตำแหน่ง",
	Default = true,
	Callback = function(value)
		GameModule.EnableAntiStuck = value
	end,
})

SettingsGroupBox:AddSlider("StuckCheckDelay", {
	Text = "",
	Default = 3,
	Min = 1,
	Max = 10,
	Rounding = 1,
	Callback = function(Value)
		GameModule.StuckCheckDelay = Value
	end,
})

-- COMBAT TAB
local CombatGroupBox = Tabs.Combat:AddLeftGroupbox("ล่าศัตรู", "sword")

CombatGroupBox:AddDropdown("MobType", {
	Values = GameModule.MobTypes,
	Default = 1,
	Text = "เลือกศัตรู",
	Callback = function(Value)
		GameModule.SelectedMobType = Value
		GameModule.clearSkippedMobs()
	end,
})

CombatGroupBox:AddDivider()

CombatGroupBox:AddToggle("AutoAttack", {
	Text = "เปิดใช้งานการโจมตีอัตโนมัติ",
	Default = false,
	Callback = function(value)
		if value then
			GameModule.clearSkippedMobs()
			GameModule.startAutoAttack()
		else
			GameModule.stopAutoAttack()
		end
	end,
})

local CombatSettings = Tabs.Combat:AddRightGroupbox("การตั้งค่าการต่อสู้", "settings")

CombatSettings:AddSlider("MoveSpeed", {
	Text = "ความเร็ว",
	Default = 25,
	Min = 1,
	Max = 50,
	Rounding = 0,
	Callback = function(Value)
		GameModule.MoveSpeed = Value
	end,
})

CombatSettings:AddSlider("MobTeleportOffset", {
	Text = "ความสูงจากศัตรู",
	Default = 15,
	Min = 5,
	Max = 50,
	Rounding = 1,
	Callback = function(Value)
		GameModule.MobTeleportOffset = Value
	end,
})

CombatSettings:AddDivider()

CombatSettings:AddToggle("EnableAntiStuck", {
	Text = "รีเซ็ตตำแหน่ง",
	Default = true,
	Callback = function(value)
		GameModule.CombatEnableAntiStuck = value
	end,
})

CombatSettings:AddSlider("StuckCheckDelay", {
	Text = "",
	Default = 2,
	Min = 1,
	Max = 10,
	Rounding = 1,
	Callback = function(Value)
		GameModule.CombatStuckCheckDelay = Value
	end,
})

CombatSettings:AddDivider()

local PotionsGroupBox = Tabs.Combat:AddLeftGroupbox("น้ำยาอัตโนมัติ")

PotionsGroupBox:AddToggle("AutoDamagePotion", {
	Text = "ยาความเสียหายอัตโนมัติ",
	Default = false,
	Callback = function(value)
		GameModule.AutoUsePotions.Damage = value
		if value then
			GameModule.startAutoPotions()
		end
	end,
})

PotionsGroupBox:AddToggle("AutoSpeedPotion", {
	Text = "น้ำยาอีลิกเซอร์ที่สร้างความเสียหาย",
	Default = false,
	Callback = function(value)
		GameModule.AutoUsePotions.Speed = value
		if value then
			GameModule.startAutoPotions()
		end
	end,
})

PotionsGroupBox:AddToggle("AutoHealthPotion", {
	Text = "น้ำยาอีลิกเซอร์เพื่อสุขภาพ",
	Default = false,
	Callback = function(value)
		GameModule.AutoUsePotions.Health = value
		if value then
			GameModule.startAutoPotions()
		end
	end,
})

PotionsGroupBox:AddToggle("AutoMinerPotion", {
	Text = "น้ำยาอีลิกเซอร์สำหรับคนงานเหมือง",
	Default = false,
	Callback = function(value)
		GameModule.AutoUsePotions.Miner = value
		if value then
			GameModule.startAutoPotions()
		end
	end,
})

PotionsGroupBox:AddToggle("AutoLuckPotion", {
	Text = "ยานำโชคอัตโนมัติ",
	Default = false,
	Callback = function(value)
		GameModule.AutoUsePotions.Luck = value
		if value then
			GameModule.startAutoPotions()
		end
	end,
})

-- PLAYER TAB
local PlayerGroupBox = Tabs.Player:AddLeftGroupbox("การเคลื่อนที่")

PlayerGroupBox:AddToggle("แมลงวัน", {
	Text = "โหมดการบิน",
	Default = false,
	Callback = function(value)
		PlayerModule.FlyEnabled = value
		if value then
			PlayerModule.startFly()
		else
			PlayerModule.stopFly()
		end
	end,
})

PlayerGroupBox:AddSlider("FlySpeed", {
	Text = "ความเร็วในการบิน",
	Default = 50,
	Min = 10,
	Max = 200,
	Rounding = 0,
	Callback = function(Value)
		PlayerModule.FlySpeed = Value
	end,
})

PlayerGroupBox:AddDivider()

PlayerGroupBox:AddToggle("InfiniteJump", {
	Text = "การกระโดดที่ไม่มีที่สิ้นสุด",
	Default = false,
	Callback = function(value)
		PlayerModule.InfiniteJumpEnabled = value
	end,
})

PlayerModule.setupInfiniteJump()

local TeleportGroupBox = Tabs.Player:AddLeftGroupbox("เทเลพอร์ต")

TeleportGroupBox:AddButton({
	Text = "ร้านขายของ",
	Func = function()
		PlayerModule.teleportToLocation(Vector3.new(-152.43, 28.29, 117.26))
	end,
})

TeleportGroupBox:AddButton({
	Text = "Enchanter",
	Func = function()
		PlayerModule.teleportToLocation(Vector3.new(-260.09, 20.06, 30.93))
	end,
})

TeleportGroupBox:AddDivider()

for _, location in ipairs(PlayerModule.getProximityLocations()) do
	TeleportGroupBox:AddButton({
		Text = location.name,
		Func = function()
			local position = PlayerModule.getProximityPosition(location.path)
			if position then
				PlayerModule.teleportToLocation(position)
			end
		end,
	})
end

local PlayerSettings = Tabs.Player:AddRightGroupbox("สถิติของผู้เล่น")

PlayerSettings:AddSlider("WalkSpeed", {
	Text = "ความเร็วในการเดิน",
	Default = 1,
	Min = 1,
	Max = 10,
	Rounding = 1,
	Callback = function(Value)
		PlayerModule.WalkSpeedMultiplier = Value
	end,
})

PlayerModule.setupWalkSpeed()

local ServerGroupBox = Tabs.Player:AddRightGroupbox("เซิร์ฟเวอร์")

ServerGroupBox:AddButton({
	Text = "กระโดดเซิร์ฟเวอร์",
	Func = function()
		PlayerModule.serverHop()
	end,
})

ServerGroupBox:AddButton({
	Text = "เข้าร่วมเซิร์ฟเวอร์อีกครั้ง",
	Func = function()
		PlayerModule.rejoinServer()
	end,
})

-- SELL SYSTEM
local SellGroupBox = Tabs.Player:AddLeftGroupbox("ขาย")

SellGroupBox:AddToggle("AutoSellEnable", {
	Text = "เปิดใช้งานการขาย",
	Default = false,
	Callback = function(value)
		PlayerModule.AutoSellEnabled = value
		if value then
			PlayerModule.startAutoSell()
			Library:Notify("Auto Sell Enabled", 2)
		else
			PlayerModule.stopAutoSell()
			Library:Notify("Auto Sell Disabled", 2)
		end
	end,
})

SellGroupBox:AddDivider()

SellGroupBox:AddLabel("Select Items to Auto Sell")

SellGroupBox:AddDropdown("SellOres", {
	Values = PlayerModule.getOres(),
	Default = 1,
	Multi = true,
	Text = "แร่",
	Callback = function(value)
		PlayerModule.clearSellItems()
		for itemName, selected in pairs(value) do
			if selected then
				PlayerModule.addSellItem(itemName)
			end
		end
		if Options.SellEssences then
			for itemName, selected in pairs(Options.SellEssences.Value) do
				if selected then
					PlayerModule.addSellItem(itemName)
				end
			end
		end
		if Options.SellMaterials then
			for itemName, selected in pairs(Options.SellMaterials.Value) do
				if selected then
					PlayerModule.addSellItem(itemName)
				end
			end
		end
	end,
})

SellGroupBox:AddDropdown("SellEssences", {
	Values = PlayerModule.getEssences(),
	Default = 1,
	Multi = true,
	Text = "เอสเซ้นส์",
	Callback = function(value)
		PlayerModule.clearSellItems()
		if Options.SellOres then
			for itemName, selected in pairs(Options.SellOres.Value) do
				if selected then
					PlayerModule.addSellItem(itemName)
				end
			end
		end
		for itemName, selected in pairs(value) do
			if selected then
				PlayerModule.addSellItem(itemName)
			end
		end
		if Options.SellMaterials then
			for itemName, selected in pairs(Options.SellMaterials.Value) do
				if selected then
					PlayerModule.addSellItem(itemName)
				end
			end
		end
	end,
})

SellGroupBox:AddDropdown("SellMaterials", {
	Values = PlayerModule.getMaterials(),
	Default = 1,
	Multi = true,
	Text = "วัสดุ",
	Callback = function(value)
		PlayerModule.clearSellItems()
		if Options.SellOres then
			for itemName, selected in pairs(Options.SellOres.Value) do
				if selected then
					PlayerModule.addSellItem(itemName)
				end
			end
		end
		if Options.SellEssences then
			for itemName, selected in pairs(Options.SellEssences.Value) do
				if selected then
					PlayerModule.addSellItem(itemName)
				end
			end
		end
		for itemName, selected in pairs(value) do
			if selected then
				PlayerModule.addSellItem(itemName)
			end
		end
	end,
})

SellGroupBox:AddDivider()

SellGroupBox:AddButton({
	Text = "ล้างส่วนการเลือก",
	Func = function()
		PlayerModule.clearSellItems()
		Options.SellOres:SetValue({})
		Options.SellEssences:SetValue({})
		Options.SellMaterials:SetValue({})
		Library:Notify("Selection cleared", 2)
	end,
})

SellGroupBox:AddButton({
	Text = "Fix Auto Sell",
	Func = function()
		local success, message = PlayerModule.fixAutoSell()
		if success then
			Library:Notify(message, 2)
		else
			Library:Notify(message or "Failed to fix auto sell", 3)
		end
	end,
})

-- UI SETTINGS TAB
local MenuGroup = Tabs["UI Settings"]:AddLeftGroupbox("เมนู", "wrench")

MenuGroup:AddToggle("KeybindMenuOpen", {
	Default = false,
	Text = "เปิดเมนูคีย์บิด",
	Callback = function(value)
		Library.KeybindFrame.Visible = value
	end,
})

MenuGroup:AddDropdown("NotificationSide", {
	Values = { "Left", "Right" },
	Default = "Right",
	Text = "ด้านการแจ้งเตือน",
	Callback = function(Value)
		Library:SetNotifySide(Value)
	end,
})

MenuGroup:AddDivider()
MenuGroup:AddLabel("Menu bind"):AddKeyPicker("MenuKeybind", { Default = "RightShift", NoUI = true, Text = "การผูกปุ่มเมนู" })

MenuGroup:AddButton("Unload", function()
	GameModule.cleanup()
	Library:Unload()
end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)

SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })

ThemeManager:SetFolder("AutoFarmHub")
SaveManager:SetFolder("AutoFarmHub")

SaveManager:BuildConfigSection(Tabs["UI Settings"])
ThemeManager:ApplyToTab(Tabs["UI Settings"])

Library:OnUnload(function()
	GameModule.cleanup()
end)