-- Chinese (Simplified) Translation
-- Script ID: 665ebae4b216a7e9174305c623405ead
-- Created: 2026-05-16T01:42:39.190Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local repo      = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local moduleURL = "https://raw.githubusercontent.com/checkurasshole/INK/main/AgeOfTitansModule"

local Library      = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager  = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()
local CW           = loadstring(game:HttpGet(moduleURL))()

local Options = Library.Options
local Toggles = Library.Toggles

local Window = Library:CreateWindow({
    Title            = "COMBOWICK",
    Icon             = 6031071057,
    NotifySide       = "Right",
    ShowCustomCursor = false,
    AutoShow         = true,
})

local Tabs = {
    Main            = Window:AddTab("免费物品",  "star"),
    ["界面设置"] = Window:AddTab("界面设置", "settings"),
}

local LeftGroup  = Tabs.Main:AddLeftGroupbox("Items")
local RightGroup = Tabs.Main:AddRightGroupbox("Player")

LeftGroup:AddDropdown("DevProductDrop", {
    Text    = "选择物品",
    Values  = CW.productNames,
    Default = CW.productNames[1],
    Callback = function(v)
        for _, p in ipairs(CW.products) do
            if p.name == v then CW.selectedProduct = p break end
        end
    end,
})

LeftGroup:AddButton({
    Text = "领取所选物品",
    Func = function() CW.fireProduct(Library, CW.selectedProduct) end,
})

LeftGroup:AddButton({
    Text = "领取全部物品",
    Func = function() CW.fireAll(Library) end,
})

LeftGroup:AddDivider()

getgenv().bbLoopSingle = false
LeftGroup:AddToggle("LoopSingle", {
    Text    = "自动领取所选物品",
    Default = false,
    Callback = function(v)
        getgenv().bbLoopSingle = v
        while getgenv().bbLoopSingle and task.wait() do
            CW.fireProduct(Library, CW.selectedProduct)
        end
    end,
})

getgenv().bbLoopAll = false
LeftGroup:AddToggle("LoopAll", {
    Text    = "自动领取全部物品",
    Default = false,
    Callback = function(v)
        getgenv().bbLoopAll = v
        while getgenv().bbLoopAll and task.wait() do
            CW.fireAll(Library)
        end
    end,
})

RightGroup:AddToggle("SpeedEnabled", {Text = "速度提升", Default = false})
RightGroup:AddSlider("WalkSpeedVal", {
    Text = "移动速度", Default = 16, Min = 16, Max = 500, Rounding = 0,
})

RightGroup:AddDivider()

RightGroup:AddToggle("PlayerESP", {
    Text    = "玩家透视",
    Default = false,
    Callback = function(v)
        if v then CW.enableESP() else CW.removeESP() end
    end,
})

RightGroup:AddDivider()

RightGroup:AddDropdown("TeleportTarget", {
    Text    = "选择玩家",
    Values  = CW.getPlayerNames(),
    Default = CW.getPlayerNames()[1],
})

RightGroup:AddButton({
    Text = "传送到玩家",
    Func = function()
        local target = Options.TeleportTarget.Value
        if not target or target == "(no players)" then
            CW.notify(Library, "Error", "No player selected.") return
        end
        local tp     = game:GetService("Players"):FindFirstChild(target)
        local myHRP  = CW.LocalPlayer.Character and CW.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
        local tgtHRP = tp and tp.Character and tp.Character:FindFirstChild("HumanoidRootPart")
        if myHRP and tgtHRP then
            myHRP.CFrame = tgtHRP.CFrame + Vector3.new(0, 4, 0)
            CW.notify(Library, "Teleported", "You are now at " .. target)
        else
            CW.notify(Library, "Error", "Could not teleport to " .. target)
        end
    end,
})

RightGroup:AddButton({
    Text = "刷新玩家列表",
    Func = function()
        Options.TeleportTarget:SetValues(CW.getPlayerNames())
        CW.notify(Library, "Refreshed", "Player list updated.")
    end,
})

CW.startHeartbeat(Toggles, Options)

local MenuGroup = Tabs["界面设置"]:AddLeftGroupbox("Menu", "wrench")
MenuGroup:AddToggle("ShowCustomCursor", {
    Text     = "自定义光标",
    Default  = false,
    Callback = function(v) Library.ShowCustomCursor = v end,
})
MenuGroup:AddDivider()
MenuGroup:AddLabel("菜单快捷键"):AddKeyPicker("MenuKeybind", {Default="RightShift", NoUI=true, Text="菜单快捷键"})
MenuGroup:AddButton({Text="Unload", Func=function() Library:Unload() end})

Library.ToggleKeybind = Options.MenuKeybind
ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({"MenuKeybind"})
ThemeManager:SetFolder("Combowick")
SaveManager:SetFolder("Combowick/settings")
SaveManager:BuildConfigSection(Tabs["界面设置"])
ThemeManager:ApplyToTab(Tabs["界面设置"])
SaveManager:LoadAutoloadConfig()

Library:OnUnload(function()
    CW.unloadAll(Library, Toggles)
end)

if _G.COMBOWICK_KEY then
    _G.COMBOWICK_FREE   = false
    _G.COMBOWICK_ACTIVE = nil
    _G.COMBOWICK_KEY    = false
end

if _G.COMBOWICK_FREE then
    _G.COMBOWICK_ACTIVE = true
    task.spawn(function()
        repeat task.wait(1) until _G.COMBOWICK_ACTIVE == false
        CW.showExpiredPopup(Library)
    end)
end