-- Protected Script (French)
-- Script ID: 6af058ac2bca885f5f49dfb7b7a5bc79
-- Created: 2025-10-23T19:46:44.811Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local moduleUrl = "https://raw.githubusercontent.com/checkurasshole/Script/refs/heads/main/deadass"
local ComboWick = loadstring(game:HttpGet(moduleUrl))()

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local Options = Library.Options
local Toggles = Library.Toggles

local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local GetProfileData = ReplicatedStorage:WaitForChild("Events", 9e9):WaitForChild("GetProfileData", 9e9)

Library.ShowToggleFrameInKeybinds = true

local Window = Library:CreateWindow({
	Title = "_COMBO WICK",
	Footer = "Auto Farm & Pet Manager",
	Icon = 95816097006870,
	NotifySide = "Right",
	ShowCustomCursor = true,
})

local Tabs = {
	Main = Window:AddTab("Principales", "home"),
	["UI Settings"] = Window:AddTab("Paramètres de l' UI", "settings"),
}

local MainBox = Tabs.Main:AddLeftGroupbox("Auto-agriculture", "zap")

MainBox:AddToggle("AutoLift", {
	Text = "Exercice automatique",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.AutoLift = Value
	end,
})

MainBox:AddToggle("AutoPunch", {
	Text = "Lutte automatique",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.AutoPunch = Value
	end,
})

MainBox:AddToggle("Autorenaissance", {
	Text = "Renaissance automatique",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.AutoRebirth = Value
	end,
})

MainBox:AddDivider()

MainBox:AddToggle("Gems infinis", {
	Text = "Gems infinis",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.InfiniteGems = Value
	end,
})

MainBox:AddDivider()

MainBox:AddToggle("Anti-AFK", {
	Text = "Anti-AFK",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.AntiAFK = Value
	end,
})

local PetBox = Tabs.Main:AddRightGroupbox("Gestion des animaux de compagnie", "heart")

PetBox:AddLabel("Auto Hatch and Craft")

PetBox:AddSlider("MaxHatches", {
	Text = "Les chapeaux avant l'artisanat",
	Default = 5,
	Min = 1,
	Max = 20,
	Rounding = 0,
	Callback = function(Value)
		ComboWick.Options.MaxHatches = Value
	end,
})

PetBox:AddToggle("AutoHatchCraft", {
	Text = "Auto Hatch & Craft",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.AutoHatchCraft = Value
	end,
})

PetBox:AddDivider()

PetBox:AddLabel("Remove pets by quality")

PetBox:AddToggle("SupprimerByTier", {
	Text = "Activer la suppression par niveau",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.DeleteByTier = Value
	end,
})

PetBox:AddInput("DeleteTiers", {
	Default = "Basic,Uncommon,Rare",
	Finished = false,
	Text = "Niveaux à supprimer",
	Placeholder = "Basic,Uncommon,Rare,Epic,Shiny",
	Callback = function(Value)
		ComboWick.Options.DeleteTiers = Value
	end,
})

PetBox:AddDivider()

PetBox:AddToggle("SupprimerParNom", {
	Text = "Activer la suppression par nom",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.DeleteByName = Value
	end,
})

PetBox:AddDropdown("DeleteNames", {
	Values = {},
	Default = 1,
	Multi = true,
	Text = "Noms à supprimer",
	Callback = function(Value)
		ComboWick.Options.DeleteNames = Value
	end,
})

PetBox:AddButton({
	Text = "Rafraîchir les noms des animaux",
	Func = function()
		task.spawn(function()
			local args = { [1] = true }
			local success, profileData = pcall(function()
				return GetProfileData:InvokeServer(unpack(args))
			end)
			
			if success and profileData and profileData.Pets then
				local uniqueNames = {}
				local nameList = {}
				
				for _, petData in pairs(profileData.Pets) do
					if petData.PetName and not uniqueNames[petData.PetName] then
						uniqueNames[petData.PetName] = true
						table.insert(nameList, petData.PetName)
					end
				end
				
				table.sort(nameList)
				if Options.DeleteNames then
					Options.DeleteNames.Values = nameList
					Options.DeleteNames:SetValues(nameList)
				end
			end
		end)
	end,
})

PetBox:AddDivider()

PetBox:AddToggle("Suppression automatique", {
	Text = "Supprimer automatiquement les animaux de compagnie",
	Default = false,
	Callback = function(Value)
		ComboWick.Toggles.AutoDelete = Value
	end,
})

PetBox:AddButton({
	Text = "Manuel Supprimer maintenant",
	Func = function()
		ComboWick:DeletePets()
	end,
	Risky = true,
})

local lastRefreshTime = 0
local refreshCooldown = 30

task.spawn(function()
	RunService.Heartbeat:Connect(function()
		if tick() - lastRefreshTime >= refreshCooldown then
			lastRefreshTime = tick()
			
			task.spawn(function()
				local args = { [1] = true }
				local success, profileData = pcall(function()
					return GetProfileData:InvokeServer(unpack(args))
				end)
				
				if success and profileData and profileData.Pets then
					local uniqueNames = {}
					local nameList = {}
					
					for _, petData in pairs(profileData.Pets) do
						if petData.PetName and not uniqueNames[petData.PetName] then
							uniqueNames[petData.PetName] = true
							table.insert(nameList, petData.PetName)
						end
					end
					
					table.sort(nameList)
					if Options.DeleteNames then
						Options.DeleteNames.Values = nameList
						Options.DeleteNames:SetValues(nameList)
					end
				end
			end)
		end
	end)
end)

local MenuGroup = Tabs["UI Settings"]:AddLeftGroupbox("Menu", "wrench")

MenuGroup:AddToggle("KeybindMenuOuvrir", {
	Default = Library.KeybindFrame.Visible,
	Text = "Ouvrir le menu Keybind",
	Callback = function(value)
		Library.KeybindFrame.Visible = value
	end,
})

MenuGroup:AddToggle("AfficherCurseurCustom", {
	Text = "Curseur personnalisé",
	Default = true,
	Callback = function(Value)
		Library.ShowCustomCursor = Value
	end,
})

MenuGroup:AddDropdown("NotificationSide", {
	Values = { "Left", "Right" },
	Default = "Right",
	Text = "Côté notification",
	Callback = function(Value)
		Library:SetNotifySide(Value)
	end,
})

MenuGroup:AddDivider()
MenuGroup:AddLabel("Menu bind"):AddKeyPicker("MenuKeybind", { Default = "RightShift", NoUI = true, Text = "Keybind du menu" })

MenuGroup:AddButton("Unload", function()
	ComboWick:Destroy()
	Library:Unload()
end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("COMBO_WICK")
SaveManager:SetFolder("COMBO_WICK/configs")
SaveManager:BuildConfigSection(Tabs["UI Settings"])
ThemeManager:ApplyToTab(Tabs["UI Settings"])

ComboWick:Initialize()