-- COMBOWICK Loader (Filipino)
-- Script ID: 763a5160393e681defecff6ec74d5df8
-- Updated: 2026-07-10T05:47:12.595Z
-- Auto-generated by Lua Script Vault

if _G.COMBOWICK_ACTIVE then return end

local HttpService = game:GetService("HttpService")
local Players     = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

pcall(function() if not game:IsLoaded() then game.Loaded:Wait() end end)
do
    local t = tick()
    while not LocalPlayer and (tick() - t) < 10 do task.wait(); LocalPlayer = Players.LocalPlayer end
end
if not LocalPlayer then return end
if not game.PlaceId or game.PlaceId == 0 then return end

local MODULE_URL = "https://raw.githubusercontent.com/checkurasshole/combowick-test/main/combowick_module.lua"
local repo       = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"

local M
do
    local ok, m = pcall(function() return loadstring(game:HttpGet(MODULE_URL))() end)
    if ok and type(m) == "table" then M = m end
end
if not M then
    warn("[COMBOWICK] module failed to load from " .. tostring(MODULE_URL))
    return
end

M.queueOnTeleport()

if M.tryVaultWhitelist() then return end
if M.tryHwidKey() then return end

local preCheck = M.withRetry(M.checkSession, M.hwid)
if preCheck ~= nil and preCheck.status ~= "game_not_allowed" then
    if M.tryFreeSession(preCheck) then return end
end
preCheck = preCheck or { status = "error", remaining = 0, disabled = false }

do
    pcall(function() if getgenv and getgenv().Library then getgenv().Library:Unload() end end)
    local targets = {}
    if gethui then local ok, h = pcall(gethui); if ok and h then table.insert(targets, h) end end
    table.insert(targets, game:GetService("CoreGui"))
    for _, target in ipairs(targets) do
        for _, v in ipairs(target:GetChildren()) do
            local n = v.Name
            if n == "Obsidian" or n == "ObsidianLoading" or n == "LinoriaGui" then pcall(v.Destroy, v) end
        end
    end
end

local Library      = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager  = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()
local Options      = Library.Options

local VaultModule       = M.VaultModule
local execPremiumScript = M.execPremiumScript

local function safeSet(lbl, text) pcall(function() lbl:SetText(text) end) end

local Window = Library:CreateWindow({
    Title = "COMBOWICK", Footer = "Libreng Bersyon", NotifySide = "Right",
    ShowCustomCursor = false, AutoShow = true, Size = UDim2.fromOffset(560, 340),
})
local Tabs = {
    Main    = Window:AddTab("Main",        "user"),
    Key     = Window:AddTab("Premium Key", "key"),
    Suggest = Window:AddTab("Mga Suhestiyon", "message-square"),
    UI      = Window:AddTab("UI Settings", "settings"),
}

if M.looksTampered() then
    Library:Notify({Title="⚠️ Tampering", Description="May na-detect na binagong functions sa iyong executor.", Time=6})
end

local preRemaining = tonumber(preCheck.remaining) or 0
local preStatus      = preCheck.status
local gameDisabled   = preCheck.disabled == true
local gameUnsupported = preStatus == "game_not_allowed"

local InfoGroup = Tabs.Main:AddLeftGroupbox("Libreng Session", "info")
local lSession  = InfoGroup:AddLabel(
    (not gameDisabled and (preStatus == "allowed" or preStatus == "session_active") and preRemaining > 0)
        and string.format("Oras ng session: %s", M.formatTime(preRemaining)) or "Oras ng session: —", true)
local lCooldown = InfoGroup:AddLabel(
    (preStatus == "cooldown" and preRemaining > 0)
        and string.format("Cooldown: %s", M.formatTime(preRemaining)) or "Cooldown: —", true)
if gameUnsupported then
    InfoGroup:AddLabel("🚫 Hindi pa suportado ang laro na ito.", true)
elseif gameDisabled then
    InfoGroup:AddLabel("⛔ Hindi available ang libreng bersyon sa laro na ito.", true)
else
    InfoGroup:AddLabel("Hindi available ang libreng bersyon sa lahat ng laro.", true)
end
InfoGroup:AddDivider()
InfoGroup:AddLabel("Mag-upgrade sa 11-oras na key para maalis ang cooldown.", true)
InfoGroup:AddButton({
    Text = "Kopyahin ang Key Link", Tooltip = "combowick.com/verify/provider-select",
    Func = function()
        pcall(function() setclipboard(M.KEY_URL) end)
        Library:Notify({Title="COMBOWICK", Description="Nakopya ang link. I-paste ito sa iyong browser.", Time=4})
    end,
})
local StatusGroup = Tabs.Main:AddRightGroupbox("Status", "shield")
local statusLabel = StatusGroup:AddLabel("Sinusuri...", true)
local timerLabel  = StatusGroup:AddLabel("", true)
local hintLabel   = StatusGroup:AddLabel("", true)

local AnnounceGroup = Tabs.Main:AddRightGroupbox("📢 Mga Anunsyo", "megaphone")
local announceLabel = AnnounceGroup:AddLabel("Nilo-load ang mga anunsyo...", true)
task.spawn(function()
    local text
    local ok, body = pcall(function() return game:HttpGet(M.ANNOUNCE_URL) end)
    if ok and type(body) == "string" and #body > 0 then
        local dok, data = pcall(function() return HttpService:JSONDecode(body) end)
        if dok and data ~= nil then
            local a = data
            if type(a) == "table" and a[1] ~= nil then a = a[1] end
            if type(a) == "table" then
                if a.enabled ~= false and a.message then
                    text = (a.title and (tostring(a.title) .. "\n") or "") .. tostring(a.message)
                end
            elseif type(a) == "string" then
                text = a
            end
        elseif not body:match("^%s*<") then
            text = body:sub(1, 400)
        end
    end
    safeSet(announceLabel, (text and #M.trim(text) > 0) and M.trim(text) or "Walang anunsyo sa ngayon.")
end)

local savedKey = ""
if VaultModule and VaultModule.loadKey then
    local ok, k = pcall(VaultModule.loadKey)
    if ok and type(k) == "string" then savedKey = k end
end
local keyInputValue = savedKey

local KeyGroup = Tabs.Key:AddLeftGroupbox("Ilagay ang Iyong Key")
KeyGroup:AddInput("KeyInput", {
    Default          = savedKey,
    Numeric          = false,
    Finished         = false,
    ClearTextOnFocus = false,
    Text             = "Key 🔑",
    Placeholder      = "I-paste ang iyong key dito...",
    Callback         = function(v) keyInputValue = v end,
})
local function submitKey(key)
    key = M.cleanKey(key)
    if key == "" then
        Library:Notify({Title="⚠️ Walang Key na Nailagay", Description="Pakilagay ang iyong key.", Time=3})
        return
    end
    if VaultModule and VaultModule.validateKey then
        local ok = VaultModule.validateKey(key, M.hwid, Library)
        if ok then
            Library:Notify({Title="🔓 Nilo-load", Description="Nilo-load ang premium script...", Time=2})
            if VaultModule.startSessionMonitoring then pcall(VaultModule.startSessionMonitoring, M.hwid) end
            if getgenv then pcall(function() getgenv().VaultReady = true end) end
            if M.safeToLoad() and execPremiumScript then pcall(execPremiumScript) end
            task.wait(2)
            pcall(function() Library:Unload() end)
        else
            Library:Notify({Title="❌ Invalid na Key", Description="Hindi valid ang key na iyan. Pakisuri ito at subukang muli.", Time=4})
        end
    else
        local kr = M.withRetry(M.checkKey, M.encryptedHWID)
        if kr and kr.success == true then
            local url = M.getChronicleScript(game.PlaceId)
            if url and M.runUrl(url) then task.wait(1); pcall(function() Library:Unload() end); return end
        end
        Library:Notify({Title="Key Check", Description="Walang aktibong key na nahanap. I-activate ang iyong key sa website, tapos patakbuhin muli ang script.", Time=6})
    end
end

local function readKeyFromBox()
    local raw
    pcall(function()
        local holder = Options and Options.KeyInput and Options.KeyInput.Holder
        local box = holder and holder:FindFirstChildOfClass("TextBox")
        if box then raw = box.Text end
    end)
    local key = M.cleanKey(raw)
    if key == "" then key = M.cleanKey(Options and Options.KeyInput and Options.KeyInput.Value) end
    if key == "" then key = M.cleanKey(keyInputValue) end
    return key
end

KeyGroup:AddButton({
    Text = "✅ I-submit ang Key",
    Func = function() submitKey(readKeyFromBox()) end,
})
KeyGroup:AddButton({
    Text = "🔗 Kumuha ng Key",
    Func = function()
        pcall(function() setclipboard(M.KEY_URL) end)
        Library:Notify({Title="Nakopya", Description="Nakopya ang key link.", Time=2})
    end,
})

local HWIDGroup = Tabs.Key:AddRightGroupbox("Ang Iyong HWID")
HWIDGroup:AddLabel(M.hwid, true)
HWIDGroup:AddButton({
    Text = "📋 Kopyahin ang HWID",
    Func = function()
        pcall(function() setclipboard(M.hwid) end)
        Library:Notify({Title="Nakopya", Description="Nakopya ang HWID.", Time=2})
    end,
})
HWIDGroup:AddButton({
    Text = "🔒 Kopyahin ang Encrypted HWID",
    Func = function()
        pcall(function() setclipboard(M.encryptedHWID) end)
        Library:Notify({Title="Nakopya", Description="Nakopya ang encrypted HWID.", Time=2})
    end,
})

local FEEDBACK_COOLDOWN, lastFeedback = 20, 0
local ERRMAP = {
    empty = "Walang laman ang mensahe.", no_links = "Hindi pinapayagan ang mga link.",
    too_long = "Masyadong mahaba ang mensahe (500 karakter maximum).", rate_limited = "Naabot mo na ang limitasyong 3 mensahe. Pakisubukang muli mamaya.",
    busy = "Busy ang server. Pakisubukang muli.", banned = "Hindi ka pinapayagang magpadala ng feedback.",
    discord_error = "Nabigo ang pagpapadala. Pakisubukang muli.", network = "May error sa network.",
    no_request = "Hindi makapagpadala ng requests ang iyong executor.", bad_response = "Nagbalik ang server ng hindi inaasahang response.",
    unreachable = "Hindi maabot ng iyong executor ang server (TLS error). Sumubok ng ibang executor.",
}
local FG = Tabs.Suggest:AddLeftGroupbox("Mga Suhestiyon / Tulong", "message-square")
FG:AddDropdown("FeedbackType", {Text = "Uri", Values = {"Suggestion", "Bug", "Help"}, Default = "Suggestion", Callback = function() end})
FG:AddInput("FeedbackMsg", {Default = "", Numeric = false, Finished = false, ClearTextOnFocus = false, Text = "Mensahe", Placeholder = "I-type ang iyong mensahe (500 karakter maximum, walang link)"})
local fbStatus = FG:AddLabel("", true)
FG:AddButton({
    Text = "📨 Send",
    Func = function()
        local now = tick()
        if now - lastFeedback < FEEDBACK_COOLDOWN then
            safeSet(fbStatus, string.format("Maghintay ng %d segundo bago magpadala muli.", math.ceil(FEEDBACK_COOLDOWN - (now - lastFeedback))))
            return
        end
        local ftype = tostring((Options.FeedbackType and Options.FeedbackType.Value) or "Suggestion"):lower()
        local msg   = M.trim((Options.FeedbackMsg and Options.FeedbackMsg.Value) or "")
        if msg == "" then safeSet(fbStatus, "Walang laman ang mensahe."); return end
        if #msg > 500 then safeSet(fbStatus, "Masyadong mahaba ang mensahe (500 karakter maximum)."); return end
        local low = msg:lower()
        if low:find("http", 1, true) or low:find("discord.gg", 1, true) or low:find("www.", 1, true) or low:find(".gg/", 1, true) then
            safeSet(fbStatus, "Hindi pinapayagan ang mga link."); return
        end
        safeSet(fbStatus, "Nagpapadala...")
        task.spawn(function()
            local sok, err = M.sendFeedback(ftype, msg, (preCheck and preCheck.session_token) or "")
            if sok then
                lastFeedback = tick()
                safeSet(fbStatus, "✅ Naipadala. Salamat!")
                pcall(function() Options.FeedbackMsg:SetValue("") end)
                Library:Notify({Title = "COMBOWICK", Description = "Naipadala ang iyong feedback. Salamat!", Time = 3})
            else
                safeSet(fbStatus, ERRMAP[err] or ("Nabigong ipadala: " .. tostring(err)))
            end
        end)
    end,
})
FG:AddLabel("Maximum 3 mensahe kada oras. Walang link o mentions.", true)

local HelpGroup = Tabs.Suggest:AddRightGroupbox("Tulong / FAQ", "life-buoy")
HelpGroup:AddButton({
    Text = "💬 Sumali sa Discord",
    Tooltip = M.DISCORD_INVITE,
    Func = function()
        pcall(function() setclipboard(M.DISCORD_INVITE) end)
        Library:Notify({Title = "COMBOWICK", Description = "Nakopya ang Discord link. I-paste ito sa iyong browser.", Time = 4})
    end,
})
HelpGroup:AddDivider()
HelpGroup:AddLabel("❓ Paano ako makakakuha ng premium?\nKumuha ng key sa combowick.com/verify, tapos i-paste ito sa Premium Key tab. Isang tap lang ang kailangan.", true)
HelpGroup:AddLabel("⏳ Bakit ako naka-cooldown?\nMay panahon ng paghihintay ang libreng bersyon sa pagitan ng mga session. Ang 11-oras na key ay lubusang inaalis ito.", true)
HelpGroup:AddLabel("🎮 Hindi ito gumagana sa laro ko.\nHindi available ang libreng bersyon sa lahat ng laro. Tingnan ang aming Discord para sa listahan ng mga suportadong laro.", true)
HelpGroup:AddLabel("🔑 Ano ang aking HWID?\nIto ang iyong hardware ID. Kopyahin ito mula sa Premium Key tab kung hihingin ng support.", true)

task.spawn(function()
    safeSet(statusLabel, "Nag-a-authenticate...")

    local result = M.withRetry(M.checkSession, M.hwid)

    if result == nil then
        safeSet(statusLabel, "Status: Nabigo")
        Library:Notify({Title="COMBOWICK", Description="Nabigo ang session check.", Time=5})

    elseif result.status == "allowed" or result.status == "session_active" then
        if result.disabled then
            safeSet(statusLabel, "⛔ Naka-disable ang Laro")
            safeSet(hintLabel, "Hindi available ang libreng bersyon dito. Kumuha ng key.")
            Library:Notify({Title="COMBOWICK", Description="Naka-disable ang libreng bersyon para sa laro na ito. Gumamit ng key.", Time=6})
            return
        end
        local token = result.session_token
        if type(token) ~= "string" or #token < 20 then
            safeSet(statusLabel, "Status: Nabigo")
        else
            safeSet(statusLabel, "Status: Authenticated")
            Library:Notify({Title="COMBOWICK", Description="Ikaw ay authenticated na.", Time=3})
            _G.COMBOWICK_FREE   = true
            _G.COMBOWICK_ACTIVE = true
            local remaining = tonumber(result.remaining) or 0
            task.spawn(function()
                while remaining > 0 do
                    local fmt = M.formatTime(remaining)
                    safeSet(timerLabel, string.format("Natitirang oras: %s", fmt))
                    safeSet(lSession, string.format("Oras ng session: %s", fmt))
                    task.wait(1); remaining = remaining - 1
                end
                safeSet(timerLabel, "Nag-expire na ang session.")
                safeSet(lSession, "Oras ng session: nag-expire")
                _G.COMBOWICK_ACTIVE = false
                pcall(function() Library:Unload() end)
                task.wait(0.5)
                M.reloadExist()
            end)
            local scriptUrl = M.getScriptForGame(token)
            if M.loadFreeScript(scriptUrl, token) then task.wait(2); pcall(function() Library:Unload() end) end
        end

    elseif result.status == "cooldown" then
        local remaining = tonumber(result.remaining) or 0
        safeSet(statusLabel, "Naka-cooldown")
        safeSet(hintLabel, "Kumuha ng 11-oras na key, o maghintay hanggang matapos ang cooldown.")
        Library:Notify({Title="COMBOWICK", Description="Ikaw ay naka-cooldown. Kumuha ng key para laktawan ang paghihintay.", Time=6})
        task.spawn(function()
            while remaining > 0 do
                local fmt = M.formatTime(remaining)
                safeSet(timerLabel, string.format("Cooldown: %s", fmt))
                safeSet(lCooldown, string.format("Cooldown: %s", fmt))
                task.wait(1); remaining = remaining - 1
            end
            safeSet(timerLabel, "Tapos na ang cooldown.")
            safeSet(lCooldown, "Cooldown: tapos na")
            safeSet(hintLabel, "")
            Library:Notify({Title="COMBOWICK", Description="Tapos na ang cooldown. Nirerload...", Time=3})
            pcall(function() Library:Unload() end)
            task.wait(0.5)
            M.reloadExist()
        end)

    elseif result.status == "throttled" then
        local remaining = tonumber(result.remaining) or 0
        safeSet(statusLabel, "Masyadong Maraming Requests")
        safeSet(hintLabel, "Masyadong maraming requests. Pakihintay.")
        Library:Notify({Title="COMBOWICK", Description="Masyadong maraming requests. Sandaling maghintay.", Time=5})
        task.spawn(function()
            while remaining > 0 do
                safeSet(timerLabel, string.format("Subukang muli sa %s", M.formatTime(remaining)))
                task.wait(1); remaining = remaining - 1
            end
            safeSet(timerLabel, "Nirerload...")
            safeSet(hintLabel, "")
            pcall(function() Library:Unload() end)
            task.wait(0.5)
            M.reloadExist()
        end)

    elseif result.status == "disabled" then
        safeSet(statusLabel, "Naka-pause ang Serbisyo")
        safeSet(hintLabel, "Pansamantalang offline ang COMBOWICK.")
        Library:Notify({Title="COMBOWICK", Description="Kasalukuyang naka-disable ang serbisyo. Pakisubukang muli mamaya.", Time=6})

    elseif result.status == "banned" then
        safeSet(statusLabel, "Na-ban")
        Library:Notify({Title="COMBOWICK", Description="Ikaw ay na-ban.", Time=5})

    elseif result.status == "game_not_allowed" then
        safeSet(statusLabel, "🚫 Hindi Suportado ang Laro")
        safeSet(hintLabel, "Hindi pa suportado ang laro na ito. Gumagana pa rin ang premium keys kung may available na script.")
        Library:Notify({Title="COMBOWICK", Description="Hindi pa suportado ang laro na ito.", Time=6})

    else
        safeSet(statusLabel, "Error")
        safeSet(hintLabel, "Hindi maabot ang server. Pakipatakbo muli ang script.")
        Library:Notify({Title="COMBOWICK", Description=tostring(result.message or "May naganap na hindi kilalang error."), Time=5})
    end
end)

local MenuGroup = Tabs.UI:AddLeftGroupbox("Menu", "wrench")
MenuGroup:AddToggle("ShowCustomCursor", {Text="Custom Cursor", Default=false, Callback=function(v) Library.ShowCustomCursor = v end})
MenuGroup:AddLabel("Menu keybind"):AddKeyPicker("MenuKeybind", {Default="RightShift", NoUI=true, Text="Menu keybind"})
MenuGroup:AddButton({Text="Unload", Func=function() pcall(function() Library:Unload() end) end})
Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({"MenuKeybind"})
ThemeManager:SetFolder("COMBOWICK")
SaveManager:SetFolder("COMBOWICK/game")
SaveManager:BuildConfigSection(Tabs.UI)
ThemeManager:ApplyToTab(Tabs.UI)
SaveManager:LoadAutoloadConfig()
