-- Indonesian Translation
-- Script ID: 7bb7c9bc3659bc451c30e4fd7c234f20
-- Created: 2026-05-05T23:13:43.372Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local repo   = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local modURL = "https://raw.githubusercontent.com/checkurasshole/INK/main/KickLuckyBlockModule"

local Library    = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager  = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()
local M          = loadstring(game:HttpGet(modURL))()

local Options = Library.Options
local Toggles = Library.Toggles

local State        = M.State
local DiscordState = M.DiscordState
local Net          = M.Net
local player       = M.player
local PlayerGui    = M.PlayerGui
local Players      = M.Players

local Window = Library:CreateWindow({
    Title            = "COMBOWICK",
    Footer           = "Tendang Lucky Block",
    ShowCustomCursor = false,
    Size             = UDim2.new(0, 340, 0, 460),
})

local Tabs = {
    Main            = Window:AddTab("Utama ",        "home"),
    Farm            = Window:AddTab("Peternakan",        "coins"),
    Upgrades        = Window:AddTab("Peningkatan ",    "star"),
    Scanner         = Window:AddTab("Pemindai ",     "search"),
    Player          = Window:AddTab("Pemain ",      "user"),
    Discord         = Window:AddTab("Discord ",     "bell"),
    ["UI Settings"] = Window:AddTab("Pengaturan UI ", "settings"),
}

local MainGroup = Tabs.Main:AddLeftGroupbox("Tendang ")
local InfoGroup = Tabs.Main:AddRightGroupbox("Prediksi ")

MainGroup:AddDropdown("KickMode", {
    Text     = "Kekuatan Tendangan ",
    Values   = { "Perfect","Excellent","Great","Mid","Bad" },
    Default  = "Perfect",
    Callback = function(v) State.KickMode = v end,
})

MainGroup:AddToggle("AutoKick", {
    Text     = "Tendangan Otomatis ",
    Default  = false,
    Callback = function(v)
        State.AutoKick = v
        if v then M.startAutoKick() end
    end,
})

MainGroup:AddButton({
    Text = "Teleport ke Base Saya ",
    Func = function()
        pcall(function()
            local plot = M.getMyPlot()
            if plot then M.ForcedTP(plot:GetPivot() + Vector3.new(0, 5, 0)) end
        end)
    end,
})

MainGroup:AddDivider()

MainGroup:AddToggle("AutoRebirth", {
    Text     = "Rebirth Otomatis ",
    Default  = false,
    Callback = function(v)
        State.AutoRebirth = v
        if v then
            task.spawn(function()
                while State.AutoRebirth do
                    pcall(function() Net.rev_RebirthRequest:FireServer() end)
                    task.wait(3)
                end
            end)
        end
    end,
})

MainGroup:AddDivider()

MainGroup:AddDropdown("ZoneFilter", {
    Text     = "Filter Zona ",
    Values   = M.ZONE_NAMES,
    Default  = {},
    Multi    = true,
    Callback = function(v)
        for _, zone in ipairs(M.ZONE_NAMES) do
            State.ZoneFilter[zone] = v[zone] or false
        end
    end,
})

local KeepGroup = Tabs.Main:AddRightGroupbox("Simpan Filter ")

KeepGroup:AddLabel("Kosong = Simpan Hewan Peliharaan Apa Pun", true)
KeepGroup:AddDivider()

KeepGroup:AddDropdown("KeepRarityFilter", {
    Text     = "Simpan Hewan Peliharaan Berdasarkan Kelangkaan ",
    Values   = M.RARITY_LIST,
    Default  = {},
    Multi    = true,
    Callback = function(v)
        for _, rar in ipairs(M.RARITY_LIST) do
            State.KeepRarityFilter[rar] = v[rar] or false
        end
    end,
})

KeepGroup:AddDropdown("KeepMutFilter", {
    Text     = "Simpan Hewan Peliharaan Berdasarkan Mutasi ",
    Values   = M.MUTATION_LIST,
    Default  = {},
    Multi    = true,
    Callback = function(v)
        for _, mut in ipairs(M.MUTATION_LIST) do
            State.KeepMutFilter[mut] = v[mut] or false
        end
    end,
})

M.LabelName  = InfoGroup:AddLabel("Nama: —")
M.LabelMut   = InfoGroup:AddLabel("Mutasi: —")
M.LabelRar   = InfoGroup:AddLabel("Kelangkaan: —")
M.LabelCash  = InfoGroup:AddLabel("Uang: —")
M.LabelCount = InfoGroup:AddLabel("Tendangan: 0")

local FarmGroup = Tabs.Farm:AddLeftGroupbox("Bertani ")

FarmGroup:AddToggle("AutoCollect", {
    Text     = "Kumpulkan Uang Base Secara Otomatis ",
    Default  = false,
    Callback = function(v)
        State.AutoCollect = v
        if v then M.startAutoCollect() end
    end,
})

FarmGroup:AddToggle("AutoBuySpeed", {
    Text     = "Beli Peningkatan Kecepatan Secara Otomatis ",
    Default  = false,
    Callback = function(v)
        State.AutoBuySpeed = v
        if v then
            task.spawn(function()
                while State.AutoBuySpeed do
                    pcall(function() Net.rev_SPEED_UPGRADE:FireServer(1) end)
                    task.wait(0.5)
                end
            end)
        end
    end,
})

FarmGroup:AddToggle("AutoTrain", {
    Text     = "Latih Secara Otomatis (Bonus x2) ",
    Default  = false,
    Callback = function(v)
        State.AutoTrain = v
        if v then
            M.startOofLoop()
            task.spawn(function()
                while State.AutoTrain do
                    pcall(function()
                        local char        = player.Character
                        local hum         = char and char:FindFirstChild("Humanoid")
                        local backpack    = player:FindFirstChild("Backpack")
                        local currentTool = char and char:FindFirstChildOfClass("Tool")
                        local holdingValid = currentTool and M.validWeights[currentTool.Name]
                        if not holdingValid then
                            if currentTool then hum:UnequipTools() end
                            local slot1 = PlayerGui:FindFirstChild("Backpack")
                                and PlayerGui.Backpack:FindFirstChild("Bar")
                                and PlayerGui.Backpack.Bar:FindFirstChild("Slot1")
                            if slot1 and getconnections then
                                local targets = { slot1, slot1:FindFirstChild("ToolImage") }
                                for _, t in pairs(targets) do
                                    if t then
                                        pcall(function() for _, c in pairs(getconnections(t.MouseButton1Down))  do c:Fire() end end)
                                        pcall(function() for _, c in pairs(getconnections(t.MouseButton1Click)) do c:Fire() end end)
                                        pcall(function() for _, c in pairs(getconnections(t.Activated))         do c:Fire() end end)
                                        pcall(function()
                                            for _, c in pairs(getconnections(t.InputBegan)) do
                                                c:Fire({UserInputType=Enum.UserInputType.MouseButton1, UserInputState=Enum.UserInputState.Begin})
                                                c:Fire({UserInputType=Enum.UserInputType.Touch,        UserInputState=Enum.UserInputState.Begin})
                                            end
                                        end)
                                    end
                                end
                            end
                            task.wait(0.1)
                            if not char:FindFirstChildOfClass("Tool") and backpack and hum then
                                for _, tool in pairs(backpack:GetChildren()) do
                                    if tool:IsA("Tool") and M.validWeights[tool.Name] then
                                        hum:EquipTool(tool)
                                        break
                                    end
                                end
                            end
                        else
                            currentTool:Activate()
                            if getconnections then
                                for _, c in pairs(getconnections(currentTool.Activated)) do c:Fire() end
                            end
                        end
                    end)
                    pcall(function()
                        local kickUpgrades = PlayerGui:FindFirstChild("KickUpgrades")
                        if not kickUpgrades then return end
                        for _, bonus in pairs(kickUpgrades:GetChildren()) do
                            if bonus.Name == "Bonus" or bonus.Name == "PopBonus" then
                                if bonus.Visible then
                                    if not bonus:GetAttribute("AutoClicked") then
                                        bonus:SetAttribute("AutoClicked", true)
                                        task.spawn(function()
                                            task.wait(0.2)
                                            local imgLabel = bonus:FindFirstChild("ImageLabel")
                                            local targets  = { bonus }
                                            if imgLabel then table.insert(targets, imgLabel) end
                                            if getconnections then
                                                for _, target in pairs(targets) do
                                                    pcall(function()
                                                        for _, conn in pairs(getconnections(target.InputBegan)) do
                                                            conn:Fire({UserInputType=Enum.UserInputType.MouseButton1, UserInputState=Enum.UserInputState.Begin})
                                                            conn:Fire({UserInputType=Enum.UserInputType.Touch,        UserInputState=Enum.UserInputState.Begin})
                                                        end
                                                    end)
                                                    pcall(function() for _, conn in pairs(getconnections(target.MouseButton1Down))  do conn:Fire() end end)
                                                    pcall(function() for _, conn in pairs(getconnections(target.MouseButton1Up))    do conn:Fire() end end)
                                                    pcall(function() for _, conn in pairs(getconnections(target.MouseButton1Click)) do conn:Fire() end end)
                                                    pcall(function() for _, conn in pairs(getconnections(target.Activated))         do conn:Fire() end end)
                                                end
                                            end
                                        end)
                                    end
                                else
                                    bonus:SetAttribute("AutoClicked", nil)
                                end
                            end
                        end
                    end)
                    task.wait(0.1)
                end
                M.stopOofLoop()
            end)
        else
            M.stopOofLoop()
        end
    end,
})

FarmGroup:AddButton({
    Text = "Buka Pembekuan Latihan ",
    Func = function()
        pcall(function()
            local char = player.Character
            local root = char and char:FindFirstChild("HumanoidRootPart")
            if root then root.Anchored = false end
            for _, v in pairs(Players:GetPlayers()) do
                if v.Character and v.Character:FindFirstChild("Head") then
                    for _, x in pairs(v.Character.Head:GetChildren()) do
                        if x:IsA("Sound") then
                            pcall(function() x.Playing = true end)
                        end
                    end
                end
            end
        end)
    end,
})

FarmGroup:AddToggle("InstantTouch", {
    Text     = "Interaksi Instan ",
    Default  = false,
    Callback = function(v)
        State.InstantTouch = v
        if v then
            task.spawn(function()
                while State.InstantTouch do
                    pcall(function()
                        for _, obj in pairs(workspace:GetDescendants()) do
                            if obj:IsA("ProximityPrompt") then obj.HoldDuration = 0 end
                        end
                    end)
                    task.wait(1)
                end
            end)
        end
    end,
})

FarmGroup:AddDivider()

FarmGroup:AddButton({
    Text = "Jual Semua Hewan Peliharaan ",
    Func = function()
        pcall(function() Net.ref_B_SellAll:InvokeServer() end)
    end,
})

local UpGGroup = Tabs.Upgrades:AddLeftGroupbox("Tingkatkan ")

UpGGroup:AddToggle("AutoRefreshSlots", {
    Text    = "Segarkan Daftar Slot Secara Otomatis ",
    Default = true,
    Callback = function(v)
        State.AutoRefreshSlots = v
        if v then pcall(M.scanSlots) end
    end,
})

UpGGroup:AddDivider()

M.upgradeDropdown = UpGGroup:AddDropdown("TargetUpgrade", {
    Text     = "Pilih Slot untuk Ditingkatkan ",
    Values   = { "Memindai..." },
    Default  = "Memindai...",
    Callback = function(v)
        for _, s in ipairs(M.scannedSlots) do
            if M.buildSlotLabel(s) == v then
                State.TargetUpgrade = s.index
                break
            end
        end
    end,
})

UpGGroup:AddToggle("AutoUpgrade", {
    Text     = "Tingkatkan Slot Terpilih Secara Otomatis ",
    Default  = false,
    Callback = function(v)
        State.AutoUpgrade = v
        if v then
            task.spawn(function()
                while State.AutoUpgrade do
                    pcall(function() Net.rev_B_Upgrade:FireServer(State.TargetUpgrade) end)
                    task.wait(0.2)
                end
            end)
        end
    end,
})

UpGGroup:AddDivider()

UpGGroup:AddButton({
    Text = "Tingkatkan Semua Slot (1-30) ",
    Func = function()
        task.spawn(function()
            for i = 1, 30 do
                pcall(function() Net.rev_B_Upgrade:FireServer(i) end)
                task.wait(0.05)
            end
        end)
    end,
})

UpGGroup:AddButton({
    Text = "Tingkatkan Semua Slot (Aktif/Nonaktif Loop) ",
    Func = function()
        State.AutoUpgrade = not State.AutoUpgrade
        if State.AutoUpgrade then
            task.spawn(function()
                while State.AutoUpgrade do
                    for i = 1, 30 do
                        if not State.AutoUpgrade then break end
                        pcall(function() Net.rev_B_Upgrade:FireServer(i) end)
                        task.wait(0.05)
                    end
                    task.wait(0.1)
                end
            end)
        end
    end,
})

local ScannerBox      = Tabs.Scanner:AddLeftGroupbox("Hewan Peliharaan Terbaik per Base ")
local ScanStatusLabel = ScannerBox:AddLabel("Status: Tekan Pindai untuk Memulai", true)
ScannerBox:AddDivider()

local ResultLabels = {}
for i = 1, 10 do
    table.insert(ResultLabels, ScannerBox:AddLabel("", true))
end

local bestPlotRef = nil

ScannerBox:AddButton({
    Text    = "Pindai ",
    Tooltip = "Pindai semua base dan temukan hewan peliharaan terbaik di setiap base",
    Func    = function()
        ScanStatusLabel:SetText("Status: Memindai...")
        bestPlotRef = nil
        for _, lbl in ipairs(ResultLabels) do lbl:SetText("") end
        local plotResults = {}
        for _, plot in pairs(workspace.Plots:GetChildren()) do
            local owner = plot:GetAttribute("Owner") or "Unknown"
            if owner == player.Name then continue end
            local slots = plot:FindFirstChild("Slots")
            if slots then
                local bestPet, bestCashRaw = nil, nil
                for _, slot in pairs(slots:GetChildren()) do
                    local placed = slot:FindFirstChild("PlacedPart")
                    if placed then
                        local id       = placed:GetAttribute("ID")
                        local level    = placed:GetAttribute("Level") or 1
                        local mutation = placed:GetAttribute("Mutation") or "None"
                        if id then
                            local cashRaw = M.getCashRaw(id, level, mutation)
                            if cashRaw then
                                local isHigher = bestCashRaw == nil
                                if not isHigher then
                                    local ok, cmp = pcall(function() return cashRaw > bestCashRaw end)
                                    isHigher = ok and cmp
                                end
                                if isHigher then
                                    bestCashRaw = cashRaw
                                    bestPet = {
                                        id       = id,
                                        level    = level,
                                        mutation = mutation,
                                        rarity   = M.getRarity(id),
                                        cash     = tostring(cashRaw) .. "/s"
                                    }
                                end
                            end
                        end
                    end
                end
                if bestPet then
                    table.insert(plotResults, {
                        plot    = plot.Name,
                        plotObj = plot,
                        owner   = owner,
                        pet     = bestPet,
                        cashRaw = bestCashRaw
                    })
                end
            end
        end
        table.sort(plotResults, function(a, b)
            local ok, result = pcall(function() return a.cashRaw > b.cashRaw end)
            return ok and result
        end)
        local count = math.min(#plotResults, 10)
        for i = 1, count do
            local e = plotResults[i]
            ResultLabels[i]:SetText(string.format(
                "#%d [Base: %s] Owner: %s | Pet: %s | Level: %d | Mutation: %s | Rarity: %s | Cash: %s",
                i, e.plot, e.owner,
                e.pet.id, e.pet.level, e.pet.mutation, e.pet.rarity, e.pet.cash
            ))
        end
        if count == 0 then
            ScanStatusLabel:SetText("Status: Tidak Ada Hasil Ditemukan.")
        else
            ScanStatusLabel:SetText("Status: Complete — " .. count .. " Base(s) Scanned.")
            bestPlotRef = plotResults[1].plotObj
        end
    end,
})

ScannerBox:AddButton({
    Text    = "Teleport ke Hewan Peliharaan Terbaik ",
    Tooltip = "Teleport ke base dengan peringkat tertinggi",
    Func    = function()
        if not bestPlotRef then
            Library:Notify({ Title = "Scanner", Description = "Tidak ada hasil pemindaian. Tekan Pindai terlebih dahulu.", Time = 3 })
            return
        end
        M.ForcedTP(bestPlotRef:GetPivot() * CFrame.new(0, 5, 0))
    end,
})

local MovGroup  = Tabs.Player:AddLeftGroupbox("Pergerakan ")
local MiscGroup = Tabs.Player:AddRightGroupbox("Lain-lain ")

MovGroup:AddSlider("JumpPowerSlider", {
    Text     = "Kekuatan Lompatan ",
    Min      = 50,
    Max      = 500,
    Default  = 50,
    Rounding = 0,
    Callback = function(v) State.JumpPower = v; M.applyJumpPower(v) end,
})

MovGroup:AddToggle("InfiniteJump", {
    Text    = "Lompatan Tak Terbatas ",
    Default = false,
    Callback = function(v)
        State.InfiniteJump = v
        if v then M.enableInfiniteJump() else M.disableInfiniteJump() end
    end,
})

MovGroup:AddToggle("Noclip", {
    Text    = "Tembus Tembok ",
    Default = false,
    Callback = function(v)
        State.Noclip = v
        if v then M.enableNoclip() else M.disableNoclip() end
    end,
})

MiscGroup:AddToggle("AntiAFK", {
    Text    = "Anti-AFK ",
    Default = false,
    Callback = function(v)
        State.AntiAFK = v
        if v then M.enableAntiAFK() else M.disableAntiAFK() end
    end,
})

MiscGroup:AddSlider("FOVSlider", {
    Text     = "Bidang Pandang ",
    Min      = 50,
    Max      = 120,
    Default  = 70,
    Rounding = 0,
    Callback = function(v)
        State.FOV = v
        local cam = workspace.CurrentCamera
        if cam then cam.FieldOfView = v end
    end,
})

MiscGroup:AddToggle("PotatoMode", {
    Text    = "Mode Kualitas Rendah ",
    Default = false,
    Callback = function(v)
        State.PotatoMode = v
        if v then M.enablePotatoMode() else M.disablePotatoMode() end
    end,
})

local WebhookGroup = Tabs.Discord:AddLeftGroupbox("Webhook ")

WebhookGroup:AddToggle("DiscordEnabled", {
    Text     = "Aktifkan Notifikasi ",
    Default  = false,
    Callback = function(v) DiscordState.Enabled = v end,
})

WebhookGroup:AddDivider()

WebhookGroup:AddInput("WebhookURL", {
    Text        = "URL Webhook ",
    Default     = DiscordState.WebhookURL,
    Numeric     = false,
    Finished    = false,
    Placeholder = "Tempel URL Webhook di sini...",
    Callback    = function(v) DiscordState.WebhookURL = v end,
})

WebhookGroup:AddSlider("NotifCooldown", {
    Text     = "Cooldown Notifikasi (Detik) ",
    Min      = 1,
    Max      = 60,
    Default  = 10,
    Rounding = 0,
    Callback = function(v) DiscordState.Cooldown = v end,
})

WebhookGroup:AddDivider()

WebhookGroup:AddButton({
    Text = "Uji Webhook ",
    Func = function()
        if not DiscordState.WebhookURL or DiscordState.WebhookURL == "" then
            Library:Notify({ Title = "Discord", Description = "Belum ada URL Webhook yang diatur.", Time = 3 })
            return
        end
        local HttpService = game:GetService("HttpService")
        local payload = HttpService:JSONEncode({
            content  = "@everyone\n✅ Uji webhook **COMBOWICK** berhasil!\n👤 **Pemain:** " .. player.Name,
            username = "COMBOWICK Alert",
        })
        local ok, err = pcall(function()
            request({
                Url     = DiscordState.WebhookURL,
                Method  = "POST",
                Headers = { ["Content-Type"] = "application/json" },
                Body    = payload,
            })
        end)
        if ok then
            Library:Notify({ Title = "Discord", Description = "Notifikasi uji berhasil dikirim.", Time = 3 })
        else
            Library:Notify({ Title = "Discord", Description = "Kesalahan: " .. tostring(err), Time = 5 })
        end
    end,
})

local FilterGroup = Tabs.Discord:AddRightGroupbox("Filter Notifikasi ")

FilterGroup:AddLabel("Kirim notifikasi saat prediksi cocok:", true)
FilterGroup:AddDivider()

FilterGroup:AddDropdown("FilterKelangkaanDiscord ", {
    Text     = "Filter Notifikasi Berdasarkan Kelangkaan ",
    Values   = M.RARITY_LIST,
    Default  = {},
    Multi    = true,
    Callback = function(v)
        for _, rar in ipairs(M.RARITY_LIST) do
            DiscordState.NotifyRarities[rar] = v[rar] or false
        end
    end,
})

FilterGroup:AddDropdown("DiscordMutFilter", {
    Text     = "Filter Notifikasi Berdasarkan Mutasi ",
    Values   = M.MUTATION_LIST,
    Default  = {},
    Multi    = true,
    Callback = function(v)
        for _, mut in ipairs(M.MUTATION_LIST) do
            DiscordState.NotifyMutations[mut] = v[mut] or false
        end
    end,
})

local MenuGroup = Tabs["UI Settings"]:AddLeftGroupbox("Menu ")

MenuGroup:AddDivider()
MenuGroup:AddLabel("Tombol Pintas Menu ")
    :AddKeyPicker("MenuKeybind", { Default = "RightShift", NoUI = true, Text = "Tombol Pintas Menu " })

MenuGroup:AddButton("Muat Keluar Skrip ", function() Library:Unload() end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("combowick")
SaveManager:SetFolder("combowick/brainrot")
SaveManager:BuildConfigSection(Tabs["UI Settings"])
ThemeManager:ApplyToTab(Tabs["UI Settings"])
SaveManager:LoadAutoloadConfig()

M.hookRemotes()