-- Portuguese Translation
-- Script ID: 88ee701ad4ac054d0336d12815b88923
-- Created: 2026-05-20T05:37:06.378Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ForceCheckbox = false
Library.ShowToggleFrameInKeybinds = true

local Window = Library:CreateWindow({
	Title = "COMBOWICK",
	Footer = "v2.0",
	Icon = "star",
	NotifySide = "Right",
	ShowCustomCursor = false,
	Size = UDim2.fromOffset(300, 500),
})

local Tabs = {
	Main = Window:AddTab("Main", "sword"),
	["Configurações da UI"] = Window:AddTab("Configurações da UI", "settings"),
}

local CombatGroup  = Tabs.Main:AddLeftGroupbox("Combat", "zap")
local ESPGroup     = Tabs.Main:AddLeftGroupbox("ESP", "eye")
local GearGroup    = Tabs.Main:AddLeftGroupbox("Gears", "box")
local UpgradeGroup = Tabs.Main:AddRightGroupbox("Upgrades", "zap")
local WaveGroup    = Tabs.Main:AddRightGroupbox("Wave", "waves")
local MiscGroup    = Tabs.Main:AddRightGroupbox("Misc", "map-pin")
local InfoGroup    = Tabs.Main:AddRightGroupbox("Info", "info")

local Mod = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/main/SurviveZombieArenaModule"))()(Library, Toggles, Options)

local countLabel    = InfoGroup:AddLabel("Zumbis: 0")
local estCredLabel  = InfoGroup:AddLabel("Créditos Est.: 0")
local sessCredLabel = InfoGroup:AddLabel("Sessão: 0")

task.spawn(function()
	while true do
		task.wait(0.5)
		countLabel:SetText("Zombies: " .. Mod.getZombieCount())
		estCredLabel:SetText("Est. Credits: " .. tostring(Mod.getEstCredits()))
		sessCredLabel:SetText("Session: " .. tostring(Mod.sessionTotal))
		Mod.updateESP()
	end
end)

CombatGroup:AddToggle("AutoKill", {
	Text    = "Tiro automático",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.InstaKill.Value then Toggles.InstaKill:SetValue(false) end
			Mod.startAutoKill()
		else
			Mod.stopAutoKill()
		end
	end,
})
CombatGroup:AddSlider("AutoKillDelay", {
	Text = "Atraso do tiro automático (segundos)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddToggle("InstaKill", {
	Text    = "Matar instantaneamente",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.AutoKill.Value then Toggles.AutoKill:SetValue(false) end
			Mod.startInstaKill()
		else
			Mod.stopInstaKill()
		end
	end,
})
CombatGroup:AddSlider("InstaKillDamage", {
	Text = "Damage", Default = 999999999, Min = 1000, Max = 999999999, Rounding = 0,
})
CombatGroup:AddSlider("InstaKillDelay", {
	Text = "Atraso (segundos)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddButton({
	Text = "Matar todos", DoubleClick = false,
	Func = function() Mod.killAll() end,
})

ESPGroup:AddToggle("ZombieESP", {
	Text    = "Destaques de Zumbis",
	Default = false,
	Callback = function(Value) if not Value then Mod.clearESP() end end,
})
ESPGroup:AddDropdown("ESPColor", {
	Values = { "Red", "Orange", "Yellow", "Purple" }, Default = "Red", Text = "Color",
	Callback = function(Value) Mod.applyESPColor(Mod.ESP_COLORS[Value] or Mod.ESP_COLORS.Red) end,
})

local GEARS = {
	"Landmine", "AutoTurret", "Barricade", "Bunker", "Drone",
	"FlamethrowerTurret", "HealingStation", "LaserTurret", "MendingTower",
	"Molotov", "ShockwaveMine", "Shuriken", "Spikes", "SteelBarricade", "VanguardTurret",
}
GearGroup:AddDropdown("GearBuySelect", {
	Values = GEARS, Default = { "Landmine" }, Text = "Selecionar Engrenagens", Multi = true,
})
GearGroup:AddToggle("AutoBuyGear", {
	Text    = "Compra automática",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startAutoBuy() else Mod.stopAutoBuy() end
	end,
})
GearGroup:AddSlider("GearBuyDelay", {
	Text = "Atrasar compras", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

UpgradeGroup:AddToggle("AutoWeaponUpgrade", {
	Text    = "Upgrade automático de arma",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startWeaponUpgrade() else Mod.stopWeaponUpgrade() end
	end,
})
UpgradeGroup:AddSlider("WeaponUpgradeDelay", {
	Text = "Atraso (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})
UpgradeGroup:AddToggle("AutoHealthUpgrade", {
	Text    = "Upgrade automático de vida",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startHealthUpgrade() else Mod.stopHealthUpgrade() end
	end,
})
UpgradeGroup:AddSlider("HealthUpgradeDelay", {
	Text = "Atraso (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

WaveGroup:AddToggle("AutoSkipWave", {
	Text    = "Voto de pular automático",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startSkip() else Mod.stopSkip() end
	end,
})
WaveGroup:AddButton({
	Text = "Pular ondas instantaneamente agora", DoubleClick = false,
	Func = function()
		Mod.instantSkip()
		if not Toggles.EnableFly.Value then Toggles.EnableFly:SetValue(true) end
	end,
})
WaveGroup:AddToggle("AutoDoubleCredits", {
	Text    = "Créditos duplos automáticos",
	Default = false,
})

MiscGroup:AddToggle("AntiAFK", {
	Text    = "Anti AFK",
	Default = false,
	Callback = function(Value) if Value then Mod.enableAntiAFK() end end,
})
MiscGroup:AddToggle("Noclip", {
	Text    = "Noclip",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startNoclip() else Mod.stopNoclip() end
	end,
})
MiscGroup:AddSlider("WalkSpeed", {
	Text = "Velocidade de caminhada", Default = 16, Min = 16, Max = 150, Rounding = 0,
	Callback = function(Value) Mod.setWalkSpeed(Value) end,
})
MiscGroup:AddToggle("EnableFly", {
	Text    = "Fly",
	Default = false,
	Callback = function(Value) if Value then Mod.startFly() else Mod.stopFly() end end,
})
MiscGroup:AddSlider("FlyHeight", {
	Text = "Altura do voo", Default = 0, Min = 0, Max = 150, Rounding = 0,
})

local MenuGroup = Tabs["Configurações da UI"]:AddLeftGroupbox("Menu", "wrench")
MenuGroup:AddToggle("KeybindMenuOpen", {
	Default = Library.KeybindFrame.Visible, Text = "Menu de teclas",
	Callback = function(value) Library.KeybindFrame.Visible = value end,
})
MenuGroup:AddDropdown("NotificationSide", {
	Values = { "Left", "Right" }, Default = "Right", Text = "Lado das notificações",
	Callback = function(Value) Library:SetNotifySide(Value) end,
})
MenuGroup:AddDropdown("DPIDropdown", {
	Values = { "50%", "75%", "100%", "125%", "150%", "175%", "200%" }, Default = "100%", Text = "Escala de DPI",
	Callback = function(Value)
		Value = Value:gsub("%%", "")
		Library:SetDPIScale(tonumber(Value))
	end,
})
MenuGroup:AddSlider("UICornerSlider", {
	Text = "Raio dos cantos", Default = Library.CornerRadius, Min = 0, Max = 20, Rounding = 0,
	Callback = function(value) Window:SetCornerRadius(value) end,
})
MenuGroup:AddLabel("Tecla de atalho do menu"):AddKeyPicker("MenuKeybind", {
	Default = "RightShift", NoUI = true, Text = "Tecla de atalho do menu",
})
MenuGroup:AddButton("Unload", function() Library:Unload() end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("COMBOWICK")
SaveManager:SetFolder("COMBOWICK/zombie-game")
SaveManager:BuildConfigSection(Tabs["Configurações da UI"])
ThemeManager:ApplyToTab(Tabs["Configurações da UI"])
SaveManager:LoadAutoloadConfig()
Library:SetDPIScale(100)

if _G.COMBOWICK_KEY then
	_G.COMBOWICK_FREE = false
	_G.COMBOWICK_ACTIVE = nil
	_G.COMBOWICK_KEY = false
end

if _G.COMBOWICK_FREE then
	_G.COMBOWICK_ACTIVE = true
	task.spawn(function()
		repeat task.wait(1) until _G.COMBOWICK_ACTIVE == false
		Mod.disableAllFeatures()
		Mod.showExpiredPopup(function() Library:Unload() end)
	end)
end