-- Portuguese Translation
-- Script ID: 88ee701ad4ac054d0336d12815b88923
-- Updated: 2026-05-26T02:53:24.212Z
-- Auto-generated by Lua Script Vault

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library     = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager  = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local M = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/main/SurviveZombieArenaModule"))()

local Options = Library.Options
local Toggles = Library.Toggles
local LP = game:GetService("Players").LocalPlayer

Library.ForceCheckbox = false
Library.ShowToggleFrameInKeybinds = true

local Window = Library:CreateWindow({
	Title = "COMBOWICK",
	Footer = "v2.0",
	Icon = "star",
	NotifySide = "Right",
	ShowCustomCursor = false,
	Size = UDim2.fromOffset(300, 500),
})

local Tabs = {
	Main = Window:AddTab("Main", "sword"),
	["Configurações da UI"] = Window:AddTab("Configurações da UI", "settings"),
}

local CombatGroup  = Tabs.Main:AddLeftGroupbox("Combate ", "zap")
local ESPGroup     = Tabs.Main:AddLeftGroupbox("ESP", "eye")
local GearGroup    = Tabs.Main:AddLeftGroupbox("Engrenagens ", "box")
local InvisGroup   = Tabs.Main:AddLeftGroupbox("Imortal ", "eye")
local UpgradeGroup = Tabs.Main:AddRightGroupbox("Melhorias ", "zap")
local WaveGroup    = Tabs.Main:AddRightGroupbox("Onda ", "waves")
local MiscGroup    = Tabs.Main:AddRightGroupbox("Diversos ", "map-pin")
local InfoGroup    = Tabs.Main:AddRightGroupbox("Informações ", "info")

M.init(Toggles, Options)

local countLabel    = InfoGroup:AddLabel("Zumbis: 0")
local estCredLabel  = InfoGroup:AddLabel("Créditos estimados: 0")
local sessCredLabel = InfoGroup:AddLabel("Sessão: 0")

task.spawn(function()
	while true do
		task.wait(0.5)
		countLabel:SetText("Zombies: " .. M.getZombieCount())
		estCredLabel:SetText("Est. Credits: " .. tostring(M.getEstCredits()))
		sessCredLabel:SetText("Session: " .. tostring(M.getSessionTotal()))
		M.updateESP()
	end
end)

local function forceCleanup()
	-- ESP
	pcall(function()
		local folder = workspace:FindFirstChild("Zombies_Local")
		if folder then
			for _, zombie in ipairs(folder:GetChildren()) do
				local h = zombie:FindFirstChildOfClass("Highlight")
				if h then h:Destroy() end
			end
		end
	end)
	-- Fly
	pcall(function()
		local char = LP.Character
		if char then
			local root = char:FindFirstChild("HumanoidRootPart")
			if root then
				local bv = root:FindFirstChildOfClass("BodyVelocity")
				if bv then bv:Destroy() end
			end
		end
	end)
	-- Invisibility
	pcall(function()
		local inv = workspace:FindFirstChild("invischair")
		if inv then inv:Destroy() end
		local char = LP.Character
		if char then
			for _, part in pairs(char:GetDescendants()) do
				if part:IsA("BasePart") and part.Name ~= "HumanoidRootPart" then
					part.Transparency = 0
				end
			end
		end
	end)
	-- Noclip + WalkSpeed
	pcall(function()
		local char = LP.Character
		if char then
			for _, part in ipairs(char:GetDescendants()) do
				if part:IsA("BasePart") then part.CanCollide = true end
			end
			local hum = char:FindFirstChildOfClass("Humanoid")
			if hum then hum.WalkSpeed = 16 end
		end
	end)
end

CombatGroup:AddToggle("AutoKill", {
	Text    = "Atirar automaticamente",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.InstaKill.Value then Toggles.InstaKill:SetValue(false) end
			M.startAutoKill()
		else
			M.stopAutoKill()
		end
	end,
})
CombatGroup:AddSlider("AutoKillDelay", {
	Text = "Atraso do tiro automático (segundos)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddToggle("InstaKill", {
	Text    = "Matar instantaneamente",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.AutoKill.Value then Toggles.AutoKill:SetValue(false) end
			M.startInstaKill()
		else
			M.stopInstaKill()
		end
	end,
})
CombatGroup:AddSlider("InstaKillDamage", {
	Text = "Damage", Default = 999999999, Min = 1000, Max = 999999999, Rounding = 0,
})
CombatGroup:AddSlider("InstaKillDelay", {
	Text = "Atraso (segundos)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddButton({
	Text = "Matar todos", DoubleClick = false,
	Func = function() M.killAll() end,
})

ESPGroup:AddToggle("ZombieESP", {
	Text    = "Realces dos zumbis",
	Default = false,
	Callback = function(Value) if not Value then M.clearESP() end end,
})
ESPGroup:AddDropdown("ESPColor", {
	Values = { "Red", "Orange", "Yellow", "Purple" }, Default = "Red", Text = "Color",
	Callback = function(Value) M.applyESPColor(M.ESP_COLORS[Value] or M.ESP_COLORS.Red) end,
})

GearGroup:AddDropdown("GearBuySelect", {
	Values = M.GEARS, Default = { "Landmine" }, Text = "Selecionar engrenagens", Multi = true,
})
GearGroup:AddToggle("AutoBuyGear", {
	Text    = "Compra automática",
	Default = false,
	Callback = function(Value)
		if Value then M.startAutoBuy() else M.stopAutoBuy() end
	end,
})
GearGroup:AddSlider("GearBuyDelay", {
	Text = "Atrasar compra(s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

InvisGroup:AddToggle("InvisEnabled", {
	Text    = "Imortal ",
	Default = false,
	Callback = function(Value)
		if Value then
			M.setInvisTransparency(Options.InvisTransparency.Value / 100)
			M.enableInvisibility()
		else
			M.disableInvisibility()
		end
	end,
})
InvisGroup:AddSlider("InvisTransparency", {
	Text = "Transparência ", Default = 0, Min = 0, Max = 100, Rounding = 0,
	Callback = function(value)
		M.setInvisTransparency(value / 100)
	end,
})
InvisGroup:AddLabel("Atalho de Imortal"):AddKeyPicker("Keybind_Invis", {
	Default  = "Z",
	Mode     = "Press",
	Text     = "Alternar invisibilidade",
	NoUI     = false,
	Callback = function()
		Toggles.InvisEnabled:SetValue(not Toggles.InvisEnabled.Value)
	end,
})

UpgradeGroup:AddToggle("AutoWeaponUpgrade", {
	Text    = "Upgrade automático de arma",
	Default = false,
	Callback = function(Value)
		if Value then M.startWeaponUpgrade() else M.stopWeaponUpgrade() end
	end,
})
UpgradeGroup:AddSlider("WeaponUpgradeDelay", {
	Text = "Atraso (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})
UpgradeGroup:AddToggle("AutoHealthUpgrade", {
	Text    = "Melhoria automática de saúde",
	Default = false,
	Callback = function(Value)
		if Value then M.startHealthUpgrade() else M.stopHealthUpgrade() end
	end,
})
UpgradeGroup:AddSlider("HealthUpgradeDelay", {
	Text = "Atraso (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

WaveGroup:AddToggle("AutoSkipWave", {
	Text    = "Voto para pular automaticamente",
	Default = false,
	Callback = function(Value)
		if Value then M.startSkip() else M.stopSkip() end
	end,
})
WaveGroup:AddButton({
	Text = "Pular ondas instantaneamente agora", DoubleClick = false,
	Func = function()
		M.instantSkip()
		if not Toggles.EnableFly.Value then Toggles.EnableFly:SetValue(true) end
	end,
})
WaveGroup:AddToggle("AutoDoubleCredits", {
	Text    = "Créditos em dobro automáticos",
	Default = false,
})

MiscGroup:AddToggle("AntiAFK", {
	Text    = "Anti AFK",
	Default = false,
	Callback = function(Value) if Value then M.enableAntiAFK() end end,
})
MiscGroup:AddToggle("Noclip", {
	Text    = "Noclip",
	Default = false,
	Callback = function(Value)
		if Value then M.startNoclip() else M.stopNoclip() end
	end,
})
MiscGroup:AddSlider("WalkSpeed", {
	Text = "Velocidade de caminhada", Default = 16, Min = 16, Max = 150, Rounding = 0,
	Callback = function(Value) M.setWalkSpeed(Value) end,
})
MiscGroup:AddToggle("EnableFly", {
	Text    = "Fly",
	Default = false,
	Callback = function(Value) if Value then M.startFly() else M.stopFly() end end,
})
MiscGroup:AddSlider("FlyHeight", {
	Text = "Altura do voo", Default = 0, Min = 0, Max = 150, Rounding = 0,
})

local MenuGroup = Tabs["Configurações da UI"]:AddLeftGroupbox("Menu", "wrench")
MenuGroup:AddToggle("KeybindMenuOpen", {
	Default = Library.KeybindFrame.Visible, Text = "Menu de atalhos",
	Callback = function(value) Library.KeybindFrame.Visible = value end,
})
MenuGroup:AddDropdown("NotificationSide", {
	Values = { "Left", "Right" }, Default = "Right", Text = "Lado das notificações",
	Callback = function(Value) Library:SetNotifySide(Value) end,
})
MenuGroup:AddDropdown("DPIDropdown", {
	Values = { "50%", "75%", "100%", "125%", "150%", "175%", "200%" }, Default = "100%", Text = "Escala de DPI",
	Callback = function(Value)
		Value = Value:gsub("%%", "")
		Library:SetDPIScale(tonumber(Value))
	end,
})
MenuGroup:AddSlider("UICornerSlider", {
	Text = "Raio dos cantos", Default = Library.CornerRadius, Min = 0, Max = 20, Rounding = 0,
	Callback = function(value) Window:SetCornerRadius(value) end,
})
MenuGroup:AddLabel("Atalho do menu"):AddKeyPicker("MenuKeybind", {
	Default = "RightShift", NoUI = true, Text = "Atalho do menu",
})
MenuGroup:AddButton("Unload", function() Library:Unload() end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("COMBOWICK")
SaveManager:SetFolder("COMBOWICK/zombie-game")
SaveManager:BuildConfigSection(Tabs["Configurações da UI"])
ThemeManager:ApplyToTab(Tabs["Configurações da UI"])
SaveManager:LoadAutoloadConfig()
Library:SetDPIScale(100)

Library:OnUnload(function()
	forceCleanup()
end)

local function showExpiredPopup(onDone)
	forceCleanup()

	local ScreenGui = Instance.new("ScreenGui")
	ScreenGui.Name = "CW_Expired"
	ScreenGui.ResetOnSpawn = false
	ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
	ScreenGui.Parent = game:GetService("CoreGui")
	local Frame = Instance.new("Frame")
	Frame.Size = UDim2.fromOffset(280, 140)
	Frame.Position = UDim2.new(0.5, -140, 0, -150)
	Frame.BackgroundColor3 = Color3.fromRGB(18, 18, 22)
	Frame.BorderSizePixel = 0
	Frame.Parent = ScreenGui
	Instance.new("UICorner", Frame).CornerRadius = UDim.new(0, 14)
	local Stroke = Instance.new("UIStroke", Frame)
	Stroke.Color = Color3.fromRGB(80, 80, 100)
	Stroke.Thickness = 1
	local Title = Instance.new("TextLabel", Frame)
	Title.Size = UDim2.new(1, -20, 0, 28)
	Title.Position = UDim2.fromOffset(10, 10)
	Title.BackgroundTransparency = 1
	Title.Text = "Sessão gratuita encerrada"
	Title.TextColor3 = Color3.fromRGB(255, 255, 255)
	Title.TextSize = 14
	Title.Font = Enum.Font.GothamBold
	Title.TextXAlignment = Enum.TextXAlignment.Left
	local Sub = Instance.new("TextLabel", Frame)
	Sub.Size = UDim2.new(1, -20, 0, 34)
	Sub.Position = UDim2.fromOffset(10, 36)
	Sub.BackgroundTransparency = 1
	Sub.Text = "Obtenha uma chave em combowick.com
para continuar sem tempos de espera."
	Sub.TextColor3 = Color3.fromRGB(180, 180, 200)
	Sub.TextSize = 12
	Sub.Font = Enum.Font.Gotham
	Sub.TextXAlignment = Enum.TextXAlignment.Left
	Sub.TextWrapped = true
	local Button = Instance.new("TextButton", Frame)
	Button.Size = UDim2.new(1, -20, 0, 24)
	Button.Position = UDim2.fromOffset(10, 74)
	Button.BackgroundColor3 = Color3.fromRGB(100, 100, 200)
	Button.BorderSizePixel = 0
	Button.Text = "Copiar link da chave"
	Button.TextColor3 = Color3.fromRGB(255, 255, 255)
	Button.TextSize = 12
	Button.Font = Enum.Font.GothamBold
	Instance.new("UICorner", Button).CornerRadius = UDim.new(0, 6)
	Button.MouseButton1Click:Connect(function()
		pcall(function() setclipboard("https://combowick.com/verify/provider-select") end)
		Button.Text = "Copiado!"
		task.wait(1.5)
		Button.Text = "Copiar link da chave"
	end)
	local Bar = Instance.new("Frame", Frame)
	Bar.Size = UDim2.new(1, -20, 0, 3)
	Bar.Position = UDim2.fromOffset(10, 122)
	Bar.BackgroundColor3 = Color3.fromRGB(100, 100, 200)
	Bar.BorderSizePixel = 0
	Instance.new("UICorner", Bar).CornerRadius = UDim.new(1, 0)
	Frame:TweenPosition(UDim2.new(0.5, -140, 0, 20), Enum.EasingDirection.Out, Enum.EasingStyle.Quint, 0.4, true)
	local ts = game:GetService("TweenService")
	ts:Create(Bar, TweenInfo.new(20, Enum.EasingStyle.Linear), { Size = UDim2.new(0, 0, 0, 3) }):Play()
	task.delay(20, function()
		Frame:TweenPosition(UDim2.new(0.5, -140, 0, -150), Enum.EasingDirection.In, Enum.EasingStyle.Quint, 0.4, true)
		task.wait(0.5)
		ScreenGui:Destroy()
		if onDone then onDone() end
	end)
end

if _G.COMBOWICK_KEY then
	_G.COMBOWICK_FREE   = false
	_G.COMBOWICK_ACTIVE = nil
	_G.COMBOWICK_KEY    = false
end

if _G.COMBOWICK_FREE then
	_G.COMBOWICK_ACTIVE = true
	task.spawn(function()
		repeat task.wait(1) until _G.COMBOWICK_ACTIVE == false
		showExpiredPopup(function()
			Library:Unload()
		end)
	end)
end