-- Protected Script (Russian)
-- Script ID: 8e53b95c2fa747e17fa2a52a8e329e55
-- Created: 2025-12-22T18:57:54.499Z
-- Source: External API
-- Auto-generated by Lua Script Vault

if getgenv().ComboWickLoaded then
    getgenv().ComboWickLoaded:Unload()
end

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()

local Module = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/Trt/refs/heads/main/inf%20money"))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ShowCustomCursor = false

getgenv().ComboWickLoaded = Library

local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Footer = "By COMBO_WICK",
    ShowCustomCursor = false,
    Position = UDim2.new(0.5, -200, 0.5, -150),
    Size = UDim2.new(0, 400, 0, 300),
})

local Tabs = {
    Main = Window:AddTab("Основной", "shopping-cart"),
    Other = Window:AddTab("Прочее", "zap"),
}

local MainBox = Tabs.Main:AddLeftGroupbox("Характеристики", "package")

MainBox:AddButton({
    Text = "Максимальные статы",
    Func = function()
        Module.trainStat("9999e15")
        task.wait(0.1)
        Module.winGainStat("9999e15")
    end
})

MainBox:AddDivider()

local customTrainValue = "1"

MainBox:AddInput("CustomTrain", {
    Default = "",
    Numeric = false,
    Finished = true,
    Text = "Сила",
    Placeholder = "",
    Callback = function(Value)
        customTrainValue = Value
    end,
})

MainBox:AddButton({
    Text = "Тренировать силу",
    Func = function()
        Module.trainStat(customTrainValue)
    end
})

MainBox:AddDivider()

local customWinGainValue = "1"

MainBox:AddInput("CustomWinGain", {
    Default = "",
    Numeric = false,
    Finished = true,
    Text = "Деньги",
    Placeholder = "",
    Callback = function(Value)
        customWinGainValue = Value
    end,
})

MainBox:AddButton({
    Text = "Получить деньги",
    Func = function()
        Module.winGainStat(customWinGainValue)
    end
})

local RightBox = Tabs.Main:AddRightGroupbox("Прочее", "zap")

RightBox:AddButton({
    Text = "Зачарованный",
    Func = function()
        Module.enchanted(195500000000, 0.15)
    end
})

RightBox:AddButton({
    Text = "Добавить здоровье / Перерождение",
    Func = function()
        Module.healthAdd(25)
    end
})

local OtherBox = Tabs.Other:AddLeftGroupbox("Миры и предметы", "globe")

OtherBox:AddButton({
    Text = "Открыть все миры",
    Func = function()
        Module.unlockWorld("W3")
        task.wait(0.1)
        Module.unlockWorld("W2")
        task.wait(0.1)
        Module.unlockWorld("W1")
    end
})

OtherBox:AddDivider()

OtherBox:AddButton({
    Text = "Купить лучшую лопату",
    Func = function()
        Module.buyPower("Water", 39100000000)
    end
})

local PetBox = Tabs.Other:AddRightGroupbox("Питомцы", "star")

local petData = 900

PetBox:AddInput("PetData", {
    Default = "900",
    Numeric = true,
    Finished = true,
    Text = "Данные питомца",
    Placeholder = "",
    Callback = function(Value)
        petData = tonumber(Value) or 900
    end,
})

PetBox:AddButton({
    Text = "Получить лучшего питомца",
    Func = function()
        Module.hatchPet("Exotic", "Celestia", petData)
    end
})