-- English (Original)
-- Script ID: 9b8c67ec1697f32f887908eabf113931
-- Created: 2026-05-02T03:48:31.361Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/deividcomsono/Obsidian/main/Library.lua"))()
local ThemeManager = loadstring(game:HttpGet("https://raw.githubusercontent.com/deividcomsono/Obsidian/main/addons/ThemeManager.lua"))()
local SaveManager  = loadstring(game:HttpGet("https://raw.githubusercontent.com/deividcomsono/Obsidian/main/addons/SaveManager.lua"))()

local M = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/main/CombowickMain.lua"))()

local Window = Library:CreateWindow({
    Title            = "COMBOWICK",
    ShowCustomCursor = false,
    Size             = UDim2.new(0, 340, 0, 480),
    Position         = UDim2.new(0.5, -170, 0.5, -240),
    AutoShow         = true,
    NotifySide       = "Right",
})

local Tabs = {
    Farm     = Window:AddTab("Automatic Farm "),
    Wins     = Window:AddTab("Wins & Gifts "),
    Spot     = Window:AddTab("Farm Position "),
    Extras   = Window:AddTab("Extras "),
    Guide    = Window:AddTab("Guide "),
    Settings = Window:AddTab("Settings "),
}

local FarmLeft  = Tabs.Farm:AddLeftGroupbox("Farm Setup ")
local FarmRight = Tabs.Farm:AddRightGroupbox("Status ")

local statusLabel = FarmRight:AddLabel({ Text = "Status: Idle " })
local worldLabel  = FarmRight:AddLabel({ Text = "Tower: detecting... " })

task.spawn(function()
    while not Library.Unloaded do
        task.wait(0.5)
        if M.isSharedStallActive() then
            local remaining = math.max(0, math.ceil(M.getSharedStallUntil() - tick()))
            statusLabel:SetText("Status: Stalled " .. remaining .. "s ")
        elseif M.isClaimingWins() then
            statusLabel:SetText("Status: Claiming Wins ")
        elseif M.isListening() then
            statusLabel:SetText("Status: Listening... ")
        elseif M.isAllCaptured() then
            statusLabel:SetText("Status: Ready! ")
        else
            statusLabel:SetText("Status: Not set up yet ")
        end
        worldLabel:SetText("Tower: " .. (M.getCurrentWorldName() or "not found") .. " ")
    end
end)

FarmLeft:AddToggle("AutoSetupToggle", {
    Text     = "Automatic Setup on New Tower ",
    Default  = true,
    Callback = function(val) M.autoListenOnWorldChange = val end,
})

FarmLeft:AddDivider()

local JumpInput = FarmLeft:AddInput("JumpInput", {
    Text        = "Jump Power ",
    Default     = "0",
    Numeric     = true,
    Finished    = false,
    Placeholder = "Auto-fills after capture ",
})
JumpInput:OnChanged(function(val)
    local num = tonumber(val)
    if num then M.setCustomJumpVal(math.clamp(num, 0, 9999)) end
end)

task.spawn(function()
    local synced = false
    while not Library.Unloaded do
        task.wait(0.5)
        local cap = M.getCaptured()
        if not synced and cap.JumpResults1 and cap.JumpResults1.value then
            JumpInput:SetValue(tostring(math.clamp(math.floor(cap.JumpResults1.value), 0, 9999)))
            synced = true
        end
        if not cap.JumpResults1 then synced = false end
    end
end)

FarmLeft:AddDivider()

FarmLeft:AddInput("AutoFireWaitInput", {
    Text        = "Delay Between Farms (seconds) ",
    Default     = "5",
    Numeric     = true,
    Finished    = false,
    Placeholder = "Seconds between farms ",
}):OnChanged(function(val)
    local num = tonumber(val)
    if num and num >= 0.1 then M.autoFireWait = num end
end)

FarmLeft:AddDivider()
FarmLeft:AddLabel({ Text = "Not working? Climb & jump " })
FarmLeft:AddLabel({ Text = "manually then try again. " })
FarmLeft:AddDivider()

FarmLeft:AddToggle("AutoFarmToggle", {
    Text    = "Automatic Money Farm ",
    Default = false,
})

Library.Toggles.AutoFarmToggle:OnChanged(function()
    if Library.Toggles.AutoFarmToggle.Value then
        M.startAutoFarmLoop()
    end
end)

local WinsLeft  = Tabs.Wins:AddLeftGroupbox("Claim Wins ")
local WinsRight = Tabs.Wins:AddRightGroupbox("Win Status ")

local cwStatusLabel = WinsRight:AddLabel({ Text = "Status: Off " })
local cwWorldLabel2 = WinsRight:AddLabel({ Text = "Tower: - " })

task.spawn(function()
    while not Library.Unloaded do
        task.wait(1)
        local world = M.getCurrentWorld()
        cwWorldLabel2:SetText("Tower: " .. (world and world.Name or "not found") .. " ")
    end
end)

WinsLeft:AddInput("ClaimDelayInput", {
    Text        = "How often to claim (seconds) ",
    Default     = "40",
    Numeric     = true,
    Finished    = false,
    Placeholder = "Default: 40 ",
}):OnChanged(function(val)
    local num = tonumber(val)
    if num and num >= 1 then M.claimWinsDelay = num end
end)

WinsLeft:AddDivider()

WinsLeft:AddToggle("AutoClaimToggle", {
    Text    = "Automatic Claim Wins ",
    Default = false,
})

Library.Toggles.AutoClaimToggle:OnChanged(function()
    M.autoClaimWinsEnabled = Library.Toggles.AutoClaimToggle.Value
    if M.autoClaimWinsEnabled then
        task.spawn(function() M.autoClaimWinsLoop(cwStatusLabel) end)
        Library:Notify({Title="Automatic Claim Wins ", Description="Started! ", Duration=3})
    else
        Library:Notify({Title="Automatic Claim Wins ", Description="Stopped. ", Duration=3})
    end
end)

local GiftGroup = Tabs.Wins:AddLeftGroupbox("Free Gifts ")
local SpinGroup = Tabs.Wins:AddRightGroupbox("Spin ")

GiftGroup:AddToggle("AutoAwardToggle", {
    Text    = "Automatic Free Gifts (60s) ",
    Default = false,
})

Library.Toggles.AutoAwardToggle:OnChanged(function()
    M.autoAwardEnabled = Library.Toggles.AutoAwardToggle.Value
    if M.autoAwardEnabled then
        task.spawn(M.autoAwardLoop)
        Library:Notify({Title="Automatic Free Gifts ", Description="Started! ", Duration=3})
    else
        Library:Notify({Title="Automatic Free Gifts ", Description="Stopped. ", Duration=3})
    end
end)

SpinGroup:AddInput("AutoSpinDelayInput", {
    Text        = "Spin again after (seconds) ",
    Default     = "86400",
    Numeric     = true,
    Finished    = false,
    Placeholder = "Default: 86400 = 24hrs ",
}):OnChanged(function(val)
    local num = tonumber(val)
    if num and num >= 1 then M.autoSpinDelay = num end
end)

SpinGroup:AddDivider()

SpinGroup:AddToggle("AutoSpinToggle", {
    Text    = "Automatic Spin ",
    Default = false,
})

Library.Toggles.AutoSpinToggle:OnChanged(function()
    M.autoSpinEnabled = Library.Toggles.AutoSpinToggle.Value
    if M.autoSpinEnabled then
        task.spawn(M.autoSpinLoop)
        Library:Notify({Title="Automatic Spin ", Description="Started! ", Duration=3})
    else
        Library:Notify({Title="Automatic Spin ", Description="Stopped. ", Duration=3})
    end
end)

-- FARM POSITION TAB
local SpotLeft  = Tabs.Spot:AddLeftGroupbox("Position Override ")
local SpotRight = Tabs.Spot:AddRightGroupbox("Quick-Save Key ")

local overrideLabel = SpotLeft:AddLabel({ Text = "Custom Position: OFF " })
local savedCFLabel  = SpotLeft:AddLabel({ Text = "Saved: none " })

SpotLeft:AddButton("Save Current Position ", function()
    local char = game.Players.LocalPlayer.Character
    if not char then Library:Notify({Title="Error ", Description="No character! ", Duration=3}) return end
    local root = char:FindFirstChild("HumanoidRootPart")
    if not root then Library:Notify({Title="Error ", Description="No HumanoidRootPart! ", Duration=3}) return end
    M.setCustomCFrameOverride(root.CFrame)
    local p = root.Position
    savedCFLabel:SetText(string.format("Saved: %.1f, %.1f, %.1f ", p.X, p.Y, p.Z))
    Library:Notify({Title="Position Saved! ", Description=string.format("%.1f, %.1f, %.1f", p.X, p.Y, p.Z), Duration=4})
end)

SpotLeft:AddButton("Clear Custom Position ", function()
    M.setCustomCFrameOverride(nil)
    savedCFLabel:SetText("Saved: none ")
    Library:Notify({Title="Cleared ", Description="Using original captured spot. ", Duration=3})
end)

task.spawn(function()
    while not Library.Unloaded do
        task.wait(0.5)
        overrideLabel:SetText("Custom Position: " .. (M.getCustomCFrameOverride() and "ON " or "OFF "))
    end
end)

local keybindLabel = SpotRight:AddLabel({ Text = "Quick-Save Key: F " })

SpotRight:AddButton("Set Quick-Save Key ", function()
    M.setSettingKeybind(true)
    keybindLabel:SetText("Press a key now... ")
    Library:Notify({Title="Press Any Key ", Description="That key will save your spot. ", Duration=4})
end)

SpotRight:AddButton("Clear Quick-Save Key ", function()
    M.setTeleportKeybind(nil)
    keybindLabel:SetText("Quick-Save Key: none ")
    Library:Notify({Title="Key Cleared ", Description="No quick-save key set. ", Duration=3})
end)

M.onKeybindSet = function(keyCode)
    keybindLabel:SetText("Quick-Save Key: " .. keyCode.Name .. " ")
end

M.onSpotSaved = function(p)
    savedCFLabel:SetText(string.format("Saved: %.1f, %.1f, %.1f ", p.X, p.Y, p.Z))
end

-- EXTRAS TAB
local EggsGroup  = Tabs.Extras:AddLeftGroupbox("Automatic Hatch Eggs ")
local SpeedGroup = Tabs.Extras:AddRightGroupbox("Walk Speed ")

EggsGroup:AddToggle("AutoBuyEggsToggle", {
    Text    = "Automatic Hatch Eggs ",
    Default = false,
})

Library.Toggles.AutoBuyEggsToggle:OnChanged(function()
    M.autoBuyEggsEnabled = Library.Toggles.AutoBuyEggsToggle.Value
    if M.autoBuyEggsEnabled then
        task.spawn(M.autoBuyEggsLoop)
        Library:Notify({Title="Automatic Hatch Eggs ", Description="Started! ", Duration=3})
    else
        Library:Notify({Title="Automatic Hatch Eggs ", Description="Stopped. ", Duration=3})
    end
end)

SpeedGroup:AddSlider("WalkSpeedSlider", {
    Text     = "Walk Speed ",
    Default  = 16,
    Min      = 0,
    Max      = 710,
    Suffix   = " studs/s",
    Rounding = 0,
    Callback = function(val)
        M.walkSpeed = val
        if not M.speedLoopEnabled then
            M.speedLoopEnabled = true
            task.spawn(M.speedLoop)
        end
    end,
})

SpeedGroup:AddDivider()

SpeedGroup:AddButton("Reset Speed to 16 ", function()
    M.speedLoopEnabled = false
    task.wait(0.1)
    local char = game.Players.LocalPlayer.Character
    if char then
        local hum = char:FindFirstChildOfClass("Humanoid")
        if hum then hum.WalkSpeed = 16 end
    end
    M.walkSpeed = 16
    if Library.Sliders and Library.Sliders.WalkSpeedSlider then
        Library.Sliders.WalkSpeedSlider:SetValue(16)
    end
    Library:Notify({Title="Speed Reset ", Description="Back to normal (16). ", Duration=3})
end)

-- GUIDE TAB
local G1 = Tabs.Guide:AddLeftGroupbox("Automatic Farm? ")
local G2 = Tabs.Guide:AddRightGroupbox("No Coins & Wins? ")
local G3 = Tabs.Guide:AddLeftGroupbox("Farm Position? ")
local G4 = Tabs.Guide:AddRightGroupbox("Eggs? ")

G1:AddLabel({ Text = "1. Open the Automatic Farm tab. " })
G1:AddLabel({ Text = "2. Turn on Automatic Setup. " })
G1:AddLabel({ Text = "3. Wait for Status: Ready! " })
G1:AddLabel({ Text = "4. Turn on Automatic Money Farm. " })

G2:AddLabel({ Text = "Turn OFF Automatic Money Farm. " })
G2:AddLabel({ Text = "Turn OFF Automatic Claim Wins. " })
G2:AddLabel({ Text = "Wait 20 seconds then turn both ON. " })
G2:AddDivider()
G2:AddLabel({ Text = "Keep upgrading your wings! " })
G2:AddLabel({ Text = "Keep buying more pets! " })
G2:AddLabel({ Text = "More pets and wings = more money. " })

G3:AddLabel({ Text = "This is where your character farms. " })
G3:AddLabel({ Text = "Walk to your spot and press Save. " })

G4:AddLabel({ Text = "Walk close to the egg you want. " })
G4:AddLabel({ Text = "Then turn on Automatic Eggs. " })
G4:AddLabel({ Text = "Make sure you have enough money. " })

-- SETTINGS TAB
local SettingsGUI = Tabs.Settings:AddLeftGroupbox("GUI ")
local ExecGroup   = Tabs.Settings:AddRightGroupbox("Executor Check ")

SettingsGUI:AddButton("Unload / Close Script ", function()
    Library:Unload()
end)
SettingsGUI:AddDivider()

if M.allRequiredPresent then
    ExecGroup:AddLabel({ Text = "[COMPATIBLE] All functions found! " })
else
    ExecGroup:AddLabel({ Text = "[INCOMPATIBLE] Missing functions! " })
    ExecGroup:AddLabel({ Text = "Missing: " .. table.concat(M.missingRequired, ", ") .. " " })
end

ExecGroup:AddDivider()
ExecGroup:AddLabel({ Text = "-- Required -- " })
for _, name in ipairs(M.requiredFns) do
    ExecGroup:AddLabel({ Text = (M.checkFn(name) and "[OK] " or "[MISSING] ") .. name .. " " })
end

ExecGroup:AddDivider()
ExecGroup:AddLabel({ Text = "-- Optional -- " })
for _, name in ipairs(M.optionalFns) do
    ExecGroup:AddLabel({ Text = (M.checkFn(name) and "[OK] " or "[N/A] ") .. name .. " " })
end

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:SetFolder("COMBOWICK")
ThemeManager:ApplyToTab(Tabs.Settings)
SaveManager:BuildConfigSection(Tabs.Settings)
SaveManager:LoadAutoloadConfig()

M.init(Library, JumpInput)

if M.allRequiredPresent then
    Library:Notify({
        Title       = "COMBOWICK",
        Description = "Loaded! Executor is compatible. ",
        Duration    = 5,
    })
else
    Library:Notify({
        Title       = "INCOMPATIBLE EXECUTOR ",
        Description = "Missing: " .. table.concat(M.missingRequired, ", ") .. " ",
        Duration    = 8,
    })
end