-- Vietnamese Translation
-- Script ID: a2b71e27aa6b5bf41d6da93df6dc9e05
-- Updated: 2026-05-25T16:37:29.781Z
-- Auto-generated by Lua Script Vault

-- Main Script
local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ForceCheckbox = false
Library.ShowToggleFrameInKeybinds = true

local Window = Library:CreateWindow({
	Title = "COMBOWICK",
	Footer = "v2.0",
	Icon = "star",
	NotifySide = "Right",
	ShowCustomCursor = false,
	Size = UDim2.fromOffset(300, 500),
})

local Tabs = {
	Main = Window:AddTab("Main", "sword"),
	["Cài đặt UI"] = Window:AddTab("Cài đặt UI", "settings"),
}

local CombatGroup  = Tabs.Main:AddLeftGroupbox("Chiến đấu ", "zap")
local ESPGroup     = Tabs.Main:AddLeftGroupbox("ESP", "eye")
local GearGroup    = Tabs.Main:AddLeftGroupbox("Bánh răng", "box")
local InvisGroup   = Tabs.Main:AddLeftGroupbox("Bất tử ", "eye")
local UpgradeGroup = Tabs.Main:AddRightGroupbox("Nâng cấp ", "zap")
local WaveGroup    = Tabs.Main:AddRightGroupbox("Làn sóng ", "waves")
local MiscGroup    = Tabs.Main:AddRightGroupbox("Khác ", "map-pin")
local InfoGroup    = Tabs.Main:AddRightGroupbox("Thông tin ", "info")

local Mod = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/main/SurviveZombieArenaModule"))()(Library, Toggles, Options)

local countLabel    = InfoGroup:AddLabel("Zombie: 0")
local estCredLabel  = InfoGroup:AddLabel("Tín dụng ước tính: 0")
local sessCredLabel = InfoGroup:AddLabel("Phiên: 0")

task.spawn(function()
	while true do
		task.wait(0.5)
		countLabel:SetText("Zombies: " .. Mod.getZombieCount())
		estCredLabel:SetText("Est. Credits: " .. tostring(Mod.getEstCredits()))
		sessCredLabel:SetText("Session: " .. tostring(Mod.sessionTotal))
		Mod.updateESP()
	end
end)

CombatGroup:AddToggle("AutoKill", {
	Text    = "Tự động bắn",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.InstaKill.Value then Toggles.InstaKill:SetValue(false) end
			Mod.startAutoKill()
		else
			Mod.stopAutoKill()
		end
	end,
})
CombatGroup:AddSlider("AutoKillDelay", {
	Text = "Độ trễ tự bắn (giây)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddToggle("InstaKill", {
	Text    = "Hạ gục ngay lập tức",
	Default = false,
	Callback = function(Value)
		if Value then
			if Toggles.AutoKill.Value then Toggles.AutoKill:SetValue(false) end
			Mod.startInstaKill()
		else
			Mod.stopInstaKill()
		end
	end,
})
CombatGroup:AddSlider("InstaKillDamage", {
	Text = "Damage", Default = 999999999, Min = 1000, Max = 999999999, Rounding = 0,
})
CombatGroup:AddSlider("InstaKillDelay", {
	Text = "Độ trễ (giây)", Default = 0.1, Min = 0, Max = 2, Rounding = 2,
})
CombatGroup:AddButton({
	Text = "Hạ gục tất cả", DoubleClick = false,
	Func = function() Mod.killAll() end,
})

ESPGroup:AddToggle("ZombieESP", {
	Text    = "Tô sáng zombie",
	Default = false,
	Callback = function(Value) if not Value then Mod.clearESP() end end,
})
ESPGroup:AddDropdown("ESPColor", {
	Values = { "Red", "Orange", "Yellow", "Purple" }, Default = "Red", Text = "Color",
	Callback = function(Value) Mod.applyESPColor(Mod.ESP_COLORS[Value] or Mod.ESP_COLORS.Red) end,
})

local GEARS = {
	"Landmine", "AutoTurret", "Barricade", "Bunker", "Drone",
	"FlamethrowerTurret", "HealingStation", "LaserTurret", "MendingTower",
	"Molotov", "ShockwaveMine", "Shuriken", "Spikes", "SteelBarricade", "VanguardTurret",
}
GearGroup:AddDropdown("GearBuySelect", {
	Values = GEARS, Default = { "Landmine" }, Text = "Chọn trang bị", Multi = true,
})
GearGroup:AddToggle("AutoBuyGear", {
	Text    = "Mua tự động",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startAutoBuy() else Mod.stopAutoBuy() end
	end,
})
GearGroup:AddSlider("GearBuyDelay", {
	Text = "Trì hoãn mua hàng", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

InvisGroup:AddToggle("InvisEnabled", {
	Text    = "Bất tử ",
	Default = false,
	Callback = function(Value)
		if Value then
			Mod.setInvisTransparency(Options.InvisTransparency.Value / 100) -- apply current slider value immediately
			Mod.enableInvisibility()
		else
			Mod.disableInvisibility()
		end
	end,
})

InvisGroup:AddSlider("InvisTransparency", {
	Text = "Độ trong suốt ", Default = 0, Min = 0, Max = 100, Rounding = 0,
	Callback = function(value)
		Mod.setInvisTransparency(value / 100)
	end,
})
InvisGroup:AddLabel("Phím gán Bất tử"):AddKeyPicker("Keybind_Invis", {
	Default  = "Z",
	Mode     = "Press",
	Text     = "Bật/tắt tàng hình",
	NoUI     = false,
	Callback = function()
		Toggles.InvisEnabled:SetValue(not Toggles.InvisEnabled.Value)
	end,
})

UpgradeGroup:AddToggle("AutoWeaponUpgrade", {
	Text    = "Tự động nâng cấp vũ khí",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startWeaponUpgrade() else Mod.stopWeaponUpgrade() end
	end,
})
UpgradeGroup:AddSlider("WeaponUpgradeDelay", {
	Text = "Độ trễ (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})
UpgradeGroup:AddToggle("AutoHealthUpgrade", {
	Text    = "Tự động nâng cấp máu",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startHealthUpgrade() else Mod.stopHealthUpgrade() end
	end,
})
UpgradeGroup:AddSlider("HealthUpgradeDelay", {
	Text = "Độ trễ (s)", Default = 0.5, Min = 0.1, Max = 5, Rounding = 1,
})

WaveGroup:AddToggle("AutoSkipWave", {
	Text    = "Tự động bỏ qua bình chọn",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startSkip() else Mod.stopSkip() end
	end,
})
WaveGroup:AddButton({
	Text = "Bỏ qua làn sóng ngay lập tức", DoubleClick = false,
	Func = function()
		Mod.instantSkip()
		if not Toggles.EnableFly.Value then Toggles.EnableFly:SetValue(true) end
	end,
})
WaveGroup:AddToggle("AutoDoubleCredits", {
	Text    = "Tự động nhân đôi tín dụng",
	Default = false,
})

MiscGroup:AddToggle("AntiAFK", {
	Text    = "Chống AFK",
	Default = false,
	Callback = function(Value) if Value then Mod.enableAntiAFK() end end,
})
MiscGroup:AddToggle("Noclip", {
	Text    = "Noclip",
	Default = false,
	Callback = function(Value)
		if Value then Mod.startNoclip() else Mod.stopNoclip() end
	end,
})
MiscGroup:AddSlider("WalkSpeed", {
	Text = "Tốc độ đi", Default = 16, Min = 16, Max = 150, Rounding = 0,
	Callback = function(Value) Mod.setWalkSpeed(Value) end,
})
MiscGroup:AddToggle("EnableFly", {
	Text    = "Fly",
	Default = false,
	Callback = function(Value) if Value then Mod.startFly() else Mod.stopFly() end end,
})
MiscGroup:AddSlider("FlyHeight", {
	Text = "Độ cao bay", Default = 0, Min = 0, Max = 150, Rounding = 0,
})

local MenuGroup = Tabs["Cài đặt UI"]:AddLeftGroupbox("Menu", "wrench")
MenuGroup:AddToggle("KeybindMenuOpen", {
	Default = Library.KeybindFrame.Visible, Text = "Menu phím gán",
	Callback = function(value) Library.KeybindFrame.Visible = value end,
})
MenuGroup:AddDropdown("NotificationSide", {
	Values = { "Left", "Right" }, Default = "Right", Text = "Vị trí thông báo",
	Callback = function(Value) Library:SetNotifySide(Value) end,
})
MenuGroup:AddDropdown("DPIDropdown", {
	Values = { "50%", "75%", "100%", "125%", "150%", "175%", "200%" }, Default = "100%", Text = "Tỉ lệ DPI",
	Callback = function(Value)
		Value = Value:gsub("%%", "")
		Library:SetDPIScale(tonumber(Value))
	end,
})
MenuGroup:AddSlider("UICornerSlider", {
	Text = "Độ bo góc", Default = Library.CornerRadius, Min = 0, Max = 20, Rounding = 0,
	Callback = function(value) Window:SetCornerRadius(value) end,
})
MenuGroup:AddLabel("Phím gán menu"):AddKeyPicker("MenuKeybind", {
	Default = "RightShift", NoUI = true, Text = "Phím gán menu",
})
MenuGroup:AddButton("Unload", function() Library:Unload() end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("COMBOWICK")
SaveManager:SetFolder("COMBOWICK/zombie-game")
SaveManager:BuildConfigSection(Tabs["Cài đặt UI"])
ThemeManager:ApplyToTab(Tabs["Cài đặt UI"])
SaveManager:LoadAutoloadConfig()
Library:SetDPIScale(100)

local function showExpiredPopup(onDone)
	local ScreenGui = Instance.new("ScreenGui")
	ScreenGui.Name = "CW_Expired"
	ScreenGui.ResetOnSpawn = false
	ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
	ScreenGui.Parent = game:GetService("CoreGui")

	local Frame = Instance.new("Frame")
	Frame.Size = UDim2.fromOffset(280, 140)
	Frame.Position = UDim2.new(0.5, -140, 0, -150)
	Frame.BackgroundColor3 = Color3.fromRGB(18, 18, 22)
	Frame.BorderSizePixel = 0
	Frame.Parent = ScreenGui
	Instance.new("UICorner", Frame).CornerRadius = UDim.new(0, 14)

	local Stroke = Instance.new("UIStroke", Frame)
	Stroke.Color = Color3.fromRGB(80, 80, 100)
	Stroke.Thickness = 1

	local Title = Instance.new("TextLabel", Frame)
	Title.Size = UDim2.new(1, -20, 0, 28)
	Title.Position = UDim2.fromOffset(10, 10)
	Title.BackgroundTransparency = 1
	Title.Text = "Phiên miễn phí kết thúc"
	Title.TextColor3 = Color3.fromRGB(255, 255, 255)
	Title.TextSize = 14
	Title.Font = Enum.Font.GothamBold
	Title.TextXAlignment = Enum.TextXAlignment.Left

	local Sub = Instance.new("TextLabel", Frame)
	Sub.Size = UDim2.new(1, -20, 0, 34)
	Sub.Position = UDim2.fromOffset(10, 36)
	Sub.BackgroundTransparency = 1
	Sub.Text = "Nhận một khóa tại combowick.com\nto tiếp tục mà không có thời gian chờ."
	Sub.TextColor3 = Color3.fromRGB(180, 180, 200)
	Sub.TextSize = 12
	Sub.Font = Enum.Font.Gotham
	Sub.TextXAlignment = Enum.TextXAlignment.Left
	Sub.TextWrapped = true

	local Button = Instance.new("TextButton", Frame)
	Button.Size = UDim2.new(1, -20, 0, 24)
	Button.Position = UDim2.fromOffset(10, 74)
	Button.BackgroundColor3 = Color3.fromRGB(100, 100, 200)
	Button.BorderSizePixel = 0
	Button.Text = "Sao chép liên kết khóa"
	Button.TextColor3 = Color3.fromRGB(255, 255, 255)
	Button.TextSize = 12
	Button.Font = Enum.Font.GothamBold
	Instance.new("UICorner", Button).CornerRadius = UDim.new(0, 6)

	Button.MouseButton1Click:Connect(function()
		pcall(function() setclipboard("https://combowick.com/verify/provider-select") end)
		Button.Text = "Đã sao chép!"
		task.wait(1.5)
		Button.Text = "Sao chép liên kết khóa"
	end)

	local Bar = Instance.new("Frame", Frame)
	Bar.Size = UDim2.new(1, -20, 0, 3)
	Bar.Position = UDim2.fromOffset(10, 122)
	Bar.BackgroundColor3 = Color3.fromRGB(100, 100, 200)
	Bar.BorderSizePixel = 0
	Instance.new("UICorner", Bar).CornerRadius = UDim.new(1, 0)

	Frame:TweenPosition(UDim2.new(0.5, -140, 0, 20), Enum.EasingDirection.Out, Enum.EasingStyle.Quint, 0.4, true)

	local ts = game:GetService("TweenService")
	ts:Create(Bar, TweenInfo.new(20, Enum.EasingStyle.Linear), { Size = UDim2.new(0, 0, 0, 3) }):Play()

	task.delay(20, function()
		Frame:TweenPosition(UDim2.new(0.5, -140, 0, -150), Enum.EasingDirection.In, Enum.EasingStyle.Quint, 0.4, true)
		task.wait(0.5)
		ScreenGui:Destroy()
		if onDone then onDone() end
	end)
end

if _G.COMBOWICK_FREE then
	_G.COMBOWICK_ACTIVE = true
	task.spawn(function()
		repeat task.wait(1) until _G.COMBOWICK_ACTIVE == false
		showExpiredPopup(function()
			-- Unload the GUI and clear ALL state so nothing persists
			Library:Unload()
			_G.COMBOWICK_FREE    = nil
			_G.COMBOWICK_ACTIVE  = nil
			_G.COMBOWICK_KEY     = nil
		end)
	end)
end