-- Protected Script (Filipino)
-- Script ID: b793b9c57cf2865cf0c6a393a229ef5d
-- Created: 2025-10-22T20:35:40.840Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local Fluent = loadstring(game:HttpGet("https://github.com/dawid-scripts/Fluent/releases/latest/download/main.lua"))()
local CoreModule = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/PET/refs/heads/main/jurrasiccccc"))()

local Window = Fluent:CreateWindow({
    Title = "COMB0_WICK",
    SubTitle = "",
    TabWidth = 160,
    Size = UDim2.fromOffset(580, 460),
    Acrylic = true,
    Theme = "Dark",
    MinimizeKey = Enum.KeyCode.LeftControl
})

local Tabs = {
    ReadThis = Window:AddTab({ Title = "Basahin mona", Icon = "info" }),
    Main = Window:AddTab({ Title = "Main", Icon = "home" }),
    Shop = Window:AddTab({ Title = "Tindahan", Icon = "shopping-cart" }),
    Gamepass = Window:AddTab({ Title = "Mga Pagpasa ng Laro", Icon = "gift" })
}

-- Rejoin Button
Tabs.ReadThis:AddButton({
    Title = "This is for trolling your friends, lol\n:Enabling shop features will not allow you to play!",
    Description = "",
    Callback = function()
        Fluent:Notify({
            Title = "R",
            Content = "T",
            Duration = 2
        })
        task.wait(0.5)
       -- game:GetService("TeleportService"):Teleport(game.PlaceId, game:GetService("Players").LocalPlayer)
    end
})

-- Initialize the core module
CoreModule:Init()

-- Main Tab
local CoinInput = Tabs.Main:AddInput("CoinInput", {
    Title = "Halaga ng Barya",
    Default = "10000",
    Placeholder = "Enter amount",
    Numeric = true,
    Finished = true,
    Callback = function(Value)
        local amount = tonumber(Value)
        if amount and amount > 0 then
            CoreModule:SetCoinAmount(amount)
        end
    end
})

local CoinToggle = Tabs.Main:AddToggle("BitcoinToggle", {
    Title = "Bigyan ng Halaga ng mga Barya",
    Default = false,
    Callback = function(Value)
        CoreModule:ToggleCoins(Value)
        if Value then
            Fluent:Notify({
                Title = "Tagumpay",
                Content = "Binago ang mga barya sa" .. tostring(CoreModule:GetCoinAmount()),
                Duration = 2
            })
        end
    end
})

-- Shop Tab
local DinosaurPurchaseToggle = Tabs.Shop:AddToggle("DinosaurToggle", {
    Title = "Bypass Dinosaur Pagbili",
    Default = false,
    Callback = function(Value)
        CoreModule:ToggleDinosaurBypass(Value)
        if Value then
            Fluent:Notify({
                Title = "Tagumpay",
                Content = "Pinagana ang bypass sa pagbili ng dinosaur",
                Duration = 2
            })
        end
    end
})

local UnlockAllButton = Tabs.Shop:AddButton({
    Title = "I - unlock ang Lahat ng Dinosaur",
    Callback = function()
        CoreModule:UnlockAllDinosaurs()
        Fluent:Notify({
            Title = "Tagumpay",
            Content = "Na - unlock nang biswal ang lahat ng mga dinosaur",
            Duration = 3
        })
    end
})

-- Gamepass Tab
local GamepassToggle = Tabs.Gamepass:AddToggle("GamepassToggle", {
    Title = "Bypass ang Lahat ng Game Passes",
    Default = false,
    Callback = function(Value)
        CoreModule:ToggleAllGamepasses(Value)
        if Value then
            Fluent:Notify({
                Title = "Tagumpay",
                Content = "Naka - enable ang lahat ng game pass",
                Duration = 2
            })
        end
    end
})

Tabs.Gamepass:AddToggle("PlayableAI", {
    Title = "I - unlock ang Playable AI",
    Default = false,
    Callback = function(Value)
        CoreModule:ToggleGamepass(716086049, Value)
        if Value then
            Fluent:Notify({
                Title = "Tagumpay",
                Content = "Na - unlock ang nalalaro na AI",
                Duration = 2
            })
        end
    end
})

Tabs.Gamepass:AddToggle("StealthPass", {
    Title = "I - unlock ang Stealth Pass",
    Default = false,
    Callback = function(Value)
        CoreModule:ToggleGamepass(716240706, Value)
        if Value then
            Fluent:Notify({
                Title = "Tagumpay",
                Content = "Na - unlock ang Stealth Pass",
                Duration = 2
            })
        end
    end
})

-- Rejoin Button
Tabs.ReadThis:AddButton({
    Title = "Muling sumali sa Server",
    Description = "",
    Callback = function()
        Fluent:Notify({
            Title = "Rejoining...",
            Content = "Pag - teleport sa iyo pabalik sa laro",
            Duration = 2
        })
        task.wait(0.5)
        game:GetService("TeleportService"):Teleport(game.PlaceId, game:GetService("Players").LocalPlayer)
    end
})

Window:SelectTab(1)