-- Protected Script (Japanese)
-- Script ID: c17da1c58fcf3b6bdd486f9cf24e5b22
-- Created: 2025-10-20T23:12:55.923Z
-- Source: External API
-- Auto-generated by Lua Script Vault


local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

-- Load Core Module from GitHub (replace with your raw GitHub link)
local Module = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/refs/heads/main/Jurrasicscript"))()

-- Initialize connections
Module.initConnections()

-- Create Window
local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Icon = 7734068321,
    NotifySide = "Right",
    ShowCustomCursor = true,
    Size = UDim2.new(0, 500, 0, 400),
})

-- Create Tabs
local Tabs = {
    Main = Window:AddTab("メイン", "zap"),
    Amber = Window:AddTab("アンバー", "gem"),
    Utility = Window:AddTab("設定", "wrench"),
}

-- Main Tab - Walkspeed
local MainWalkspeed = Tabs.Main:AddLeftGroupbox("歩行速度", "activity")
MainWalkspeed:AddToggle("WalkspeedToggle", {
    Text = "歩行速度を有効にする",
    Default = false,
    Callback = function(Value)
        Module.toggleWalkspeed(Value)
    end,
})
MainWalkspeed:AddSlider("WalkspeedSlider", {
    Text = "歩行速度値",
    Default = 16,
    Min = 1,
    Max = 150,
    Rounding = 1,
    Callback = function(Value)
        Module.updateWalkspeed(Value)
    end,
})

-- Main Tab - Animal Farm
local MainNPC = Tabs.Main:AddLeftGroupbox("動物農場", "crosshair")
MainNPC:AddToggle("ESPトグル", {
    Text = "ESP名",
    Default = false,
    Callback = function(Value)
        Module.toggleESP(Value)
    end,
})
MainNPC:AddToggle("HighlightToggle", {
    Text = "ESPマーカー",
    Default = false,
    Callback = function(Value)
        Module.toggleHighlight(Value)
    end,
})
MainNPC:AddToggle("NPCテレポートトグル", {
    Text = "ヤギにテレポート",
    Default = false,
    Callback = function(Value)
        Module.toggleNPCTeleport(Value)
    end,
})
MainNPC:AddSlider("NPCDistance", {
    Text = "後方の距離",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.npcBehindDistance = Value
        if Module.State.npcTeleportEnabled and Module.State.currentNPCTarget then
            Module.anchorToNPC(Module.State.currentNPCTarget)
        end
    end,
})
MainNPC:AddButton({
    Text = "次のNPC",
    Func = function()
        if Module.State.npcTeleportEnabled then
            local newTarget = Module.switchToNextNPC()
            if newTarget then
                Module.State.currentNPCTarget = newTarget
                Module.anchorToNPC(Module.State.currentNPCTarget)
            end
        end
    end,
})

-- Main Tab - Boss Farm
local MainBoss = Tabs.Main:AddLeftGroupbox("ボス農場", "skull")
MainBoss:AddToggle("BossTeleportToggle", {
    Text = "Dレックスのボスへテレポート",
    Default = false,
    Callback = function(Value)
        Module.toggleBossTeleport(Value)
    end,
})
MainBoss:AddSlider("ボス距離", {
    Text = "後方の距離",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.bossBehindDistance = Value
        if Module.State.bossTeleportEnabled and Module.State.currentBossTarget then
            Module.anchorToBoss(Module.State.currentBossTarget)
        end
    end,
})
MainBoss:AddButton({
    Text = "次のボス",
    Func = function()
        if Module.State.bossTeleportEnabled then
            local newTarget = Module.switchToNextBoss()
            if newTarget then
                Module.State.currentBossTarget = newTarget
                Module.anchorToBoss(Module.State.currentBossTarget)
            end
        end
    end,
})

-- Main Tab - Combat
local MainCombat = Tabs.Main:AddRightGroupbox("戦闘", "sword")
MainCombat:AddToggle("AutoAttackToggle", {
    Text = "オートアタック",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoAttack(Value)
    end,
})
MainCombat:AddToggle("AutoHeavyToggle", {
    Text = "コンビネーションジャケット",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoHeavy(Value)
    end,
})
MainCombat:AddButton({
    Text = "瞬時の絶滅",
    Func = function()
        Module.executeInstantDespawn()
    end,
})

-- Main Tab - Player Farm
local MainPlayer = Tabs.Main:AddRightGroupbox("プレイヤー農場", "users")
MainPlayer:AddToggle("テレポートトグル", {
    Text = "プレイヤーへのテレポート",
    Default = false,
    Callback = function(Value)
        Module.State.teleporting = Value
        if Module.State.teleporting then
            Module.State.playerIndex = 0
            Module.State.currentTarget = Module.getNextTarget()
            if Module.State.currentTarget then
                Module.anchorToPlayer(Module.State.currentTarget)
            end
        else
            Module.State.currentTarget = nil
        end
    end,
})
MainPlayer:AddToggle("TargetMovingToggle", {
    Text = "ターゲット移動中",
    Default = true,
    Callback = function(Value)
        Module.State.targetMovingPlayers = Value
        if not Module.State.targetMovingPlayers and not Module.State.targetStillPlayers then
            Module.State.targetStillPlayers = true
        end
    end,
})
MainPlayer:AddToggle("TargetStillToggle", {
    Text = "ターゲットスタンディング",
    Default = true,
    Callback = function(Value)
        Module.State.targetStillPlayers = Value
        if not Module.State.targetMovingPlayers and not Module.State.targetStillPlayers then
            Module.State.targetMovingPlayers = true
        end
    end,
})
MainPlayer:AddSlider("BehindDistance", {
    Text = "後方の距離",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.behindDistance = Value
        if Module.State.teleporting and Module.State.currentTarget then
            Module.anchorToPlayer(Module.State.currentTarget)
        end
    end,
})
MainPlayer:AddButton({
    Text = "次のターゲット",
    Func = function()
        if Module.State.teleporting then
            local validPlayers = Module.getValidPlayers()
            if #validPlayers > 0 then
                Module.State.currentTarget = Module.getNextTarget()
                if Module.State.currentTarget then
                    Module.anchorToPlayer(Module.State.currentTarget)
                end
            end
        end
    end,
})

-- Amber Tab - V1
local AmberV1 = Tabs.Amber:AddLeftGroupbox("アンバーV 1", "gem")
AmberV1:AddToggle("AmberV 1トグル", {
    Text = "アンバーコレクション",
    Default = false,
    Callback = function(Value)
        Module.toggleAmberCollectionSwim(Value)
    end,
})

-- Amber Tab - V2
local AmberV2 = Tabs.Amber:AddRightGroupbox("アンバーV 2", "zap")
AmberV2:AddToggle("AmberV 2トグル", {
    Text = "恐竜コインv 2を集める",
    Default = false,
    Callback = function(Value)
        Module.toggleAmberCollection(Value)
    end,
})
AmberV2:AddToggle("自動スポーン切り替え", {
    Text = "自動蘇生",
    Default = false,
    Callback = function(Value)
        Module.State.AUTO_SPAWN_ENABLED = Value
        if Value then
            Module.State.lastVisibleGuis = {}
        end
    end,
})
AmberV2:AddDropdown("DinoSelection", {
    Values = Module.allDinosaurs,
    Default = "Gallimimus",
    Text = "恐竜を選択",
    Callback = function(Value)
        Module.State.selectedDino = Value
        Module.State.SPAWN_ARGS = { [1] = Value }
    end,
})
AmberV2:AddButton({
    Text = "手動出撃が選択されました",
    Func = function()
        Module.executeSpawn()
    end,
})
AmberV2:AddSlider("AmberTimeout", {
    Text = "タイムアウト(秒)",
    Default = 15,
    Min = 5,
    Max = 60,
    Rounding = 1,
    Callback = function(Value)
        Module.State.amberAttemptTimeout = Value
    end,
})

-- Amber Tab - V3 (Premium)
local AmberV3 = Tabs.Amber:AddLeftGroupbox("より速いバージョンの琥珀", "zap")
local linkText = "Buy Premium Best DinoCoin Script here:\nhttps://discord.gg/9FWBQnVXCy"
AmberV3:AddLabel(linkText)
AmberV3:AddButton("Copy Link", function()
    if setclipboard then
        setclipboard("https://discord.gg/9FWBQnVXCy")
    elseif toclipboard then
        toclipboard("https://discord.gg/9FWBQnVXCy")
    else
        warn("Clipboard not supported in this executor")
    end
end)

-- Utility Tab - Anti-Void
local UtilityAntiVoid = Tabs.Utility:AddLeftGroupbox("アンチ・ヴォイド", "shield")
UtilityAntiVoid:AddToggle("AntiVoidToggle", {
    Text = "虚空に対抗する",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableAntiVoid()
        else
            Module.disableAntiVoid()
        end
    end,
})

-- Utility Tab - Other
local UtilityOther = Tabs.Utility:AddLeftGroupbox("その他", "zap")
UtilityOther:AddToggle("NoclipToggle", {
    Text = "Noclip",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableNoclip()
        else
            Module.disableNoclip()
        end
    end,
})
UtilityOther:AddToggle("AntiAFKToggle", {
    Text = "アンチAFK",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableAntiAfk()
        else
            Module.disableAntiAfk()
        end
    end,
})
UtilityOther:AddToggle("StaffWatchToggle", {
    Text = "禁止ハンマーを探しています（スタッフウォッチ）",
    Default = false,
    Callback = function(Value)
        Module.toggleStaffWatch(Value)
    end,
})

-- Utility Tab - Combat
local Combat = Tabs.Utility:AddRightGroupbox("戦闘", "sword")
Combat:AddToggle("AutoAttackToggle", {
    Text = "オートアタック",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoAttack(Value)
    end,
})
Combat:AddToggle("AutoHeavyToggle", {
    Text = "コンビネーションジャケット",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoHeavy(Value)
    end,
})
Combat:AddButton({
    Text = "素早い自殺（ドスポーン）",
    Func = function()
        Module.executeInstantDespawn()
    end,
})

-- Utility Tab - UI Settings
local UISettings = Tabs.Utility:AddRightGroupbox("UI 設定", "settings")
UISettings:AddToggle("KeybindMenuOpen", {
    Default = Library.KeybindFrame.Visible,
    Text = "キーバインドメニューを開く",
    Callback = function(value)
        Library.KeybindFrame.Visible = value
    end,
})
UISettings:AddToggle("ShowCustomCursor", {
    Text = "カスタムカーソル",
    Default = true,
    Callback = function(Value)
        Library.ShowCustomCursor = Value
    end,
})
UISettings:AddDropdown("NotificationSide", {
    Values = { "Left", "Right" },
    Default = "Right",
    Text = "通知側",
    Callback = function(Value)
        Library:SetNotifySide(Value)
    end,
})
UISettings:AddButton("Unload", function()
    Library:Unload()
end)

-- Setup Theme and Save Manager
ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("ComboChronicle")
SaveManager:SetFolder("ComboChronicle")
SaveManager:BuildConfigSection(Tabs.Utility)
ThemeManager:ApplyToTab(Tabs.Utility)

-- Cleanup on close
game:BindToClose(Module.cleanup)
SaveManager:LoadAutoloadConfig()