-- Protected Script (Portuguese)
-- Script ID: e34a7d3b4e447320bdcec47b63ab418b
-- Created: 2025-12-31T16:39:01.973Z
-- Source: External API
-- Auto-generated by Lua Script Vault

local CoreGui = game:GetService("CoreGui")
local guiName = "LinoriaGui"
local targetParent = gethui and gethui() or CoreGui

for _, Interface in ipairs(targetParent:GetChildren()) do
    if Interface.Name == guiName then
        pcall(function()
            Interface:Destroy()
        end)
    end
end

if gethui then
    for _, Interface in ipairs(CoreGui:GetChildren()) do
        if Interface.Name == guiName then
            pcall(function()
                Interface:Destroy()
            end)
        end
    end
end

_G.ComboWickLoaded = nil
_G.VaultInitialized = nil
_G.VaultVersionToken = nil
getgenv().VaultReady = nil

task.wait(0.1)

_G.ComboWickLoaded = true

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local VaultModule = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/MainModule/refs/heads/main/MainModule"))()
local HttpService = game:GetService("HttpService")
local RbxAnalytics = game:GetService("RbxAnalyticsService")
local Players = game:GetService('Players')
local LocalPlayer = Players.LocalPlayer

getgenv().VaultReady = false

VaultModule.VALIDATION_STATE.sessionToken = VaultModule.generateSessionToken("init")

local clientId = tostring(RbxAnalytics:GetClientId() or "")
if clientId == "" then
    return {
        success = false,
        error = "Não há ID do cliente"
    }
end

local encryptedClientId = VaultModule.encrypt(clientId, VaultModule.CONFIG.MASTER_KEY)

local versionValid, versionMessage, fetchedToken = VaultModule.checkVersionAndToken()
if not versionValid then
    Library:Notify({
        Title = 'Erro de Versão',
        Description = versionMessage,
        Time = 10,
    })
    return {
        success = false,
        error = "falha_na_verificação_de_versão",
        message = versionMessage
    }
end

if VaultModule.compareVersions(VaultModule.CONFIG.VERSION, '1.3.2') <= 0 then
    Library:Notify({
        Title = 'Atualização Necessária',
        Description = 'Esta versão não é mais suportada. Por favor, atualize para v' .. VaultModule.CONFIG.MIN_VERSION .. '+',
        Time = 10,
    })
    return {
        success = false,
        error = "versão_obsoleta",
        message = "Versão não mais suportada"
    }
end

_G.VaultInitialized = true
_G.VaultVersionToken = fetchedToken

local whitelisted, matchData, errorType = VaultModule.isClientIdWhitelisted(clientId, encryptedClientId)

if not whitelisted or errorType == "acesso_negado" or errorType == "deteção_de_alteração" or errorType == "chave_expirada" then
    local Window = Library:CreateWindow({
        Title = "COMBO_WICK",
        Footer = "Sistema de Validação v" .. VaultModule.CONFIG.VERSION,
        Icon = 18928661286,
        Size = UDim2.new(0, 580, 0, 380),
        Resizable = false,
        ShowCustomCursor = false,
    })
    
    local Tabs = {
        Validação = Window:AddTab("Validação", "key"),
        Informações = Window:AddTab("Informações e Links", "info")
    }
        
    local validationComplete = false
    local validationSuccess = false
    
    local MainGroup = Tabs.Validação:AddLeftGroupbox("Insira sua Chave de Validação")
    
    local savedKey = VaultModule.loadKey()
    local keyInputValue = savedKey or ""
    
    MainGroup:AddInput("KeyInput", {
        Default = keyInputValue,
        Numeric = false,
        Finished = true,
        ClearTextOnFocus = false,
        Text = "Insira sua chave",
        Placeholder = "Cole sua chave aqui...",
        Callback = function(value)
            keyInputValue = value
        end
    })
    
    MainGroup:AddButton({
        Text = "✅ Enviar Chave",
        Func = function()
            local key = VaultModule.trim(keyInputValue)
            
            if key == "" then
                Library:Notify({
                    Title = "Chave Inválida",
                    Description = "Por favor, insira uma chave de validação",
                    Time = 3
                })
                return
            end
            
            local success = VaultModule.validateKey(key, clientId, Library)
            
            if success then
                validationSuccess = true
                validationComplete = true
                
                wait(2)
                Library:Unload()
            end
        end
    })
    
    MainGroup:AddButton({
        Text = "🔗 Obter Link de Chave",
        Func = function()
            setclipboard("https://chronicle-secure-admin-dashboard-kappa.vercel.app/verify/provider-select")
            Library:Notify({
                Title = "Copiado",
                Description = "Link de chave copiado para a área de transferência",
                Time = 2
            })
        end
    })
    
    local LinksGroup = Tabs.Informações:AddLeftGroupbox("Links Úteis")

    LinksGroup:AddButton({
        Text = "Canal do YouTube",
        Func = function()
            setclipboard("https://www.youtube.com/@COMBO_WICK")
            Library:Notify({
                Title = "Copiado",
                Description = "Link do YouTube copiado para a área de transferência",
                Time = 2
            })
        end
    })
    
    LinksGroup:AddButton({
        Text = "Servidor do Discord",
        Func = function()
            setclipboard("https://discord.gg/9FWBQnVXCy")
            Library:Notify({
                Title = "Copiado",
                Description = "Link do Discord copiado para a área de transferência",
                Time = 2
            })
        end
    })
    
    local HWIDGroup = Tabs.Informações:AddRightGroupbox("Informações de HWID")
    
    HWIDGroup:AddLabel({
        Text = "Seu HWID:",
        DoesWrap = false,
    })
    
    HWIDGroup:AddLabel({
        Text = clientId,
        DoesWrap = true,
    })
    
    HWIDGroup:AddDivider()
    
    HWIDGroup:AddButton({
        Text = "📋 Copiar HWID",
        Func = function()
            setclipboard(clientId)
            Library:Notify({
                Title = "Copiado",
                Description = "HWID copiado para a área de transferência",
                Time = 2
            })
        end
    })
    
    local timeout = 300
    local elapsed = 0
    while not validationComplete and elapsed < timeout do
        task.wait(1)
        elapsed = elapsed + 1
    end
    
    if validationSuccess then
        task.wait(1)
        
        VaultModule.resetCache(clientId)
        
        whitelisted, matchData, errorType = VaultModule.isClientIdWhitelisted(clientId, encryptedClientId)
        
        if whitelisted then
            VaultModule.startSessionMonitoring(clientId)
            
            getgenv().VaultReady = true
            
            Library:Notify({
                Title = "Carregando",
                Description = "Carregando script...",
                Time = 2
            })
            
            local scriptApiUrl = VaultModule.getScriptApiUrl()
            local defaultScriptUrl = VaultModule.getDefaultScriptUrl()
            
            local scriptToLoad = defaultScriptUrl
            
            local success, response = pcall(function()
                return VaultModule.httpRequest({
                    Url = scriptApiUrl,
                    Method = 'GET',
                })
            end)
            
            if success and response and response.Body then
                local parseSuccess, data = pcall(function()
                    return HttpService:JSONDecode(response.Body)
                end)
                
                if parseSuccess and data then
                    local gameIdStr = tostring(game.PlaceId)
                    if data[gameIdStr] then
                        scriptToLoad = data[gameIdStr]
                    elseif data['default'] then
                        scriptToLoad = data['default']
                    end
                end
            end
            
            VaultModule.memoryCleanup:disconnectAll()
            
            if type(scriptToLoad) == 'table' then
                for i, url in ipairs(scriptToLoad) do
                    spawn(function()
                        pcall(function()
                            loadstring(game:HttpGet(url:match('^[^%s]+')))()
                        end)
                    end)
                end
            else
                spawn(function()
                    pcall(function()
                        loadstring(game:HttpGet(scriptToLoad:match('^[^%s]+')))()
                    end)
                end)
            end
            
            return {
                success = true,
                whitelisted = true,
                matchData = matchData,
                validated = true,
                sessionToken = VaultModule.VALIDATION_STATE.sessionToken
            }
        else
            return {
                success = false,
                error = "não_autorizado_após_validação"
            }
        end
    else
        return {
            success = false,
            error = "validação_cancelada"
        }
    end
end

if whitelisted then
    VaultModule.startSessionMonitoring(clientId)
    
    getgenv().VaultReady = true
    
    Library:Notify({
        Title = "Autenticado",
        Description = "Carregando script...",
        Time = 2
    })
    
    local scriptApiUrl = VaultModule.getScriptApiUrl()
    local defaultScriptUrl = VaultModule.getDefaultScriptUrl()
    
    local scriptToLoad = defaultScriptUrl
    
    local success, response = pcall(function()
        return VaultModule.httpRequest({
            Url = scriptApiUrl,
            Method = 'GET',
        })
    end)
    
    if success and response and response.Body then
        local parseSuccess, data = pcall(function()
            return HttpService:JSONDecode(response.Body)
        end)
        
        if parseSuccess and data then
            local gameIdStr = tostring(game.PlaceId)
            if data[gameIdStr] then
                scriptToLoad = data[gameIdStr]
            elseif data['default'] then
                scriptToLoad = data['default']
            end
        end
    end
    
    VaultModule.memoryCleanup:disconnectAll()
    
    if type(scriptToLoad) == 'table' then
        for i, url in ipairs(scriptToLoad) do
            spawn(function()
                pcall(function()
                    loadstring(game:HttpGet(url:match('^[^%s]+')))()
                end)
            end)
        end
    else
        spawn(function()
            pcall(function()
                loadstring(game:HttpGet(scriptToLoad:match('^[^%s]+')))()
            end)
        end)
    end
    
    return {
        success = true,
        whitelisted = true,
        matchData = matchData,
        sessionToken = VaultModule.VALIDATION_STATE.sessionToken
    }
else
    return {
        success = false,
        whitelisted = false
    }
end