-- Korean Translation
-- Script ID: e56bbe848928949849ceeb5bc116defb
-- Updated: 2026-09-14T23:35:43.706Z
-- Auto-generated by Lua Script Vault

local MODULE_URL = "https://v0-supabase-secure-storage.vercel.app/api/script/a4d7437234f9ca565c0a53969a2b374a"
local Core = loadstring(game:HttpGet(MODULE_URL))()
local RUNNING = true
local BIOME_LIST, HttpService, Lighting, RARITY_COLOR, RARITY_LIST, RunService, TeleportService, Workspace, applyAntiLag, carrying, cloneref, commas, eggHost, eggKg, eggName, getRemote, hiddenParent, hrp, lp, myBasePos, myDroppedEgg, navTo, nightBlocked, onClean, pickTarget, randomName, selSet, stealEgg, track =
    Core.BIOME_LIST, Core.HttpService, Core.Lighting, Core.RARITY_COLOR, Core.RARITY_LIST, Core.RunService, Core.TeleportService, Core.Workspace, Core.applyAntiLag, Core.carrying, Core.cloneref, Core.commas, Core.eggHost, Core.eggKg, Core.eggName, Core.getRemote, Core.hiddenParent, Core.hrp, Core.lp, Core.myBasePos, Core.myDroppedEgg, Core.navTo, Core.nightBlocked, Core.onClean, Core.pickTarget, Core.randomName, Core.selSet, Core.stealEgg, Core.track
local Opt, Toggles
onClean(function() RUNNING = false end)

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
if _G.__feLib then pcall(function() _G.__feLib:Unload() end) end
local Library      = loadstring(game:HttpGet(repo .. "Library.lua"))()
local SaveManager  = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
_G.__feLib = Library
getgenv().Library = Library
Library.ShowCustomCursor = false
local Window = Library:CreateWindow({ Title = "COMBO_WICK", Footer = "v1", NotifySide = "Right", ShowCustomCursor = false, AutoShow = true, Size = UDim2.fromOffset(500, 400) })
pcall(function()
    local sg = Library.ScreenGui or (Library.Holder and Library.Holder.Parent)
    if sg and sg:IsA("ScreenGui") then sg.Name = randomName(); hiddenParent(sg) end
end)
Opt, Toggles = Library.Options, Library.Toggles
Core.bindOpt(Opt, Toggles)
local function on(k) local t = Toggles[k]; return t and t.Value end
local function notify(m) pcall(function() Library:Notify({ Title = "COMBO_WICK", Description = tostring(m), Time = 3 }) end) end

local Tab = Window:AddTab("파밍", "fish")
local FarmBox = Tab:AddLeftGroupbox("자동 훔치기")
FarmBox:AddDropdown("fe_rarities", { Values = RARITY_LIST, Default = {}, Multi = true, AllowNull = true, Text = "희귀도", Tooltip = "비움 = 모든 희귀도" })
FarmBox:AddDropdown("fe_areas", { Values = BIOME_LIST, Default = {}, Multi = true, AllowNull = true, Text = "지역", Tooltip = "비움 = 모든 지역" })
FarmBox:AddDropdown("fe_priority", { Values = { "Nearest", "Highest Weight" }, Default = "Nearest", Text = "대상" })
FarmBox:AddSlider("fe_movespeed", { Text = "속도", Default = 240, Min = 20, Max = 240, Rounding = 0 })
FarmBox:AddDivider()
FarmBox:AddToggle("fe_farm", { Text = "자동 파밍", Default = false })
FarmBox:AddToggle("fe_regrab", { Text = "다시 잡기", Default = true })
FarmBox:AddToggle("fe_esp", { Text = "알 ESP", Default = false })
FarmBox:AddDropdown("fe_esprarities", { Values = RARITY_LIST, Default = {}, Multi = true, AllowNull = true, Text = "ESP 희귀도" })

local StatusBox = Tab:AddRightGroupbox("상태")
local stLbl = StatusBox:AddLabel("상태: 대기")
local carLbl = StatusBox:AddLabel("운반 중: 아니요")
local fpsLbl = StatusBox:AddLabel("FPS: -")

local SwimBox = Tab:AddRightGroupbox("수영")
SwimBox:AddToggle("fe_swim", { Text = "수영", Default = false, Callback = function(v)
    Core.setSwim(v)
    if not v then local h = hrp(); if h then h.AssemblyLinearVelocity = Vector3.zero end end
end })
SwimBox:AddSlider("fe_swimspeed", { Text = "수영 속도", Default = 200, Min = 20, Max = 400, Rounding = 0, Tooltip = "CFrame 스텝 (서버가 허용하는 방식). 고무줄처럼 튕길 때까지 올리세요 -- 그 숫자가 당신 계정의 한계입니다. 넘으려면 실제 수영 속도 스탯을 높여야 합니다." })
SwimBox:AddLabel("WASD로 수영하세요. 되돌아가면 슬라이더를 낮추세요.", true)

local BaseBox = Tab:AddLeftGroupbox("기지")
BaseBox:AddToggle("fe_autohatch", { Text = "자동 부화", Default = false })
BaseBox:AddToggle("fe_autoequip", { Text = "자동 최고 장착", Default = false })
task.spawn(function()
    while RUNNING do
        if on("fe_autohatch") then
            pcall(function()
                local he = getRemote("EggSystem", "HatchEgg")
                local pe = Workspace:FindFirstChild("PlacedEggs")
                if he and pe then
                    for _, m in ipairs(pe:GetChildren()) do
                        if m:IsA("Model") and tonumber(m:GetAttribute("OwnerUserId")) == lp.UserId and m:GetAttribute("HatchReady") == true then
                            he:FireServer(m)
                        end
                    end
                end
            end)
        end
        task.wait(2)
    end
end)
task.spawn(function()
    while RUNNING do
        if on("fe_autoequip") then pcall(function() local e = getRemote("FishSystem", "EquipBestFish"); if e then e:FireServer() end end) end
        task.wait(5)
    end
end)

local farmState = "대기"
-- ============================================================================
-- GOD DESYNC: death-TP + anti-teleport hold + drop/regrab. Chain (per the manual exploit):
-- pick egg -> suicide + death-TP onto it -> steal -> anti-TP HOLD at the safe pos (carry the egg there) ~3s
-- -> drop it (ChaseFishSystem.DropCarriedEgg) -> release hold (insta-TP out) -> regrab the dropped egg.
-- Death only used to reach the egg (dying drops a carry); the CFrame anti-TP hold moves you WITH the egg.
-- ============================================================================
do
    local RSvc = game:GetService("ReplicatedStorage")
    local DropRemote = RSvc:FindFirstChild("ChaseFishSystem") and RSvc.ChaseFishSystem:FindFirstChild("DropCarriedEgg")
    local function hum() local c = lp.Character; return c and c:FindFirstChildWhichIsA("Humanoid") end
    local holdTarget = Vector3.new(26, 116, -65)   -- anti-TP hold spot; set live off the line each cycle
    local function linePos(offZ)                    -- a point offZ studs along TheLine.RedPart's local Z
        local line = Workspace:FindFirstChild("TheLine")
        local red = line and line:FindFirstChild("RedPart")
        if red and red:IsA("BasePart") then return (red.CFrame * CFrame.new(0, 0, offZ)).Position end
        return holdTarget
    end
    local function frontLine()  return linePos(10)  end   -- IN FRONT of the line = the safe side
    local function behindLine() return linePos(-10) end   -- BEHIND the line = the water side (drop here)
    local deathAnchor, antiHold, selfSet = nil, false, false
    local failCount = 0
    -- block AC kicks
    if hookmetamethod and newcclosure and getnamecallmethod then
        local old
        old = hookmetamethod(game, "__namecall", newcclosure(function(self, ...)
            if getnamecallmethod() == "Kick" and self == lp then return end
            return old(self, ...)
        end))
    end
    -- DEATH-TP: on respawn, slam the fresh HRP to deathAnchor for a window (respawn isn't AC-guarded)
    track(lp.CharacterAdded:Connect(function(char)
        if not deathAnchor then return end
        local a = deathAnchor
        local root = char:FindFirstChild("HumanoidRootPart")
        if not root then repeat root = char:FindFirstChild("HumanoidRootPart"); RunService.Heartbeat:Wait() until root or not char.Parent end
        if not root then return end
        local cf = CFrame.new(a)
        for _ = 1, 45 do
            if not char.Parent or deathAnchor ~= a then break end
            selfSet = true; root.CFrame = cf; root.AssemblyLinearVelocity = Vector3.zero; selfSet = false
            RunService.Heartbeat:Wait()
        end
        deathAnchor = nil
    end))
    -- ANTI-TP HOLD: re-apply holdTarget on Stepped + Heartbeat (out-applies the server's rubber-band)
    local function holdStep()
        if not antiHold then return end
        local root = hrp(); if not root or selfSet then return end
        if (root.Position - holdTarget).Magnitude > 6 then
            selfSet = true; root.CFrame = CFrame.new(holdTarget); root.AssemblyLinearVelocity = Vector3.zero; selfSet = false
        end
    end
    track(RunService.Stepped:Connect(holdStep))
    track(RunService.Heartbeat:Connect(holdStep))
    local function dropEgg() if DropRemote then pcall(function() DropRemote:FireServer() end) end end
    local function deathTpTo(pos)
        deathAnchor = pos
        local h = hum(); if h then pcall(function() h.Health = 0 end) end
        local t0 = os.clock()
        repeat RunService.Heartbeat:Wait() until (hrp() and (hrp().Position - pos).Magnitude < 14) or os.clock() - t0 > 9
    end
    -- STUCK RESET: kill with NO anchor -> normal respawn at base (breaks a lag/glitch loop where the steal never lands)
    local function respawnClean()
        deathAnchor = nil; antiHold = false
        local h = hum(); if h then pcall(function() h.Health = 0 end) end
        local t0 = os.clock()
        repeat RunService.Heartbeat:Wait() until (hrp() and hum() and hum().Health > 0 and os.clock() - t0 > 1.5) or os.clock() - t0 > 8
    end
    -- CFrame-step to a 3D point (same safe ~240/s rate as the farm, velocity zeroed -> no rubber-band).
    -- Used to drop DOWN into the water to the dropped egg, then back UP to the safe zone.
    local function tweenTo(pos, stopDist)
        stopDist = stopDist or 5
        local deadline = os.clock() + 15
        while RUNNING and on("fe_farm") and os.clock() < deadline do
            local r = hrp(); if not r then return end
            local delta = pos - r.Position
            local dist = delta.Magnitude
            if dist <= stopDist then r.AssemblyLinearVelocity = Vector3.zero; return end
            local dt = RunService.Heartbeat:Wait(); if typeof(dt) ~= "number" or dt <= 0 then dt = 1 / 60 end
            local step = math.min(dist, 240 * dt, 6)
            r.CFrame = CFrame.new(r.Position + delta.Unit * step) * (r.CFrame - r.CFrame.Position)
            r.AssemblyLinearVelocity = Vector3.zero
            r.AssemblyAngularVelocity = Vector3.zero
        end
    end
    -- THE auto-steal loop (fe_farm): death-TP onto egg -> steal -> anti-TP hold behind the line -> drop -> regrab -> base
    task.spawn(function()
        while RUNNING do
            if on("fe_farm") and nightBlocked() then
                farmState = "일시정지 (야간 벽)"; task.wait(0.5)
            elseif on("fe_farm") then
                pcall(function()
                    local t = pickTarget()
                    if not t then farmState = "일치하는 알 없음"; task.wait(0.5); return end
                    local _, host = eggHost(t); if not (host and host.Position) then task.wait(0.3); return end   -- 2nd return is the host BasePart
                    farmState = "알로 순간이동"
                    deathTpTo(host.Position + Vector3.new(0, 3, 0))
                    farmState = "훔치는 중"
                    stealEgg(t)
                    if carrying() then
                        holdTarget = frontLine()                      -- IN FRONT of the line = the safe spot (dynamic)
                        farmState = "선 앞 (안전)"
                        antiHold = true; task.wait(3)                 -- hold safe 3s, carrying the egg
                        holdTarget = behindLine()                     -- then cross BEHIND the line (into the water)
                        farmState = "선 뒤"
                        task.wait(3)                                  -- hold behind 3s
                        antiHold = false
                        farmState = "떨어뜨리기"
                        dropEgg(); task.wait(0.4)                     -- drop the egg behind the line
                        farmState = "다시 잡기"
                        local d = myDroppedEgg()
                        if d then
                            local _, dh = eggHost(d)
                            if dh and dh.Position then tweenTo(dh.Position, 6) end   -- tween onto the dropped egg
                            stealEgg(d)                                              -- regrab it
                        end
                        farmState = "기지로"
                        local base = myBasePos()
                        if base then tweenTo(base, 8) end             -- go to base
                        failCount = 0                                 -- steal landed, clear the stuck counter
                    else
                        -- steal didn't land (lag/glitch). Don't loop-kill onto the same egg forever:
                        failCount = failCount + 1
                        if failCount >= 3 then
                            farmState = "막힘 -> 기지에서 리스폰"
                            antiHold = false
                            respawnClean()                            -- kill w/ NO anchor => spawn at base, then resume
                            failCount = 0
                            task.wait(0.5)
                        end
                    end
                end)
                task.wait(0.2)
            else
                farmState = "대기"; task.wait(0.4)
            end
        end
    end)
end
task.spawn(function()
    while RUNNING do
        pcall(function()
            stLbl:SetText("상태: " .. farmState)
            carLbl:SetText(carrying() and "운반 중: 예" or "운반 중: 아니요")
            fpsLbl:SetText("FPS: " .. tostring(Core.getFps()))
        end)
        task.wait(0.2)
    end
end)
task.spawn(function()
    local low = 0
    while RUNNING do
        if Core.getFps() < 15 then low = low + 1 else low = 0 end
        if low >= 4 and not on("fe_antilag") then
            pcall(function() if Toggles.fe_antilag then Toggles.fe_antilag:SetValue(true) end end)
            pcall(applyAntiLag)
            notify("낮은 FPS - 랙 감소 자동 활성화됨")
            low = 0
        end
        task.wait(1)
    end
end)

local espCache = {}
local function makeEsp(m)
    local col = RARITY_COLOR[tostring(m:GetAttribute("Rarity"))] or Color3.fromRGB(0, 255, 128)
    local hl = Instance.new("Highlight")
    hl.FillColor = col; hl.OutlineColor = Color3.fromRGB(255, 255, 255); hl.FillTransparency = 0.6
    hl.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop; hl.Adornee = m; hl.Parent = m
    local bb = Instance.new("BillboardGui")
    bb.Size = UDim2.fromOffset(220, 44); bb.StudsOffset = Vector3.new(0, 3.5, 0); bb.AlwaysOnTop = true
    bb.Adornee = m.PrimaryPart or m:FindFirstChildWhichIsA("BasePart"); bb.Parent = m
    local tl = Instance.new("TextLabel")
    tl.Size = UDim2.fromScale(1, 1); tl.BackgroundTransparency = 1; tl.TextColor3 = col
    tl.TextStrokeTransparency = 0.3; tl.Font = Enum.Font.GothamBold; tl.TextSize = 13; tl.Parent = bb
    return { hl = hl, bb = bb, tl = tl }
end
local function espLabel(m)
    return eggName(m) .. "  [" .. tostring(m:GetAttribute("Rarity") or "?") .. "]\n" .. commas(eggKg(m)) .. " kg"
end
local function clearEsp(e) pcall(function() e.hl:Destroy() end); pcall(function() e.bb:Destroy() end) end
task.spawn(function()
    while RUNNING do
        if on("fe_esp") then
            local eggs = Workspace:FindFirstChild("SpawnedEggs")
            local rset = selSet("fe_esprarities")
            local present = {}
            if eggs then
                for _, m in ipairs(eggs:GetChildren()) do
                    local rarOk = (not rset) or (m:GetAttribute("Rarity") and rset[m:GetAttribute("Rarity")])
                    if m:IsA("Model") and eggHost(m) and rarOk then
                        present[m] = true
                        local e = espCache[m]
                        if not e or not (e.hl and e.hl.Parent) then e = makeEsp(m); espCache[m] = e end
                        pcall(function() e.tl.Text = espLabel(m) end)
                    end
                end
            end
            for m, e in pairs(espCache) do if not present[m] then clearEsp(e); espCache[m] = nil end end
        elseif next(espCache) then
            for m, e in pairs(espCache) do clearEsp(e); espCache[m] = nil end
        end
        task.wait(0.5)
    end
end)
onClean(function() for m, e in pairs(espCache) do clearEsp(e) end end)

local SettingsTab = Window:AddTab("설정", "settings")
local ProtBox = SettingsTab:AddLeftGroupbox("보호")
ProtBox:AddToggle("fe_antilag", { Text = "랙 감소", Default = false, Callback = function(v) if v then task.spawn(applyAntiLag) end end })
ProtBox:AddToggle("fe_antiafk", { Text = "AFK 방지", Default = true })
ProtBox:AddDropdown("fe_time", { Values = { "Off", "Day", "Night", "Sunrise", "Sunset" }, Default = "Off", Text = "시간" })
local VirtualUser = cloneref(game:GetService("VirtualUser"))
track(lp.Idled:Connect(function()
    if RUNNING and on("fe_antiafk") then pcall(function() VirtualUser:CaptureController(); VirtualUser:ClickButton2(Vector2.new()) end) end
end))
local TIME_CT = { Day = 14, Night = 0, Sunrise = 6.5, Sunset = 18 }
track(RunService.Heartbeat:Connect(function()
    if not RUNNING then return end
    local t = Opt.fe_time and Opt.fe_time.Value
    local ct = t and TIME_CT[t]
    if ct then pcall(function() Lighting.ClockTime = ct end) end
end))

local hopping = false
local function httpGetJson(url)
    local body
    local req = (syn and syn.request) or (http and http.request) or (fluxus and fluxus.request) or http_request or request or (getgenv and getgenv().request)
    if req then local ok, res = pcall(req, { Url = url, Method = "GET" }); if ok and type(res) == "table" then body = res.Body or res.body end end
    if not body or body == "" then local ok, res = pcall(function() return game:HttpGet(url) end); if ok then body = res end end
    if not body or body == "" then return nil end
    local ok, data = pcall(function() return HttpService:JSONDecode(body) end)
    if ok then return data end
    return nil
end
local function serverHop()
    if hopping then return end
    hopping = true
    local placeId = game.PlaceId
    local list, cursor, scanned = {}, nil, 0
    for _ = 1, 10 do
        local url = ("https://games.roblox.com/v1/games/%d/servers/Public?sortOrder=Asc&limit=100"):format(placeId)
        if cursor then url = url .. "&cursor=" .. cursor end
        local data = httpGetJson(url)
        if not data or type(data.data) ~= "table" then break end
        for _, s in ipairs(data.data) do
            scanned += 1
            if type(s.playing) == "number" and s.id ~= game.JobId and s.playing < (s.maxPlayers or 999) then list[#list + 1] = s end
        end
        if data.nextPageCursor and data.nextPageCursor ~= "" then cursor = data.nextPageCursor else break end
        task.wait(0.1)
    end
    if #list == 0 then notify(scanned == 0 and "Hop: 익스큐터가 API 차단" or "Hop: 접속 가능한 서버 없음"); hopping = false; return end
    table.sort(list, function(a, b) return a.playing < b.playing end)
    notify(("Hop: 서버 %d개 발견"):format(#list))
    local idx, conn = 0, nil
    local function tryNext()
        idx = idx + 1
        local s = list[idx]
        if not s then if conn then conn:Disconnect() end; hopping = false; notify("Hop: 모두 실패"); return end
        pcall(function() TeleportService:TeleportToPlaceInstance(placeId, s.id, lp) end)
    end
    conn = TeleportService.TeleportInitFailed:Connect(function(who) if who == lp then task.wait(0.5); tryNext() end end)
    tryNext()
    task.delay(25, function() if conn then conn:Disconnect() end; hopping = false end)
end
local ServerBox = SettingsTab:AddRightGroupbox("서버")
ServerBox:AddButton({ Text = "가장 적은 서버 접속", Func = function() task.spawn(serverHop) end })
ServerBox:AddButton({ Text = "재접속", Func = function() pcall(function() TeleportService:TeleportToPlaceInstance(game.PlaceId, game.JobId, lp) end) end })
local MenuBox = SettingsTab:AddRightGroupbox("메뉴")
MenuBox:AddButton({ Text = "언로드", Func = function()
    Core.setSwim(false)
    for _, k in ipairs({ "fe_farm", "fe_swim", "fe_esp", "fe_antilag", "fe_antiafk", "fe_autohatch", "fe_autoequip" }) do local t = Toggles[k]; if t then pcall(function() t:SetValue(false) end) end end
    pcall(function() if _G.__CW_CLEAN then _G.__CW_CLEAN() end end)
    pcall(function() Library:Unload() end)
end })
MenuBox:AddLabel("메뉴 토글"):AddKeyPicker("MenuKeybind", { Default = "RightShift", NoUI = true, Text = "메뉴 토글" })
Library.ToggleKeybind = Opt.MenuKeybind

local FEEDBACK_URL = "https://v0-secure-discord-proxy.vercel.app/api/v2sender"
local FEEDBACK_VERSION = "combowick-stealfisheggs-1.0"
local _request = request or (syn and syn.request) or http_request
local function fbTrim(s) return (tostring(s or ""):gsub("^%s*(.-)%s*$", "%1")) end
local function fbHWID()
    local ok, id = pcall(function() return game:GetService("RbxAnalyticsService"):GetClientId() end)
    if ok and type(id) == "string" and id ~= "" then return id end
    return tostring(lp and lp.UserId or 0)
end
local FB_HWID = fbHWID()
local FB_ERRMAP = {
    empty = "메시지가 비어 있습니다.", no_links = "링크는 허용되지 않습니다.",
    too_long = "메시지가 너무 깁니다 (최대 500자).",
    rate_limited = "한도에 도달했습니다. 나중에 다시 시도하세요.",
    network = "네트워크 오류.", no_request = "익스큐터가 요청을 보낼 수 없습니다.",
    bad_response = "서버가 예기치 않은 응답을 반환했습니다.",
    unreachable = "익스큐터가 서버에 연결할 수 없습니다. 다른 것을 사용해 보세요.",
}
local function sendFeedback(ftype, msg)
    if not _request then return false, "no_request" end
    local ok, res = pcall(function()
        return _request({
            Url = FEEDBACK_URL, Method = "POST",
            Headers = { ["Content-Type"] = "application/json" },
            Body = HttpService:JSONEncode({ type = ftype, message = msg, hwid = FB_HWID, placeId = tostring(game.PlaceId), username = lp and lp.Name or "?", version = FEEDBACK_VERSION }),
        })
    end)
    if not ok or not res then return false, "network" end
    if type(res) == "string" then return false, "unreachable" end
    if type(res) ~= "table" then return false, "network" end
    local code = res.StatusCode or res.status_code or res.Status or res.status
    if type(code) == "number" and code ~= 200 and code ~= 201 and code ~= 204 then return false, "http_" .. tostring(code) end
    local body = res.Body or res.body
    if type(body) ~= "string" or body == "" then return false, "bad_response" end
    local dok, data = pcall(function() return HttpService:JSONDecode(body) end)
    if not dok or type(data) ~= "table" then return false, "bad_response" end
    if data.success == true then return true end
    return false, tostring(data.error or "unknown")
end
local SuggestTab = Window:AddTab("제안", "message-square")
local FG = SuggestTab:AddLeftGroupbox("제안 / 도움말")
FG:AddDropdown("FeedbackType", { Text = "유형", Values = { "Suggestion", "Bug", "Help" }, Default = "Suggestion" })
FG:AddInput("FeedbackMsg", { Default = "", Numeric = false, Finished = false, ClearTextOnFocus = false, Text = "메시지", Placeholder = "메시지를 입력하세요 (최대 500자, 링크 금지)" })
local fbStatus = FG:AddLabel("", true)
local FEEDBACK_COOLDOWN, lastFeedback = 20, 0
FG:AddButton({ Text = "보내기", Func = function()
    local now = tick()
    if now - lastFeedback < FEEDBACK_COOLDOWN then
        pcall(function() fbStatus:SetText(string.format("다시 보내기 전에 %d초 기다리세요.", math.ceil(FEEDBACK_COOLDOWN - (now - lastFeedback)))) end)
        return
    end
    local ftype = tostring((Opt.FeedbackType and Opt.FeedbackType.Value) or "Suggestion"):lower()
    local msg = fbTrim((Opt.FeedbackMsg and Opt.FeedbackMsg.Value) or "")
    if msg == "" then pcall(function() fbStatus:SetText("메시지가 비어 있습니다.") end); return end
    if #msg > 500 then pcall(function() fbStatus:SetText("너무 김 (최대 500자).") end); return end
    local low = msg:lower()
    if low:find("http", 1, true) or low:find("discord.gg", 1, true) or low:find("www.", 1, true) or low:find(".gg/", 1, true) then
        pcall(function() fbStatus:SetText("링크는 허용되지 않습니다.") end); return
    end
    pcall(function() fbStatus:SetText("전송 중...") end)
    task.spawn(function()
        local sok, err = sendFeedback(ftype, msg)
        if sok then
            lastFeedback = tick()
            pcall(function() fbStatus:SetText("전송됨. 감사합니다!") end)
            pcall(function() Opt.FeedbackMsg:SetValue("") end)
            notify("피드백이 전송되었습니다. 감사합니다!")
        else
            pcall(function() fbStatus:SetText(FB_ERRMAP[err] or ("실패: " .. tostring(err))) end)
        end
    end)
end })
FG:AddLabel("유형을 선택하고 메시지를 입력한 뒤 보내기를 누르세요. 링크 금지.", true)

SaveManager:SetLibrary(Library)
ThemeManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind", "FeedbackType", "FeedbackMsg" })
ThemeManager:SetFolder("StealFishEggs")
SaveManager:SetFolder("StealFishEggs")
ThemeManager:ApplyToTab(SettingsTab)
SaveManager:BuildConfigSection(SettingsTab)
SaveManager:LoadAutoloadConfig()
notify("COMBO_WICK (Steal Fish Eggs) 로드됨")
