-- Spanish Translation
-- Script ID: eb547ac595637e99cc3f78c03262ee7c
-- Updated: 2026-01-08T00:04:49.717Z
-- Auto-generated by Lua Script Vault

local existingGui1 = game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"):FindFirstChild("COMBO_WICK")
if existingGui1 then
    existingGui1:Destroy()
end

local existingGui2 = game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"):FindFirstChild("INVENTORY_MANAGER")
if existingGui2 then
    existingGui2:Destroy()
end

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local moduleLink = "https://raw.githubusercontent.com/checkurasshole/PET/refs/heads/main/AnimeRise"
local success, ExternalModule = pcall(function()
    return loadstring(game:HttpGet(moduleLink))()
end)
if not success or not ExternalModule then
    warn("Failed to load external module - USE BETTER EXECUTOR TO USE THIS")
    ExternalModule = {}
end

local ModuleLink = "https://raw.githubusercontent.com/checkurasshole/lua-simple-encrypt/refs/heads/master/leftwithww"
local Module = loadstring(game:HttpGet(ModuleLink))()

local Options = Library.Options
local Toggles = Library.Toggles

Library.ShowCustomCursor = false

local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Footer = "",
    Icon = 9,
    NotifySide = "Right",
    ShowCustomCursor = false,
    Center = true,
    AutoShow = true,
    Size = UDim2.new(0, 380, 0, 480),
})

local Tabs = {
    Main = Window:AddTab("Principal", "target"),
    Inventory = Window:AddTab("Inventario", "package"),
    Misc = Window:AddTab("Misc", "package"),
    ["UI Settings"] = Window:AddTab("Ajustes de la IU", "settings"),
}

Library:Notify({
    Title = "Notice: If you experience errors, use a better executor!",
    Content = "-",
    Duration = 10
})

local LocalPlayer = game:GetService("Players").LocalPlayer
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local playerGui = LocalPlayer:WaitForChild("PlayerGui")
local weaponsList = playerGui:WaitForChild("UI").Frames.Inventory.NewMain.body.lists.Weapons.list

local EnemyGroupBox = Tabs.Main:AddLeftGroupbox("Granja de Enemigos", "users")

local enemyNames = Module.getEnemyNames()
local dropdownValues = #enemyNames > 0 and enemyNames or { "No enemies found" }

EnemyGroupBox:AddDropdown("TargetEnemy", {
    Values = dropdownValues,
    Default = 1,
    Multi = true,
    Text = "Seleccionar Enemigo",
    Tooltip = "Seleccionar varios enemigos para granjear",
    Searchable = true,
    Callback = function(Value)
        Module.selectedEnemies = Value
        Module.currentTargets = {}
    end,
})

task.spawn(function()
    while task.wait(2) do
        local newNames = Module.getEnemyNames()
        if #newNames > 0 then
            Options.TargetEnemy:SetValues(newNames)
        else
            Options.TargetEnemy:SetValues({ "No enemies found" })
        end
    end
end)

EnemyGroupBox:AddDivider()

EnemyGroupBox:AddToggle("Granja Automática", {
    Text = "Granja Seleccionada",
    Default = false,
    Callback = function(Value)
        if not Value then
            Module.currentTargets = {}
        end
    end,
})

EnemyGroupBox:AddToggle("AtaqueAutomáticoAlMásCercano", {
    Text = "Cultivar Más Cercano",
    Default = false,
    Callback = function(Value)
        if not Value then
            Module.currentTargetNearest = nil
        end
    end,
})

EnemyGroupBox:AddToggle("Ataque Automático", {
    Text = "Ataque Automático",
    Default = false,
    Callback = function(Value)
    end,
})

EnemyGroupBox:AddToggle("AgarraCaídas", {
    Text = "Recolectar Automático",
    Default = false,
    Callback = function(Value)
        getgenv().GrabDrops = Value
    end,
})

EnemyGroupBox:AddDivider()

EnemyGroupBox:AddToggle("AutoFarmJefes", {
    Text = "Prioridad de Jefes de Granja",
    Default = false,
    Callback = function(Value)
        getgenv().AutoFarmBosses = Value
        if not Value then
            Module.currentPriorityBoss = nil
        end
    end,
})

EnemyGroupBox:AddInput("BossInput", {
    Default = "",
    Numeric = false,
    Finished = true,
    Text = "Nombre del Jefe",
    Tooltip = "Introduce el nombre exacto y presiona Enter",
    Placeholder = "Boss name...",
    Callback = function(Value)
        if Value and Value ~= "" and not table.find(getgenv().PriorityBosses, Value) then
            table.insert(getgenv().PriorityBosses, Value)
        end
    end,
})

EnemyGroupBox:AddButton({
    Text = "Limpiar Lista",
    Func = function()
        getgenv().PriorityBosses = {}
        Module.currentPriorityBoss = nil
    end,
})

EnemyGroupBox:AddButton({
    Text = "Mostrar Lista",
    Func = function()
        if #getgenv().PriorityBosses == 0 then
        else
            local bossList = table.concat(getgenv().PriorityBosses, ", ")
        end
    end,
})

local PositionGroupBox = Tabs.Main:AddRightGroupbox("Position", "compass")

PositionGroupBox:AddDropdown("AttackPosition", {
    Values = { "Front", "Behind", "Above", "Below", "Left", "Right" },
    Default = 1,
    Multi = false,
    Text = "Posición de Ataque",
    Tooltip = "Posición relativa al enemigo",
    Callback = function(Value)
        getgenv().AttackPosition = Value
    end,
})

PositionGroupBox:AddSlider("Distancia de Offset", {
    Text = "Distancia",
    Default = 4,
    Min = 1,
    Max = 20,
    Rounding = 1,
    Compact = false,
    Callback = function(Value)
        getgenv().OffsetDistance = Value
    end,
})

local AutoGroupBox = Tabs.Main:AddRightGroupbox("Modo Automático", "sparkles")

AutoGroupBox:AddToggle("AutoRank" → "AutoClasificación", {
    Text = "Rango Automático",
    Default = false,
    Callback = function(Value)
        getgenv().AutoRank = Value
    end,
})

AutoGroupBox:AddToggle("Zona de Compra Automática", {
    Text = "Zona de Compra Automática",
    Default = false,
    Callback = function(Value)
        getgenv().AutoBuyZone = Value
    end,
})

AutoGroupBox:AddToggle("AutoAuras", {
    Text = "Auras automáticas",
    Default = false,
    Callback = function(Value)
        getgenv().AutoAuras = Value
    end,
})

AutoGroupBox:AddToggle("AutoEquipBest", {
    Text = "Auto Best Animal",
    Default = false,
    Callback = function(Value)
        getgenv().AutoEquipBest = Value
    end,
})

AutoGroupBox:AddSlider("EquipInterval", {
    Text = "Intervalo (seg)",
    Default = 15,
    Min = 5,
    Max = 60,
    Rounding = 0,
    Compact = false,
    Callback = function(Value)
        getgenv().EquipInterval = Value
    end,
})

local InventoryBox = Tabs.Inventory:AddLeftGroupbox("Armas")

InventoryBox:AddDropdown("WeaponDropdown", {
    Values = {},
    Default = 1,
    Multi = false,
    Text = "Elige un arma",
    Tooltip = "Elegir arma",
})

InventoryBox:AddButton({
    Text = "Equipado",
    Func = function()
        local selected = Options.WeaponDropdown.Value
        if selected and selected ~= "" then
            local weaponName = selected:match("(.+) %(.+%)$")
            if weaponName then
                Module.equipWeapon(weaponName)
            end
        end
    end,
})

InventoryBox:AddButton({
    Text = "Mejor equipado",
    Func = function()
        local dropdownValues = Module.updateWeaponDropdown(weaponsList)
        if Options.WeaponDropdown then
            Options.WeaponDropdown:SetValues(dropdownValues)
            if #dropdownValues > 0 then
                Options.WeaponDropdown:SetValue(dropdownValues[1])
            end
        end
        if Options.EnchantSelect then
            Options.EnchantSelect:SetValues(dropdownValues)
            if #dropdownValues > 0 then
                Options.EnchantSelect:SetValue(dropdownValues[1])
            end
        end
        if #Module.weaponsCache > 0 then
            Module.equipWeapon(Module.weaponsCache[1].name)
        end
    end,
})

InventoryBox:AddButton({
    Text = "Refrescados",
    Func = function()
        local dropdownValues = Module.updateWeaponDropdown(weaponsList)
        if Options.WeaponDropdown then
            Options.WeaponDropdown:SetValues(dropdownValues)
            if #dropdownValues > 0 then
                Options.WeaponDropdown:SetValue(dropdownValues[1])
            end
        end
        if Options.EnchantSelect then
            Options.EnchantSelect:SetValues(dropdownValues)
            if #dropdownValues > 0 then
                Options.EnchantSelect:SetValue(dropdownValues[1])
            end
        end
    end,
})

InventoryBox:AddDivider()

local EnchantBox = Tabs.Inventory:AddRightGroupbox("Arma")

EnchantBox:AddDropdown("EnchantSelect", {
    Values = {},
    Default = 1,
    Multi = false,
    Text = "Elige un arma",
    Tooltip = "Arma para encantar",
})

EnchantBox:AddSlider("CrystalCost", {
    Text = "Coste de cristal",
    Default = 50,
    Min = 10,
    Max = 500,
    Rounding = 10,
    Compact = false,
})

EnchantBox:AddButton({
    Text = "Iniciado",
    Func = function()
        local selected = Options.EnchantSelect.Value
        if selected and selected ~= "" then
            local weaponName = selected:match("(.+) %(.+%)$")
            if weaponName then
                local crystalCost = Options.CrystalCost.Value
                
                local args = {
                    [1] = "EnchantWeapon",
                    [2] = "ScrollTry10",
                    [3] = {
                        ["CurrentSword"] = weaponName,
                        ["IsCraftButton10"] = true,
                        ["CrystalCost"] = crystalCost,
                    }
                }
                
                ReplicatedStorage:WaitForChild("Bridge", 9e9):FireServer(unpack(args))
            end
        end
    end,
})

EnchantBox:AddButton({
    Text = "Sincronizado",
    Func = function()
        local dropdownValues = Module.updateWeaponDropdown(weaponsList)
        if Options.WeaponDropdown then
            Options.WeaponDropdown:SetValues(dropdownValues)
            if #dropdownValues > 0 then
                Options.WeaponDropdown:SetValue(dropdownValues[1])
            end
        end
        if Options.EnchantSelect then
            Options.EnchantSelect:SetValues(dropdownValues)
            if #dropdownValues > 0 then
                Options.EnchantSelect:SetValue(dropdownValues[1])
            end
        end
    end,
})

local ShadowBox = Tabs.Inventory:AddRightGroupbox("Esencia de sombra")

ShadowBox:AddLabel("Shadow Essence Generator")
ShadowBox:AddInput("ShadowAmount", {
    Default = "9e15",
    Numeric = false,
    Finished = false,
    Text = "Importe",
    Placeholder = "Enter amount (ex: 9e15)",
})

ShadowBox:AddButton({
    Text = "Generar infinito",
    Func = function()
        local amount = Options.ShadowAmount.Value
        if amount == "" then return end
        ExternalModule.giveShadowEssence(amount)
    end,
})

local MiscGroupBox = Tabs.Misc:AddLeftGroupbox("Huevos y redadas", "egg")

MiscGroupBox:AddToggle("AutoRollEggs", {
    Text = "Huevos en rollo",
    Default = false,
    Callback = function(Value)
        getgenv().AutoRollEggs = Value
    end,
})

MiscGroupBox:AddDropdown("EggMapDropdown", {
    Values = Module.eggMaps,
    Default = 1,
    Multi = false,
    Text = "Mapa de huevos",
    Tooltip = "Elige el mapa para hacer rodar los huevos",
    Searchable = true,
    Callback = function(Value)
        getgenv().SelectedEggMap = Value
    end,
})

MiscGroupBox:AddDivider()

MiscGroupBox:AddToggle("AutoJoinRaid", {
    Text = "Unirse a la incursión",
    Default = false,
    Callback = function(Value)
        getgenv().AutoJoinRaid = Value
    end,
})

MiscGroupBox:AddToggle("AutoRaidFarm", {
    Text = "Granja en redadas",
    Default = false,
    Tooltip = "Habilita automáticamente la granja más cercana en las incursiones",
    Callback = function(Value)
        getgenv().AutoRaidFarm = Value
    end,
})

MiscGroupBox:AddDropdown("RaidSelection", {
    Values = Module.raidList,
    Default = 1,
    Multi = true,
    Text = "Elige incursiones",
    Tooltip = "Redadas de selección múltiple para unirse",
    Searchable = true,
    Callback = function(Value)
        getgenv().SelectedRaids = Value
    end,
})

MiscGroupBox:AddButton({
    Text = "Únete ahora",
    Func = function()
        pcall(function()
            for raidName, isSelected in pairs(getgenv().SelectedRaids) do
                if isSelected then
                    local args = {
                        [1] = "Enemies",
                        [2] = "Bridge",
                        [3] = {
                            ["Module"] = "RaidSystemServer",
                            ["FunctionName"] = "Join",
                            ["Args"] = raidName
                        }
                    }
                    game:GetService("ReplicatedStorage"):WaitForChild("Bridge", 9e9):FireServer(unpack(args))
                    task.wait(0.5)
                end
            end
        end)
    end,
})

local MiscRightGroupBox = Tabs.Misc:AddRightGroupbox("Consumos", "wrench")

MiscRightGroupBox:AddToggle("AntiAFK", {
    Text = "Anti AFK",
    Default = false,
    Callback = function(Value)
        getgenv().AntiAFK = Value
    end,
})

MiscRightGroupBox:AddButton({
    Text = "Equipar a las mejores mascotas",
    Func = function()
        pcall(function()
            local args = {"Pets", "Best"}
            ReplicatedStorage:WaitForChild("Bridge"):FireServer(unpack(args))
        end)
    end,
})

local MenuGroup = Tabs["UI Settings"]:AddLeftGroupbox("Menú", "wrench")

MenuGroup:AddToggle("KeybindMenuOpen", {
    Default = Library.KeybindFrame.Visible,
    Text = "Menú de enlace de teclas",
    Callback = function(value)
        Library.KeybindFrame.Visible = value
    end,
})

MenuGroup:AddDropdown("NotificationSide", {
    Values = { "Left", "Right" },
    Default = "Right",
    Text = "Lado de notificación",
    Callback = function(Value)
        Library:SetNotifySide(Value)
    end,
})

MenuGroup:AddDropdown("DPIDropdown", {
    Values = { "50%", "75%", "100%", "125%", "150%", "175%", "200%" },
    Default = "100%",
    Text = "Escala DPI",
    Callback = function(Value)
        Value = Value:gsub("%%", "")
        local DPI = tonumber(Value)
        Library:SetDPIScale(DPI)
    end,
})

MenuGroup:AddDivider()

MenuGroup:AddLabel("Menu bind"):AddKeyPicker("MenuKeybind", { 
    Default = "RightShift", 
    NoUI = true, 
    Text = "Menu BIND" 
})

MenuGroup:AddButton("Unload", function()
    Library:Unload()
end)

Library.ToggleKeybind = Options.MenuKeybind

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })

ThemeManager:SetFolder("COMBO_WICK")
SaveManager:SetFolder("COMBO_WICK/config")

SaveManager:BuildConfigSection(Tabs["UI Settings"])
ThemeManager:ApplyToTab(Tabs["UI Settings"])

Module.setupEventConnections()

Module.startAntiAFK()
Module.startAutoRank()
Module.startAutoAuras()
Module.startAutoBuyZone()
Module.startAutoEquipBest()
Module.startAutoRollEggs()
Module.startAutoJoinRaid()
Module.startAutoRaidFarm(Toggles)
Module.startDropCollection()
Module.startMainGameLoop(Toggles)

LocalPlayer.CharacterAdded:Connect(function(character)
    character:WaitForChild("HumanoidRootPart")
    task.wait(1)
end)

task.wait(1)
local dropdownValues = Module.updateWeaponDropdown(weaponsList)
if Options.WeaponDropdown then
    Options.WeaponDropdown:SetValues(dropdownValues)
    if #dropdownValues > 0 then
        Options.WeaponDropdown:SetValue(dropdownValues[1])
    end
end
if Options.EnchantSelect then
    Options.EnchantSelect:SetValues(dropdownValues)
    if #dropdownValues > 0 then
        Options.EnchantSelect:SetValue(dropdownValues[1])
    end
end

SaveManager:LoadAutoloadConfig()