-- Portuguese Translation
-- Script ID: f25456de3acbd9b24630a1d2d9c7baaa
-- Updated: 2025-12-18T20:46:40.801Z
-- Auto-generated by Lua Script Vault

if _G.ComboWickLoaded then
    return
end
_G.ComboWickLoaded = true

local repo = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/"
local Library = loadstring(game:HttpGet(repo .. "Library.lua"))()
local ThemeManager = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))()
local SaveManager = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()

local Module = loadstring(game:HttpGet("https://raw.githubusercontent.com/checkurasshole/INK/refs/heads/main/Jurrasicscript"))()

Module.initConnections()

local Window = Library:CreateWindow({
    Title = "COMBO_WICK",
    Icon = 7734068321,
    NotifySide = "Right",
    ShowCustomCursor = true,
    Size = UDim2.new(0, 500, 0, 400),
})

local Tabs = {
    Main = Window:AddTab("Princ.", "zap"),
    Amber = Window:AddTab("Amber", "gem"),
    Utility = Window:AddTab("Definições", "wrench"),
}

local MainWalkspeed = Tabs.Main:AddLeftGroupbox("Velocidade de caminhada", "activity")
MainWalkspeed:AddToggle("WalkspeedToggle", {
    Text = "Ativar Velocidade de Caminhada",
    Default = false,
    Callback = function(Value)
        Module.toggleWalkspeed(Value)
    end,
})
MainWalkspeed:AddSlider("WalkspeedSlider", {
    Text = "Valor da Velocidade de Caminhada",
    Default = 16,
    Min = 1,
    Max = 150,
    Rounding = 1,
    Callback = function(Value)
        Module.updateWalkspeed(Value)
    end,
})

local MainNPC = Tabs.Main:AddLeftGroupbox("Animal Farm", "crosshair")
MainNPC:AddToggle("ESPToggle", {
    Text = "Nome do ESP",
    Default = false,
    Callback = function(Value)
        Module.toggleESP(Value)
    end,
})
MainNPC:AddToggle("HighlightToggle", {
    Text = "Marcador ESP",
    Default = false,
    Callback = function(Value)
        Module.toggleHighlight(Value)
    end,
})
MainNPC:AddToggle("NPCTeleportToggle", {
    Text = "Teletransportar para cabras",
    Default = false,
    Callback = function(Value)
        Module.toggleNPCTeleport(Value)
    end,
})
MainNPC:AddSlider("NPCDistance", {
    Text = "Distância Atrás",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.npcBehindDistance = Value
        if Module.State.npcTeleportEnabled and Module.State.currentNPCTarget then
            Module.anchorToNPC(Module.State.currentNPCTarget)
        end
    end,
})
MainNPC:AddButton({
    Text = "Próximo PNJ",
    Func = function()
        if Module.State.npcTeleportEnabled then
            local newTarget = Module.switchToNextNPC()
            if newTarget then
                Module.State.currentNPCTarget = newTarget
                Module.anchorToNPC(Module.State.currentNPCTarget)
            end
        end
    end,
})

local MainBoss = Tabs.Main:AddLeftGroupbox("Boss Farm", "skull")
MainBoss:AddToggle("BossTeleportToggle", {
    Text = "Teletransportar para o chefe D-Rex",
    Default = false,
    Callback = function(Value)
        Module.toggleBossTeleport(Value)
    end,
})
MainBoss:AddSlider("BossDistance", {
    Text = "Distância Atrás",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.bossBehindDistance = Value
        if Module.State.bossTeleportEnabled and Module.State.currentBossTarget then
            Module.anchorToBoss(Module.State.currentBossTarget)
        end
    end,
})
MainBoss:AddButton({
    Text = "Próximo Chefe",
    Func = function()
        if Module.State.bossTeleportEnabled then
            local newTarget = Module.switchToNextBoss()
            if newTarget then
                Module.State.currentBossTarget = newTarget
                Module.anchorToBoss(Module.State.currentBossTarget)
            end
        end
    end,
})

local MainCombat = Tabs.Main:AddRightGroupbox("Combate", "sword")
MainCombat:AddToggle("AutoAttackToggle", {
    Text = "Ataque automático",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoAttack(Value)
    end,
})
MainCombat:AddToggle("AutoHeavyToggle", {
    Text = "Modo de Combate",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoHeavy(Value)
    end,
})
MainCombat:AddButton({
    Text = "Despertar Instantâneo",
    Func = function()
        Module.executeInstantDespawn()
    end,
})

local MainPlayer = Tabs.Main:AddRightGroupbox("Quinta de Jogadores", "users")
MainPlayer:AddToggle("TeleportToggle", {
    Text = "Teletransportar para jogadores",
    Default = false,
    Callback = function(Value)
        Module.State.teleporting = Value
        if Module.State.teleporting then
            Module.State.playerIndex = 0
            Module.State.currentTarget = Module.getNextTarget()
            if Module.State.currentTarget then
                Module.anchorToPlayer(Module.State.currentTarget)
            end
        else
            Module.State.currentTarget = nil
        end
    end,
})
MainPlayer:AddToggle("TargetMovingToggle", {
    Text = "Alvo em movimento",
    Default = true,
    Callback = function(Value)
        Module.State.targetMovingPlayers = Value
        if not Module.State.targetMovingPlayers and not Module.State.targetStillPlayers then
            Module.State.targetStillPlayers = true
        end
    end,
})
MainPlayer:AddToggle("TargetStillToggle", {
    Text = "Alvo em pé",
    Default = true,
    Callback = function(Value)
        Module.State.targetStillPlayers = Value
        if not Module.State.targetMovingPlayers and not Module.State.targetStillPlayers then
            Module.State.targetMovingPlayers = true
        end
    end,
})
MainPlayer:AddSlider("AtrásDistância", {
    Text = "Distância Atrás",
    Default = 5,
    Min = 1,
    Max = 100,
    Rounding = 1,
    Callback = function(Value)
        Module.State.behindDistance = Value
        if Module.State.teleporting and Module.State.currentTarget then
            Module.anchorToPlayer(Module.State.currentTarget)
        end
    end,
})
MainPlayer:AddButton({
    Text = "Destino Seguinte >",
    Func = function()
        if Module.State.teleporting then
            local validPlayers = Module.getValidPlayers()
            if #validPlayers > 0 then
                Module.State.currentTarget = Module.getNextTarget()
                if Module.State.currentTarget then
                    Module.anchorToPlayer(Module.State.currentTarget)
                end
            end
        end
    end,
})

local AmberV1 = Tabs.Amber:AddLeftGroupbox("Âmbar V1", "gem")
AmberV1:AddToggle("AmberV1Toggle", {
    Text = "Amber Collection",
    Default = false,
    Callback = function(Value)
        Module.toggleAmberCollectionSwim(Value)
    end,
})

local AmberV2 = Tabs.Amber:AddRightGroupbox("Âmbar V2", "zap")
AmberV2:AddToggle("AmberV2Toggle", {
    Text = "Colete Moedas de Dinossauro v2",
    Default = false,
    Callback = function(Value)
        Module.toggleAmberCollection(Value)
    end,
})
AmberV2:AddToggle("AutoSpawnToggle", {
    Text = "Reanimação Automática",
    Default = false,
    Callback = function(Value)
        Module.State.AUTO_SPAWN_ENABLED = Value
        if Value then
            Module.State.lastVisibleGuis = {}
        end
    end,
})
AmberV2:AddDropdown("DinoSelection", {
    Values = Module.allDinosaurs,
    Default = "Gallimimus",
    Text = "Selecionar dinossauro",
    Callback = function(Value)
        Module.State.selectedDino = Value
        Module.State.SPAWN_ARGS = { [1] = Value }
    end,
})
AmberV2:AddButton({
    Text = "Surgimento Manual Selecionado",
    Func = function()
        Module.executeSpawn()
    end,
})
AmberV2:AddSlider("AmberTimeout", {
    Text = "Tempo Esgotado (s)",
    Default = 15,
    Min = 5,
    Max = 60,
    Rounding = 1,
    Callback = function(Value)
        Module.State.amberAttemptTimeout = Value
    end,
})

local AmberV3 = Tabs.Amber:AddLeftGroupbox("Melhor Versão mais rápida do âmbar", "zap")
local linkText = "Buy Premium Best DinoCoin Script here:\nhttps://discord.gg/9FWBQnVXCy"
AmberV3:AddLabel(linkText)
AmberV3:AddButton("Copy Link", function()
    if setclipboard then
        setclipboard("https://discord.gg/9FWBQnVXCy")
    elseif toclipboard then
        toclipboard("https://discord.gg/9FWBQnVXCy")
    else
        warn("Clipboard not supported in this executor")
    end
end)

local UtilityAntiVoid = Tabs.Utility:AddLeftGroupbox("Antivazio", "shield")
UtilityAntiVoid:AddToggle("AntiVoidToggle", {
    Text = "Contrariar o Vazio",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableAntiVoid()
        else
            Module.disableAntiVoid()
        end
    end,
})

local UtilityOther = Tabs.Utility:AddLeftGroupbox("Outros", "zap")
UtilityOther:AddToggle("NoclipToggle", {
    Text = "Noclip",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableNoclip()
        else
            Module.disableNoclip()
        end
    end,
})
UtilityOther:AddToggle("AntiAFKToggle", {
    Text = "Anti-AFK",
    Default = false,
    Callback = function(Value)
        if Value then
            Module.enableAntiAfk()
        else
            Module.disableAntiAfk()
        end
    end,
})
UtilityOther:AddToggle("StaffWatchToggle", {
    Text = "À procura de um martelo de proibição (vigia de pessoal)",
    Default = false,
    Callback = function(Value)
        Module.toggleStaffWatch(Value)
    end,
})

local Combat = Tabs.Utility:AddRightGroupbox("Combate", "sword")
Combat:AddToggle("AutoAttackToggle", {
    Text = "Ataque automático",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoAttack(Value)
    end,
})
Combat:AddToggle("AutoHeavyToggle", {
    Text = "Modo de Combate",
    Default = false,
    Callback = function(Value)
        Module.toggleAutoHeavy(Value)
    end,
})
Combat:AddButton({
    Text = "Suicídio Rápido (desespero)",
    Func = function()
        Module.executeInstantDespawn()
    end,
})

local UISettings = Tabs.Utility:AddRightGroupbox("Interface UI", "settings")
UISettings:AddToggle("KeybindMenuAberto", {
    Default = Library.KeybindFrame.Visible,
    Text = "Abrir Menu Keybind",
    Callback = function(value)
        Library.KeybindFrame.Visible = value
    end,
})
UISettings:AddToggle("ShowCustomCursor", {
    Text = "Cursor Personalizado",
    Default = true,
    Callback = function(Value)
        Library.ShowCustomCursor = Value
    end,
})
UISettings:AddDropdown("NotificationSide", {
    Values = { "Left", "Right" },
    Default = "Right",
    Text = "Lado da notificação",
    Callback = function(Value)
        Library:SetNotifySide(Value)
    end,
})
UISettings:AddButton("Unload", function()
    Library:Unload()
end)

ThemeManager:SetLibrary(Library)
SaveManager:SetLibrary(Library)
SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({ "MenuKeybind" })
ThemeManager:SetFolder("ComboChronicle")
SaveManager:SetFolder("ComboChronicle")
SaveManager:BuildConfigSection(Tabs.Utility)
ThemeManager:ApplyToTab(Tabs.Utility)

game:BindToClose(Module.cleanup)
SaveManager:LoadAutoloadConfig()